/**
 * LOGISTICSHUB — MOCK DATA: Alerts Center
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 3 (Alerts Center)
 */

export const alertsMetrics = {
  totalAlerts: 267,
  criticalCount: 14,
  highCount: 42,
  unassignedCount: 38,
  resolvedToday: 89,
  avgMTTR: '18 mins',
};

export const alertsList = [
  {
    id: 'ALT-9821',
    severity: 'critical',
    type: 'Temperature Breach',
    title: 'Reefer Temp Exceeded (+12.5°C)',
    description: 'Cold chain container temp reached +12.5°C (max allowed +4.0°C) for over 20 minutes.',
    entityType: 'Shipment',
    entityId: 'SHP-100247',
    vehicleId: 'VEH-0102',
    driverName: 'Anil Patel',
    location: 'NH-48 Km 114, Rajasthan',
    assignee: { name: 'Priya Sharma', avatar: 'PS' },
    status: 'Investigating',
    timestamp: '8 mins ago',
    createdDate: '2026-09-27 21:54',
    rootCause: 'Compressor belt slippage on reefer unit #2.',
    historyLog: [
      { time: '21:54', user: 'IoT Telemetry System', action: 'Alert triggered by sensor #TC-44' },
      { time: '21:58', user: 'Priya Sharma', action: 'Assigned incident & contacted driver' },
    ],
  },
  {
    id: 'ALT-9822',
    severity: 'critical',
    type: 'Vehicle Breakdown',
    title: 'Transmission Lock — VEH-0102',
    description: 'Vehicle reported complete transmission failure on high-speed corridor.',
    entityType: 'Vehicle',
    entityId: 'VEH-0102',
    vehicleId: 'VEH-0102',
    driverName: 'Anil Patel',
    location: 'NH-48 Km 114, Rajasthan',
    assignee: null,
    status: 'Unassigned',
    timestamp: '14 mins ago',
    createdDate: '2026-09-27 21:48',
    rootCause: 'Hydraulic fluid leak in transmission casing.',
    historyLog: [
      { time: '21:48', user: 'OBD-II Telemetry', action: 'DTC Code P0700 Transmission Control System Error' },
    ],
  },
  {
    id: 'ALT-9823',
    severity: 'high',
    type: 'Delivery Delay',
    title: 'Delay Expected (+3h 15m) — SHP-100246',
    description: 'Highway blockade due to overturned tanker causing 5km traffic tailback.',
    entityType: 'Shipment',
    entityId: 'SHP-100246',
    vehicleId: 'VEH-0089',
    driverName: 'Suresh Sharma',
    location: 'Mumbai-Pune Expressway Km 42',
    assignee: { name: 'Rahul Verma', avatar: 'RV' },
    status: 'Action Required',
    timestamp: '22 mins ago',
    createdDate: '2026-09-27 21:40',
    rootCause: 'Severe traffic congestion at Lonavala exit.',
    historyLog: [
      { time: '21:40', user: 'ETA Predictor API', action: 'Delay calculated > 180m threshold' },
      { time: '21:45', user: 'Rahul Verma', action: 'Notified customer logistics contact' },
    ],
  },
  {
    id: 'ALT-9824',
    severity: 'high',
    type: 'Geofence Exit Delay',
    title: 'Unplanned Stop Exceeded 30m',
    description: 'Vehicle stayed outside designated corridor for over 45 minutes.',
    entityType: 'Vehicle',
    entityId: 'VEH-0210',
    vehicleId: 'VEH-0210',
    driverName: 'Deepak Tiwari',
    location: 'Vellore Bypass Plaza',
    assignee: null,
    status: 'Unassigned',
    timestamp: '32 mins ago',
    createdDate: '2026-09-27 21:30',
    rootCause: 'Unscheduled driver rest stop.',
    historyLog: [
      { time: '21:30', user: 'Geofence Monitor', action: 'Exit alert triggered outside zone GEO-05' },
    ],
  },
  {
    id: 'ALT-9825',
    severity: 'medium',
    type: 'Document Expiry',
    title: 'E-Way Bill Expiring in 2h',
    description: 'E-Way bill #99102384 for shipment SHP-100249 expires at 00:00.',
    entityType: 'Document',
    entityId: 'EWAY-99102384',
    vehicleId: 'VEH-0198',
    driverName: 'Manoj Verma',
    location: 'Surat Hub',
    assignee: { name: 'Kavita Roy', avatar: 'KR' },
    status: 'Investigating',
    timestamp: '45 mins ago',
    createdDate: '2026-09-27 21:17',
    rootCause: 'Transit duration exceeded initial estimated window.',
    historyLog: [
      { time: '21:17', user: 'Compliance Engine', action: 'Auto-generated renewal reminder' },
    ],
  },
  {
    id: 'ALT-9826',
    severity: 'medium',
    type: 'Late Pickup',
    title: 'Carrier Pickup Window Missed',
    description: 'Spot Carrier arrived 40 minutes past scheduled dock window.',
    entityType: 'Order',
    entityId: 'ORD-2024-0891',
    vehicleId: 'VEH-0045',
    driverName: 'Ramesh Kumar',
    location: 'Mumbai Central WH',
    assignee: { name: 'Amit Patel', avatar: 'AP' },
    status: 'Resolved',
    timestamp: '1 hour ago',
    createdDate: '2026-09-27 21:00',
    rootCause: 'Gate queue congestion at Gate A.',
    historyLog: [
      { time: '21:00', user: 'Dock Manager System', action: 'Pickup delay recorded' },
      { time: '21:30', user: 'Amit Patel', action: 'Reassigned to Dock 3 & marked resolved' },
    ],
  },
  {
    id: 'ALT-9827',
    severity: 'low',
    type: 'Speeding Alert',
    title: 'Speed Violation (88 km/h)',
    description: 'Vehicle exceeded 80 km/h speed limit for 5 minutes on state highway.',
    entityType: 'Driver',
    entityId: 'DRV-4091',
    vehicleId: 'VEH-0155',
    driverName: 'Vijay Singh',
    location: 'NH-44 Hyderabad Corridor',
    assignee: { name: 'System Auto', avatar: 'SA' },
    status: 'Resolved',
    timestamp: '2 hours ago',
    createdDate: '2026-09-27 20:00',
    rootCause: 'Downhill gradient speed acceleration.',
    historyLog: [
      { time: '20:00', user: 'Telematics ECU', action: 'Speed governor warning dispatched to driver app' },
    ],
  },
];
