/**
 * Comprehensive Mock Data for Carrier Management, Rate Cards, Contracts, and Transporter Portal
 * Enterprise-grade datasets for 3PLs, fleet owners, contracted linehaul rates, and transporter self-service.
 */

// ── 1. Carrier Network Summary Statistics ──
export const carriersSummaryStats = {
  totalRegisteredCarriers: 218,
  preferredTier1Count: 48,
  aggregateFleetPool: '4,850+ Trucks',
  avgPlacementAcceptancePct: 96.8,
  activeDispatchesCount: 184,
  onTimeDeliveryPct: 97.4,
  averageTripTransitDays: 2.8,
  totalMonthlyFreightPayout: '₹ 42.80 Cr',
};

// ── 2. Enterprise Carrier & Transporter Directory ──
export const carriersList = [
  {
    id: 'CRR-001',
    code: 'VRL-LOG-01',
    name: 'VRL Logistics Limited',
    legalName: 'VRL Logistics Hubballi Surface Division',
    gstin: '29AAACV2450M1Z6',
    pan: 'AAACV2450M',
    tier: 'Tier 1 Preferred',
    verificationStatus: 'Verified (KYC Active)',
    rating: 4.9,
    fleetSize: 1450,
    fleetBreakdown: {
      '32ft Multi-Axle MX': 650,
      '40ft High-Cube Trailer': 380,
      '24ft Container Truck': 320,
      '32ft Insulated Reefer': 100,
    },
    primaryHubs: ['Hubballi (HQ)', 'Mumbai Bhiwandi', 'Bangalore Nelamangala', 'Delhi NCR Bilaspur'],
    primaryLanes: ['Mumbai → Bangalore', 'Pune → Chennai', 'Delhi NCR → Ahmedabad', 'Hyderabad → Kolkata'],
    placementAcceptancePct: 98.6,
    onTimeDeliveryPct: 98.2,
    claimsRatioPct: 0.08,
    activeTripsCount: 42,
    monthlyVolumeMt: 9800,
    annualFreightGmv: 58400000,
    accountLead: 'Rameshwar Patil (Carrier Ops VP)',
    accountLeadPhone: '+91 98201 55670',
    contacts: [
      { name: 'Kiran Rao', role: 'Head of Fleet Placement', email: 'kiran.r@vrl.in', phone: '+91 98450 33410' },
      { name: 'Sanjay Hegde', role: 'Regional Linehaul Dispatcher', email: 'sanjay.h@vrl.in', phone: '+91 98450 33411' },
      { name: 'Sunil Deshmukh', role: 'Billing & Settlement Lead', email: 'billing@vrl.in', phone: '+91 98450 33412' },
    ],
    bankDetails: {
      bankName: 'HDFC Bank Ltd',
      accountNo: '50200098124501',
      ifsc: 'HDFC0000123',
      branch: 'Hubballi Main Branch',
    },
    status: 'Active (Healthy)',
  },
  {
    id: 'CRR-002',
    code: 'TCI-FRT-02',
    name: 'TCI Freight Supply Chain',
    legalName: 'Transport Corporation of India Ltd (TCI Freight)',
    gstin: '06AAACT0340N1ZF',
    pan: 'AAACT0340N',
    tier: 'Tier 1 Preferred',
    verificationStatus: 'Verified (KYC Active)',
    rating: 4.8,
    fleetSize: 1850,
    fleetBreakdown: {
      '32ft Multi-Axle MX': 820,
      '40ft High-Cube Trailer': 550,
      '24ft Container Truck': 380,
      'Heavy ODC Hydraulic Axle': 100,
    },
    primaryHubs: ['Gurugram (HQ)', 'Kolkata Dankuni', 'Mumbai Kalamboli', 'Chennai Sriperumbudur'],
    primaryLanes: ['Delhi NCR → Kolkata', 'Mumbai → Chennai', 'Jamshedpur → Mumbai', 'Ahmedabad → Bangalore'],
    placementAcceptancePct: 97.9,
    onTimeDeliveryPct: 97.6,
    claimsRatioPct: 0.12,
    activeTripsCount: 38,
    monthlyVolumeMt: 12400,
    annualFreightGmv: 74200000,
    accountLead: 'Deepak Sharma (Lead Regional KAM)',
    accountLeadPhone: '+91 98110 44901',
    contacts: [
      { name: 'Virendra Singh', role: 'National Placement Desk', email: 'virendra.s@tcifreight.in', phone: '+91 98110 88912' },
      { name: 'Pooja Varma', role: 'Freight Audit & Invoicing', email: 'pooja.v@tcifreight.in', phone: '+91 98110 88913' },
    ],
    bankDetails: {
      bankName: 'State Bank of India',
      accountNo: '304910284910',
      ifsc: 'SBIN0004210',
      branch: 'Gurugram Corporate Banking',
    },
    status: 'Active (Healthy)',
  },
  {
    id: 'CRR-003',
    code: 'SAF-EXP-03',
    name: 'Safexpress Logistics',
    legalName: 'Safexpress Private Limited Supply Chain Division',
    gstin: '07AAACS6701L1ZT',
    pan: 'AAACS6701L',
    tier: 'Tier 1 Preferred',
    verificationStatus: 'Verified (KYC Active)',
    rating: 4.9,
    fleetSize: 920,
    fleetBreakdown: {
      '24ft Container Truck': 420,
      '32ft Single-Axle SXL': 320,
      '32ft Multi-Axle MX': 180,
    },
    primaryHubs: ['New Delhi (HQ)', 'Nagpur Logistics Hub', 'Bangalore Nelamangala', 'Guwahati North'],
    primaryLanes: ['Delhi NCR → Guwahati', 'Nagpur → Bangalore', 'Mumbai → Indore', 'Kolkata → Patna'],
    placementAcceptancePct: 99.1,
    onTimeDeliveryPct: 98.7,
    claimsRatioPct: 0.05,
    activeTripsCount: 26,
    monthlyVolumeMt: 6400,
    annualFreightGmv: 42100000,
    accountLead: 'Anurag Mathur (Express Linehaul VP)',
    accountLeadPhone: '+91 98100 22340',
    contacts: [
      { name: 'Tarun Saxena', role: 'Operations & Route Control', email: 'tarun.s@safexpress.com', phone: '+91 98100 77123' },
    ],
    bankDetails: {
      bankName: 'ICICI Bank Ltd',
      accountNo: '000405018923',
      ifsc: 'ICIC0000004',
      branch: 'Connaught Place New Delhi',
    },
    status: 'Active (Healthy)',
  },
  {
    id: 'CRR-004',
    code: 'DEL-ENT-04',
    name: 'Delhivery Full-Truckload (FTL)',
    legalName: 'Delhivery Limited Freight & Part-Truckload Network',
    gstin: '06AAACD7401K1ZQ',
    pan: 'AAACD7401K',
    tier: 'Tier 1 Preferred',
    verificationStatus: 'Verified (KYC Active)',
    rating: 4.7,
    fleetSize: 1100,
    fleetBreakdown: {
      '32ft Multi-Axle MX': 520,
      '40ft High-Cube Trailer': 310,
      '24ft Container Truck': 270,
    },
    primaryHubs: ['Tauru Mega-Gateway (Haryana)', 'Bhiwandi Hub', 'Bengaluru Hub', 'Farukhnagar'],
    primaryLanes: ['Delhi NCR → Mumbai', 'Bengaluru → Hyderabad', 'Ahmedabad → Pune', 'Chennai → Kochi'],
    placementAcceptancePct: 96.4,
    onTimeDeliveryPct: 96.9,
    claimsRatioPct: 0.14,
    activeTripsCount: 31,
    monthlyVolumeMt: 8200,
    annualFreightGmv: 51200000,
    accountLead: 'Abhishek Roy (FTL Network Manager)',
    accountLeadPhone: '+91 98180 99812',
    contacts: [
      { name: 'Neha Gupta', role: 'Shipper Desk Coordinator', email: 'neha.g@delhivery.com', phone: '+91 98180 33412' },
    ],
    bankDetails: {
      bankName: 'Axis Bank Ltd',
      accountNo: '914020038910293',
      ifsc: 'UTIB0000140',
      branch: 'Cyber City Gurugram',
    },
    status: 'Active (Healthy)',
  },
  {
    id: 'CRR-005',
    code: 'CJD-LOG-05',
    name: 'CJ Darcl Logistics Limited',
    legalName: 'CJ Darcl Logistics Heavy Haul & Multimodal',
    gstin: '06AAACC1209M1ZR',
    pan: 'AAACC1209M',
    tier: 'Tier 2 Approved',
    verificationStatus: 'Verified (KYC Active)',
    rating: 4.6,
    fleetSize: 780,
    fleetBreakdown: {
      '40ft High-Cube Trailer': 380,
      '32ft Multi-Axle MX': 260,
      'Heavy ODC Flatbeds': 140,
    },
    primaryHubs: ['Delhi NCR (HQ)', 'Kandla Port', 'Jamshedpur', 'Pune SEZ'],
    primaryLanes: ['Kandla Port → Delhi NCR', 'Jamshedpur → Pune', 'Mumbai → Raipur'],
    placementAcceptancePct: 95.2,
    onTimeDeliveryPct: 95.8,
    claimsRatioPct: 0.18,
    activeTripsCount: 19,
    monthlyVolumeMt: 5900,
    annualFreightGmv: 36800000,
    accountLead: 'Harish Darcl',
    accountLeadPhone: '+91 98120 77120',
    contacts: [
      { name: 'Manish Verma', role: 'ODC & Project Cargo Lead', email: 'manish.v@cjdarcl.com', phone: '+91 98120 55432' },
    ],
    bankDetails: {
      bankName: 'Kotak Mahindra Bank',
      accountNo: '281092839102',
      ifsc: 'KKBK0000281',
      branch: 'Delhi Nehru Place',
    },
    status: 'Active (Healthy)',
  },
  {
    id: 'CRR-006',
    code: 'GAT-KWE-06',
    name: 'Gati KWE Surface Express',
    legalName: 'Gati-Kintetsu Express Private Limited',
    gstin: '36AAACG4101N1ZY',
    pan: 'AAACG4101N',
    tier: 'Tier 2 Approved',
    verificationStatus: 'KYC Expiring Soon',
    rating: 4.5,
    fleetSize: 640,
    fleetBreakdown: {
      '24ft Container Truck': 310,
      '32ft Multi-Axle MX': 220,
      '32ft Insulated Reefer': 110,
    },
    primaryHubs: ['Hyderabad (HQ)', 'Nagpur Hub', 'Bhiwandi Hub', 'Chennai Hub'],
    primaryLanes: ['Hyderabad → Bangalore', 'Nagpur → Pune', 'Chennai → Madurai'],
    placementAcceptancePct: 94.1,
    onTimeDeliveryPct: 94.8,
    claimsRatioPct: 0.22,
    activeTripsCount: 15,
    monthlyVolumeMt: 4100,
    annualFreightGmv: 28900000,
    accountLead: 'Prasad Reddy',
    accountLeadPhone: '+91 98490 22340',
    contacts: [
      { name: 'Rajesh Naidu', role: 'Fleet Placement Head', email: 'rajesh.n@gatikwe.com', phone: '+91 98490 11982' },
    ],
    bankDetails: {
      bankName: 'Yes Bank Ltd',
      accountNo: '002891028391',
      ifsc: 'YESB0000028',
      branch: 'Hyderabad Somajiguda',
    },
    status: 'Audit Review (Pending Renewal)',
  },
];

// ── 3. Master Rate Cards Dataset ──
export const rateCardsList = [
  {
    id: 'RC-901',
    carrierId: 'CRR-001',
    carrierName: 'VRL Logistics Limited',
    contractCode: 'VRL-MSA-2025-01',
    lane: 'Mumbai (Bhiwandi) → Delhi NCR (Bilaspur)',
    originCity: 'Mumbai Bhiwandi',
    destinationCity: 'Delhi NCR Bilaspur',
    distanceKm: 1420,
    vehicleType: '32ft Multi-Axle MX (18 MT)',
    baseRate: 48500,
    rateType: 'Per Trip Fixed',
    fscFormula: 'Base Diesel ₹90/L + 1% per ₹1.50 rise',
    freeDetentionHours: 4,
    detentionRatePerDay: 1500,
    tollPolicy: 'Included in Base Contract Rate',
    validTill: '2027-03-31',
    status: 'Active (Locked)',
  },
  {
    id: 'RC-902',
    carrierId: 'CRR-001',
    carrierName: 'VRL Logistics Limited',
    contractCode: 'VRL-MSA-2025-01',
    lane: 'Pune (Chakan) → Pantnagar Hub',
    originCity: 'Pune Chakan',
    destinationCity: 'Pantnagar Hub',
    distanceKm: 1480,
    vehicleType: '32ft Multi-Axle MX (18 MT)',
    baseRate: 51200,
    rateType: 'Per Trip Fixed',
    fscFormula: 'Base Diesel ₹90/L + 1% per ₹1.50 rise',
    freeDetentionHours: 4,
    detentionRatePerDay: 1500,
    tollPolicy: 'Included in Base Contract Rate',
    validTill: '2027-03-31',
    status: 'Active (Locked)',
  },
  {
    id: 'RC-903',
    carrierId: 'CRR-002',
    carrierName: 'TCI Freight Supply Chain',
    contractCode: 'TCI-MSA-2025-02',
    lane: 'Jamshedpur Plant → Mumbai (JNPT Port)',
    originCity: 'Jamshedpur',
    destinationCity: 'Mumbai JNPT Port',
    distanceKm: 1690,
    vehicleType: '40ft High-Cube Trailer (28 MT)',
    baseRate: 63500,
    rateType: 'Per Trip Fixed',
    fscFormula: 'Base Diesel ₹90/L + 1.2% per ₹1.50 rise',
    freeDetentionHours: 6,
    detentionRatePerDay: 2000,
    tollPolicy: 'Included in Base Contract Rate',
    validTill: '2027-05-31',
    status: 'Active (Locked)',
  },
  {
    id: 'RC-904',
    carrierId: 'CRR-002',
    carrierName: 'TCI Freight Supply Chain',
    contractCode: 'TCI-MSA-2025-02',
    lane: 'Delhi NCR → Kolkata (Dankuni)',
    originCity: 'Delhi NCR',
    destinationCity: 'Kolkata Dankuni',
    distanceKm: 1510,
    vehicleType: '32ft Multi-Axle MX (18 MT)',
    baseRate: 49800,
    rateType: 'Per Trip Fixed',
    fscFormula: 'Base Diesel ₹90/L + 1% per ₹1.50 rise',
    freeDetentionHours: 4,
    detentionRatePerDay: 1500,
    tollPolicy: 'Included in Base Contract Rate',
    validTill: '2027-05-31',
    status: 'Active (Locked)',
  },
  {
    id: 'RC-905',
    carrierId: 'CRR-003',
    carrierName: 'Safexpress Logistics',
    contractCode: 'SAF-MSA-2025-03',
    lane: 'Bangalore (Nelamangala) → Chennai (Sriperumbudur)',
    originCity: 'Bangalore Nelamangala',
    destinationCity: 'Chennai Sriperumbudur',
    distanceKm: 345,
    vehicleType: '24ft Container Truck (9 MT)',
    baseRate: 26800,
    rateType: 'Per Trip Fixed',
    fscFormula: 'Base Diesel ₹90/L + 0.8% per ₹1.50 rise',
    freeDetentionHours: 3,
    detentionRatePerDay: 1200,
    tollPolicy: 'Included in Base Contract Rate',
    validTill: '2026-12-31',
    status: 'Active (Locked)',
  },
  {
    id: 'RC-906',
    carrierId: 'CRR-004',
    carrierName: 'Delhivery Full-Truckload (FTL)',
    contractCode: 'DEL-MSA-2025-04',
    lane: 'Ahmedabad (Sanand) → Delhi NCR (Farukhnagar)',
    originCity: 'Ahmedabad Sanand',
    destinationCity: 'Delhi NCR Farukhnagar',
    distanceKm: 920,
    vehicleType: '32ft Multi-Axle MX (18 MT)',
    baseRate: 37200,
    rateType: 'Per Trip Fixed',
    fscFormula: 'Dynamic Dynamic Fuel Index',
    freeDetentionHours: 4,
    detentionRatePerDay: 1500,
    tollPolicy: 'FastTag Electronic Reimbursable',
    validTill: '2027-07-31',
    status: 'Active (Locked)',
  },
  {
    id: 'RC-907',
    carrierId: 'CRR-005',
    carrierName: 'CJ Darcl Logistics Limited',
    contractCode: 'CJD-MSA-2025-05',
    lane: 'Kanchipuram → Delhi NCR',
    originCity: 'Kanchipuram',
    destinationCity: 'Delhi NCR',
    distanceKm: 2180,
    vehicleType: '32ft Reefer (+2°C to +8°C Active)',
    baseRate: 82000,
    rateType: 'Per Trip Fixed',
    fscFormula: '15% Active Cold Chain FSC',
    freeDetentionHours: 4,
    detentionRatePerDay: 2500,
    tollPolicy: 'Included in Base Contract Rate',
    validTill: '2027-02-28',
    status: 'Active (Locked)',
  },
];

// ── 4. Transporter Contracts & MSAs ──
export const contractsList = [
  {
    id: 'CTR-101',
    contractNumber: 'MSA-VRL-2025-99',
    carrierId: 'CRR-001',
    carrierName: 'VRL Logistics Limited',
    title: 'Pan-India Surface Full-Truckload Master Transportation Agreement',
    signatoryName: 'Anand Sankeshwar (Managing Director)',
    effectiveDate: '2025-04-01',
    expirationDate: '2027-03-31',
    placementSlaHours: 4,
    placementSlaPct: 98.0,
    penaltyClause: '₹2,000 per 4 hours delay in placement; 0.5% per hour transit SLA delay',
    cargoInsuranceCover: '₹ 1.00 Crore per Trip (Comprehensive Marine Transit Policy)',
    status: 'Active (Signed)',
    renewalAlert: 'Healthy (368 Days Remaining)',
    documentUrl: 'https://docs.enterprise-logistics.io/contracts/MSA-VRL-2025-99.pdf',
  },
  {
    id: 'CTR-102',
    contractNumber: 'MSA-TCI-2025-104',
    carrierId: 'CRR-002',
    carrierName: 'TCI Freight Supply Chain',
    title: 'Heavy-Haul & Steel Ingot Linehaul Service Agreement',
    signatoryName: 'Vineet Agarwal (Managing Director)',
    effectiveDate: '2025-06-01',
    expirationDate: '2027-05-31',
    placementSlaHours: 6,
    placementSlaPct: 97.5,
    penaltyClause: '₹2,500 per placement breach; Full recovery for transit pilferage',
    cargoInsuranceCover: '₹ 2.50 Crore per Trailer (Heavy Engineering Endorsement)',
    status: 'Active (Signed)',
    renewalAlert: 'Healthy (429 Days Remaining)',
    documentUrl: 'https://docs.enterprise-logistics.io/contracts/MSA-TCI-2025-104.pdf',
  },
  {
    id: 'CTR-103',
    contractNumber: 'MSA-SAF-2025-112',
    carrierId: 'CRR-003',
    carrierName: 'Safexpress Logistics',
    title: 'Express Consumer Goods & Hub-to-Hub Dedicated Feeder Contract',
    signatoryName: 'Pawan Jain (Chairman & MD)',
    effectiveDate: '2025-01-01',
    expirationDate: '2026-12-31',
    placementSlaHours: 2,
    placementSlaPct: 99.0,
    penaltyClause: '₹3,000 per delayed feeder placement; 100% damage replacement SLA',
    cargoInsuranceCover: '₹ 75.00 Lakhs per Vehicle',
    status: 'Active (Signed)',
    renewalAlert: 'Expiring in 94 Days (Renewal Scheduled)',
    documentUrl: 'https://docs.enterprise-logistics.io/contracts/MSA-SAF-2025-112.pdf',
  },
  {
    id: 'CTR-104',
    contractNumber: 'MSA-GAT-2024-88',
    carrierId: 'CRR-006',
    carrierName: 'Gati KWE Surface Express',
    title: 'South-Central Regional Parcel & Feeder Distribution Agreement',
    signatoryName: 'Pirojshaw Sarkari (CEO)',
    effectiveDate: '2024-10-01',
    expirationDate: '2026-09-30',
    placementSlaHours: 6,
    placementSlaPct: 95.0,
    penaltyClause: '₹1,500 per delay day; 10% freight deduction on SLA breach',
    cargoInsuranceCover: '₹ 50.00 Lakhs per Vehicle',
    status: 'Renewal Pending (In Legal Review)',
    renewalAlert: 'Expiring in 2 Days (Urgent Action Required)',
    documentUrl: 'https://docs.enterprise-logistics.io/contracts/MSA-GAT-2024-88.pdf',
  },
];

// ── 5. Transporter Self-Service Portal Mock Data ──
export const carrierPortalSessions = {
  'CRR-001': {
    carrierId: 'CRR-001',
    carrierName: 'VRL Logistics Limited',
    tier: 'Tier 1 Preferred Carrier',
    availableLoads: [
      {
        id: 'RFQ-8810',
        origin: 'Pune (Chakan Auto Hub)',
        destination: 'Pantnagar Assembly Plant',
        cargo: 'Automotive Engine Blocks (18 MT)',
        requiredVehicle: '32ft Multi-Axle MX',
        targetRate: 51200,
        bidsCount: 2,
        placementDeadline: 'Today, 18:00 IST',
        status: 'Open for Bidding',
      },
      {
        id: 'RFQ-8814',
        origin: 'Mumbai (JNPT Port)',
        destination: 'Nagpur Multi-Modal Logistics Park',
        cargo: 'Imported Containerized Spares (16 MT)',
        requiredVehicle: '32ft Multi-Axle MX',
        targetRate: 38500,
        bidsCount: 1,
        placementDeadline: 'Tomorrow, 08:00 IST',
        status: 'Open for Bidding',
      },
    ],
    activeDispatches: [
      {
        id: 'TRP-9901',
        shipmentId: 'SHP-88092',
        route: 'Pune → Pantnagar (NH-48)',
        vehicleNumber: 'KA-25-D-8891 (32ft MX)',
        driverName: 'Rajesh Sharma',
        driverPhone: '+91 98201 22334',
        status: 'In Transit (Passing Jaipur)',
        progressPct: 74,
        eta: 'Tomorrow, 14:00 IST',
        gpsTracking: 'Active (VRL Telematics GPS)',
      },
      {
        id: 'TRP-9908',
        shipmentId: 'SHP-88096',
        route: 'Hubballi → Mumbai Bhiwandi',
        vehicleNumber: 'KA-25-C-4420 (32ft MX)',
        driverName: 'Basavaraj Patil',
        driverPhone: '+91 98450 11982',
        status: 'Approaching Delivery Hub',
        progressPct: 92,
        eta: 'Today, 22:30 IST',
        gpsTracking: 'Active (VRL Telematics GPS)',
      },
    ],
    submittedEpods: [
      {
        id: 'EPOD-4412',
        shipmentId: 'SHP-88040',
        orderId: 'ORD-5192',
        consignee: 'Tata Motors Pantnagar',
        deliveredDate: '2026-09-27',
        status: 'Verified (Freight Audit Cleared)',
        invoiceNumber: 'INV-VRL-2026-901',
        amount: 51200,
      },
      {
        id: 'EPOD-4415',
        shipmentId: 'SHP-88055',
        orderId: 'ORD-5201',
        consignee: 'Reliance Retail Nelamangala',
        deliveredDate: '2026-09-28',
        status: 'Under OCR Validation',
        invoiceNumber: 'INV-VRL-2026-904',
        amount: 28400,
      },
    ],
    payoutLedger: [
      {
        id: 'PAY-8821',
        utrNumber: 'HDFCR5202609259901',
        date: '2026-09-25',
        grossFreight: 485000,
        tdsDeduction: 9700,
        netDisbursed: 475300,
        status: 'Disbursed to Bank',
      },
      {
        id: 'PAY-8819',
        utrNumber: 'HDFCR5202609184412',
        date: '2026-09-18',
        grossFreight: 520000,
        tdsDeduction: 10400,
        netDisbursed: 509600,
        status: 'Disbursed to Bank',
      },
    ],
    registeredDriversAndVehicles: [
      {
        type: 'Vehicle',
        identifier: 'KA-25-D-8891',
        category: '32ft Multi-Axle MX (18 MT)',
        vahanStatus: 'Active & Verified',
        fitnessExpiry: '2027-06-30',
        insuranceExpiry: '2027-04-15',
      },
      {
        type: 'Driver',
        identifier: 'Rajesh Sharma (DL-KA-0920194)',
        category: 'Heavy Commercial Vehicle (HCV)',
        sarathiStatus: 'Verified (Clean Record)',
        phone: '+91 98201 22334',
        experienceYears: 12,
      },
    ],
  },
};
