/**
 * LOGISTICSHUB — MOCK DATA: Control Tower
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 3 (Control Tower)
 */

export const controlTowerStats = {
  totalTracked: 245,
  onTime: 189,
  atRisk: 34,
  delayed: 22,
  criticalIncidents: 5,
  avgSpeed: '64 km/h',
  geofenceEvents: 14,
};

export const trackedVehicles = [
  {
    id: 'VEH-0045',
    vehicleNumber: 'MH-12-AB-1234',
    type: 'Truck (Heavy)',
    carrier: 'Express Logistics',
    driverName: 'Ramesh Kumar',
    driverPhone: '+91 98765 43210',
    driverRating: 4.8,
    status: 'on-time', // on-time, at-risk, delayed
    speed: 68,
    fuel: 74,
    temp: '+4.2°C',
    battery: '13.8V',
    lat: 19.0760, // Mumbai coordinates
    lng: 72.8777,
    origin: 'Mumbai Central WH',
    destination: 'Pune Distribution Hub',
    eta: '28-Sep 14:00',
    delayMinutes: 0,
    shipmentId: 'SHP-100245',
    cargo: 'Pharmaceutical Cold Chain',
  },
  {
    id: 'VEH-0089',
    vehicleNumber: 'MH-14-CD-5678',
    type: 'Van (Medium)',
    carrier: 'BlueDart Logistics',
    driverName: 'Suresh Sharma',
    driverPhone: '+91 98765 12345',
    driverRating: 4.6,
    status: 'at-risk',
    speed: 42,
    fuel: 52,
    temp: '+6.1°C',
    battery: '12.4V',
    lat: 18.5204, // Pune
    lng: 73.8567,
    origin: 'Pune WH',
    destination: 'Bangalore Hub',
    eta: '28-Sep 19:15',
    delayMinutes: 25,
    shipmentId: 'SHP-100246',
    cargo: 'Consumer Electronics',
  },
  {
    id: 'VEH-0102',
    vehicleNumber: 'DL-08-EF-9012',
    type: 'Trailer (Heavy)',
    carrier: 'Spot Carrier Services',
    driverName: 'Anil Patel',
    driverPhone: '+91 98111 22334',
    driverRating: 4.2,
    status: 'delayed',
    speed: 0, // Breakdown stationary
    fuel: 18,
    temp: '+12.5°C', // Temp breach
    battery: '11.2V',
    lat: 28.7041, // Delhi
    lng: 77.1025,
    origin: 'Delhi North Gate',
    destination: 'Jaipur Logistics Park',
    eta: '29-Sep 11:30',
    delayMinutes: 110,
    shipmentId: 'SHP-100247',
    cargo: 'Perishable Dairy Foods',
  },
  {
    id: 'VEH-0155',
    vehicleNumber: 'KA-05-GH-3456',
    type: 'Truck (Heavy)',
    carrier: 'Express Logistics',
    driverName: 'Vijay Singh',
    driverPhone: '+91 98450 99887',
    driverRating: 4.9,
    status: 'on-time',
    speed: 72,
    fuel: 85,
    temp: '+3.8°C',
    battery: '14.1V',
    lat: 12.9716, // Bangalore
    lng: 77.5946,
    origin: 'Bangalore Port Yard',
    destination: 'Hyderabad Hub',
    eta: '28-Sep 21:00',
    delayMinutes: 0,
    shipmentId: 'SHP-100248',
    cargo: 'Automotive Components',
  },
  {
    id: 'VEH-0198',
    vehicleNumber: 'GJ-01-IJ-7890',
    type: 'Van (Light)',
    carrier: 'QuickTrans India',
    driverName: 'Manoj Verma',
    driverPhone: '+91 98250 11223',
    driverRating: 4.7,
    status: 'on-time',
    speed: 55,
    fuel: 64,
    temp: '+5.0°C',
    battery: '13.5V',
    lat: 21.1702, // Surat
    lng: 72.8311,
    origin: 'Surat Textile Hub',
    destination: 'Mumbai Nhava Sheva',
    eta: '28-Sep 16:30',
    delayMinutes: 0,
    shipmentId: 'SHP-100249',
    cargo: 'Apparel & Textiles',
  },
  {
    id: 'VEH-0210',
    vehicleNumber: 'TN-10-KL-2345',
    type: 'Truck (Heavy)',
    carrier: 'Southern Freight Corp',
    driverName: 'Deepak Tiwari',
    driverPhone: '+91 98400 44556',
    driverRating: 4.1,
    status: 'delayed',
    speed: 28,
    fuel: 35,
    temp: '+8.4°C',
    battery: '12.8V',
    lat: 13.0827, // Chennai
    lng: 80.2707,
    origin: 'Chennai Port Terminal',
    destination: 'Coimbatore Hub',
    eta: '29-Sep 08:30',
    delayMinutes: 95,
    shipmentId: 'SHP-100250',
    cargo: 'Heavy Industrial Machinery',
  },
  {
    id: 'VEH-0244',
    vehicleNumber: 'RJ-14-MN-6789',
    type: 'Trailer (Heavy)',
    carrier: 'Rajputana Logistics',
    driverName: 'Arvind Yadav',
    driverPhone: '+91 98290 77665',
    driverRating: 4.5,
    status: 'at-risk',
    speed: 50,
    fuel: 48,
    temp: '+4.5°C',
    battery: '13.2V',
    lat: 26.9124, // Jaipur
    lng: 75.7873,
    origin: 'Jaipur Industrial Area',
    destination: 'Ahmedabad Facility',
    eta: '28-Sep 18:00',
    delayMinutes: 30,
    shipmentId: 'SHP-100251',
    cargo: 'FMCG Goods',
  }
];

export const activeExceptions = [
  {
    id: 'EXC-9012',
    severity: 'critical', // critical, high, medium, low
    type: 'Vehicle Breakdown',
    title: 'Engine Failure — VEH-0102',
    description: 'Vehicle DL-08-EF-9012 reported transmission lock on NH-48 (Delhi-Jaipur highway). Cargo temp rising.',
    vehicleId: 'VEH-0102',
    shipmentId: 'SHP-100247',
    timestamp: '8 mins ago',
    location: 'NH-48 Km 114, Rajasthan border',
    assignedTo: 'Unassigned',
    status: 'Investigating',
  },
  {
    id: 'EXC-9013',
    severity: 'critical',
    type: 'Temperature Breach',
    title: 'Cold Chain Temp Alert (+12.5°C)',
    description: 'Reefer unit temperature exceeded safe threshold (+4°C max) for over 15 minutes.',
    vehicleId: 'VEH-0102',
    shipmentId: 'SHP-100247',
    timestamp: '14 mins ago',
    location: 'NH-48 Km 114',
    assignedTo: 'Quality Assurance Team',
    status: 'Action Required',
  },
  {
    id: 'EXC-9014',
    severity: 'high',
    type: 'Route Deviation',
    title: 'Unplanned Route Exit — VEH-0210',
    description: 'Vehicle TN-10-KL-2345 deviated 12km from designated corridor near Vellore.',
    vehicleId: 'VEH-0210',
    shipmentId: 'SHP-100250',
    timestamp: '22 mins ago',
    location: 'Vellore Bypass Road',
    assignedTo: 'Security Ops',
    status: 'Investigating',
  },
  {
    id: 'EXC-9015',
    severity: 'high',
    type: 'Traffic Congestion Delay',
    title: 'Heavy Traffic (+25m) — VEH-0089',
    description: 'Accident on Express Highway near Lonavala causing 4km bottleneck tailback.',
    vehicleId: 'VEH-0089',
    shipmentId: 'SHP-100246',
    timestamp: '35 mins ago',
    location: 'Mumbai-Pune Expressway',
    assignedTo: 'Dispatch Team',
    status: 'Monitoring',
  },
  {
    id: 'EXC-9016',
    severity: 'medium',
    type: 'Geofence Exit Delay',
    title: 'Unscheduled Stop > 30m — VEH-0244',
    description: 'Vehicle stopped at fuel station plaza exceeding 15m allowed dwell time.',
    vehicleId: 'VEH-0244',
    shipmentId: 'SHP-100251',
    timestamp: '42 mins ago',
    location: 'Kishangarh Toll Plaza',
    assignedTo: 'Driver Ops Manager',
    status: 'Pending',
  },
];

export const geofences = [
  { id: 'GEO-01', name: 'Mumbai Central WH', type: 'Warehouse', activeVehiclesCount: 18, lat: 19.0760, lng: 72.8777, radiusKm: 15 },
  { id: 'GEO-02', name: 'Delhi North Gate Facility', type: 'Hub', activeVehiclesCount: 24, lat: 28.7041, lng: 77.1025, radiusKm: 20 },
  { id: 'GEO-03', name: 'Bangalore Port Yard', type: 'Port', activeVehiclesCount: 14, lat: 12.9716, lng: 77.5946, radiusKm: 12 },
  { id: 'GEO-04', name: 'Pune Distribution Center', type: 'Distribution', activeVehiclesCount: 12, lat: 18.5204, lng: 73.8567, radiusKm: 10 },
  { id: 'GEO-05', name: 'Chennai Sea Terminal', type: 'Port', activeVehiclesCount: 9, lat: 13.0827, lng: 80.2707, radiusKm: 18 },
];
