/**
 * LOGISTICSHUB — MOCK DATA: Real-Time Dispatch & Trip Management
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 10 (Dispatch & Trip Management)
 */

export const fleetVehicles = [
  {
    id: 'VEH-3042',
    registration: 'MH-12-AB-3042',
    type: '20ft Box Truck',
    driver: 'John Smith',
    status: 'Ready',
    capacityKg: 5000,
    capacityCbm: 20,
    lastLocation: 'West Logistics Hub (Depot #1)',
    etaToDispatch: 'Immediate (0m)',
    certifications: ['Hazmat Class 3', 'Tail-Lift'],
    fuelPct: 88,
  },
  {
    id: 'VEH-8190',
    registration: 'MH-14-CD-8190',
    type: '32ft Multi-Axle Trailer',
    driver: 'Elena Rostova',
    status: 'On Trip',
    capacityKg: 12000,
    capacityCbm: 48,
    lastLocation: 'Highway NH-48 Mile 42',
    etaToDispatch: 'In Transit (ETA 16:30)',
    certifications: ['Heavy Payload', 'ODC Certified'],
    fuelPct: 74,
  },
  {
    id: 'VEH-1024',
    registration: 'GJ-01-EF-1024',
    type: 'Sprinter Courier Van',
    driver: 'Marcus Brody',
    status: 'Ready',
    capacityKg: 2200,
    capacityCbm: 12,
    lastLocation: 'City North Gateway Gate 2',
    etaToDispatch: 'Immediate (5m)',
    certifications: ['Urban EV', 'Rapid Express'],
    fuelPct: 92,
  },
  {
    id: 'VEH-5091',
    registration: 'DL-01-GH-5091',
    type: '24ft Container Truck',
    driver: 'David Kim',
    status: 'On Break',
    capacityKg: 7500,
    capacityCbm: 30,
    lastLocation: 'Plaza Rest Area Sector 4',
    etaToDispatch: '35m (Rest Break)',
    certifications: ['Refrigerated Cold Chain'],
    fuelPct: 65,
  },
  {
    id: 'VEH-7723',
    registration: 'KA-04-IJ-7723',
    type: '32ft Multi-Axle Trailer',
    driver: 'Rachel Green',
    status: 'Ready',
    capacityKg: 12000,
    capacityCbm: 48,
    lastLocation: 'South Metro Cross-Dock',
    etaToDispatch: 'Immediate (0m)',
    certifications: ['Heavy Steel Cargo'],
    fuelPct: 82,
  },
  {
    id: 'VEH-2291',
    registration: 'TN-09-KL-2291',
    type: 'Medium Freight Van',
    driver: 'Sam Taylor',
    status: 'Off-Duty',
    capacityKg: 3500,
    capacityCbm: 16,
    lastLocation: 'Depot Maintenance Bay',
    etaToDispatch: 'Tomorrow 06:00',
    certifications: ['Liftgate'],
    fuelPct: 50,
  },
];

export const fleetDrivers = [
  { id: 'DRV-101', name: 'John Smith', licenseValid: true, status: 'On Duty', assignedVehicle: 'VEH-3042', hoursLeft: '8.5h', rating: 4.9, certs: ['Hazmat', 'Multi-Drop'] },
  { id: 'DRV-102', name: 'Elena Rostova', licenseValid: true, status: 'On Trip', assignedVehicle: 'VEH-8190', hoursLeft: '6.0h', rating: 4.95, certs: ['Reefer Master', 'ODC'] },
  { id: 'DRV-103', name: 'Marcus Brody', licenseValid: true, status: 'Available', assignedVehicle: 'VEH-1024', hoursLeft: '10.0h', rating: 4.85, certs: ['Urban Fast', 'EV Tech'] },
  { id: 'DRV-104', name: 'David Kim', licenseValid: true, status: 'On Break', assignedVehicle: 'VEH-5091', hoursLeft: '7.0h', rating: 4.88, certs: ['Cold Chain GDP'] },
  { id: 'DRV-105', name: 'Rachel Green', licenseValid: true, status: 'Available', assignedVehicle: 'VEH-7723', hoursLeft: '9.0h', rating: 4.92, certs: ['Heavy Haul'] },
  { id: 'DRV-106', name: 'Sam Taylor', licenseValid: true, status: 'Off Duty', assignedVehicle: 'Unassigned', hoursLeft: '0.0h', rating: 4.8, certs: ['Standard'] },
];

export const waitingTripsQueue = [
  {
    id: 'TRIP-901',
    shipmentsCount: 3,
    shipmentIds: ['SHP-100280', 'SHP-100281', 'SHP-100282'],
    weightKg: 2450,
    volumeCbm: 11.2,
    stops: 4,
    origin: 'Central Hub Depot #1',
    destination: 'Metro North Corridor',
    serviceType: 'Delivery & Pickup',
    urgency: 'High',
    estDuration: '5h 30m',
    estCost: 210,
    revenue: 320,
    profitMargin: 110,
    distanceKm: 185,
    specialRequirements: ['Hazmat Class 3 Segregation'],
  },
  {
    id: 'TRIP-902',
    shipmentsCount: 2,
    shipmentIds: ['SHP-100283', 'SHP-100284'],
    weightKg: 1200,
    volumeCbm: 5.8,
    stops: 3,
    origin: 'City Express Gateway',
    destination: 'Downtown Retail Zone',
    serviceType: 'Express Delivery',
    urgency: 'Urgent',
    estDuration: '3h 15m',
    estCost: 140,
    revenue: 230,
    profitMargin: 90,
    distanceKm: 92,
    specialRequirements: ['Liftgate Required'],
  },
  {
    id: 'TRIP-903',
    shipmentsCount: 5,
    shipmentIds: ['SHP-100285', 'SHP-100286', 'SHP-100287', 'SHP-100288'],
    weightKg: 6800,
    volumeCbm: 26.0,
    stops: 6,
    origin: 'South Marine Terminal',
    destination: 'Eastern Industrial Sector',
    serviceType: 'Multi-Drop FTL',
    urgency: 'Medium',
    estDuration: '7h 45m',
    estCost: 380,
    revenue: 560,
    profitMargin: 180,
    distanceKm: 290,
    specialRequirements: ['Heavy Multi-Axle'],
  },
  {
    id: 'TRIP-904',
    shipmentsCount: 1,
    shipmentIds: ['SHP-100289'],
    weightKg: 950,
    volumeCbm: 4.2,
    stops: 2,
    origin: 'West Hub Pharma Bay',
    destination: 'Healthcare District Central',
    serviceType: 'Cold Chain Courier',
    urgency: 'Urgent',
    estDuration: '2h 45m',
    estCost: 165,
    revenue: 280,
    profitMargin: 115,
    distanceKm: 75,
    specialRequirements: ['+4°C Temperature Validated'],
  },
  {
    id: 'TRIP-905',
    shipmentsCount: 4,
    shipmentIds: ['SHP-100290', 'SHP-100291', 'SHP-100292'],
    weightKg: 3400,
    volumeCbm: 14.5,
    stops: 5,
    origin: 'Central Hub Depot #1',
    destination: 'West Airport Cargo Sector',
    serviceType: 'Standard Distribution',
    urgency: 'Medium',
    estDuration: '6h 00m',
    estCost: 240,
    revenue: 360,
    profitMargin: 120,
    distanceKm: 210,
    specialRequirements: ['Standard Pallets'],
  },
];

export const initialGanttSchedule = [
  {
    vehicleId: 'VEH-3042',
    registration: 'MH-12-AB-3042',
    driver: 'John Smith',
    vehicleType: '20ft Box Truck',
    blocks: [
      { id: 'b1', type: 'check', title: 'Pre-Trip Inspection & Loading', startHour: 6.0, durationHours: 1.5, startStr: '06:00', endStr: '07:30', tripId: null, color: '#0284c7' },
      { id: 'b2', type: 'trip', title: 'TRIP-870: Metro Gateway Multi-Drop', startHour: 7.5, durationHours: 4.5, startStr: '07:30', endStr: '12:00', tripId: 'TRIP-870', stops: 4, weight: '3,200 kg', color: '#10b981' },
      { id: 'b3', type: 'break', title: 'Mandatory Driver Meal Break', startHour: 12.0, durationHours: 1.0, startStr: '12:00', endStr: '13:00', tripId: null, color: '#f59e0b' },
      { id: 'b4', type: 'trip', title: 'TRIP-874: East Harbor Return Run', startHour: 13.0, durationHours: 4.0, startStr: '13:00', endStr: '17:00', tripId: 'TRIP-874', stops: 3, weight: '2,100 kg', color: '#10b981' },
      { id: 'b5', type: 'return', title: 'Depot Yard Return & Post-Trip', startHour: 17.0, durationHours: 1.0, startStr: '17:00', endStr: '18:00', tripId: null, color: '#06b6d4' },
    ],
  },
  {
    vehicleId: 'VEH-8190',
    registration: 'MH-14-CD-8190',
    driver: 'Elena Rostova',
    vehicleType: '32ft Multi-Axle',
    blocks: [
      { id: 'b6', type: 'check', title: 'Yard Docking & Heavy Lashing', startHour: 6.5, durationHours: 1.5, startStr: '06:30', endStr: '08:00', tripId: null, color: '#0284c7' },
      { id: 'b7', type: 'trip', title: 'TRIP-865: Highway Trunkline FTL', startHour: 8.0, durationHours: 8.5, startStr: '08:00', endStr: '16:30', tripId: 'TRIP-865', stops: 2, weight: '11,400 kg', color: '#10b981' },
      { id: 'b8', type: 'return', title: 'Depot Cross-Dock Arrival', startHour: 16.5, durationHours: 1.5, startStr: '16:30', endStr: '18:00', tripId: null, color: '#06b6d4' },
    ],
  },
  {
    vehicleId: 'VEH-1024',
    registration: 'GJ-01-EF-1024',
    driver: 'Marcus Brody',
    vehicleType: 'Sprinter Courier Van',
    blocks: [
      { id: 'b9', type: 'trip', title: 'TRIP-881: Early Morning Express', startHour: 6.0, durationHours: 3.5, startStr: '06:00', endStr: '09:30', tripId: 'TRIP-881', stops: 5, weight: '1,100 kg', color: '#10b981' },
      { id: 'b10', type: 'break', title: 'Rest Break & EV Supercharge', startHour: 9.5, durationHours: 1.0, startStr: '09:30', endStr: '10:30', tripId: null, color: '#f59e0b' },
      { id: 'b11', type: 'trip', title: 'TRIP-889: Downtown Rapid Delivery', startHour: 10.5, durationHours: 4.0, startStr: '10:30', endStr: '14:30', tripId: 'TRIP-889', stops: 6, weight: '1,450 kg', color: '#10b981' },
    ],
  },
  {
    vehicleId: 'VEH-5091',
    registration: 'DL-01-GH-5091',
    driver: 'David Kim',
    vehicleType: '24ft Container Truck',
    blocks: [
      { id: 'b12', type: 'trip', title: 'TRIP-872: Pharma Cold Chain Route', startHour: 7.0, durationHours: 5.0, startStr: '07:00', endStr: '12:00', tripId: 'TRIP-872', stops: 3, weight: '4,200 kg', color: '#10b981' },
      { id: 'b13', type: 'break', title: 'Meal Break', startHour: 12.0, durationHours: 1.5, startStr: '12:00', endStr: '13:30', tripId: null, color: '#f59e0b' },
    ],
  },
  {
    vehicleId: 'VEH-7723',
    registration: 'KA-04-IJ-7723',
    driver: 'Rachel Green',
    vehicleType: '32ft Multi-Axle',
    blocks: [
      { id: 'b14', type: 'check', title: 'Pre-Trip Inspection', startHour: 8.0, durationHours: 1.0, startStr: '08:00', endStr: '09:00', tripId: null, color: '#0284c7' },
      { id: 'b15', type: 'trip', title: 'TRIP-890: Southern Industrial Trunk', startHour: 9.0, durationHours: 7.0, startStr: '09:00', endStr: '16:00', tripId: 'TRIP-890', stops: 4, weight: '9,800 kg', color: '#10b981' },
    ],
  },
];

export const activeTripsLifecycle = [
  {
    id: 'TRIP-870',
    vehicle: 'VEH-3042 (MH-12-AB-3042)',
    driver: 'John Smith',
    origin: 'Mumbai Hub Depot #1',
    destination: 'Pune MIDC Sector 4',
    currentStage: 'In Transit', // Created | Assigned | Accepted | Pickup | Loading | In Transit | Out for Delivery | Delivered
    stageIndex: 6,
    eta: 'Today 12:00',
    delayMinutes: 0,
    stopsTotal: 4,
    stopsCompleted: 2,
    weightKg: 3200,
    volumeCbm: 14.5,
    shipments: ['SHP-100234', 'SHP-100235'],
    epodSigned: false,
    sealNumber: 'SEAL-98741-A',
    tempC: '+4.2°C (Compliant)',
  },
  {
    id: 'TRIP-865',
    vehicle: 'VEH-8190 (MH-14-CD-8190)',
    driver: 'Elena Rostova',
    origin: 'Delhi Gate North',
    destination: 'Jaipur Industrial Park',
    currentStage: 'In Transit',
    stageIndex: 6,
    eta: 'Today 16:30',
    delayMinutes: 12,
    stopsTotal: 2,
    stopsCompleted: 1,
    weightKg: 11400,
    volumeCbm: 44.0,
    shipments: ['SHP-100210'],
    epodSigned: false,
    sealNumber: 'SEAL-55210-B',
    tempC: 'Ambient',
  },
  {
    id: 'TRIP-881',
    vehicle: 'VEH-1024 (GJ-01-EF-1024)',
    driver: 'Marcus Brody',
    origin: 'Ahmedabad SEZ',
    destination: 'Vadodara City Center',
    currentStage: 'Out for Delivery',
    stageIndex: 7,
    eta: 'Today 09:30',
    delayMinutes: 0,
    stopsTotal: 5,
    stopsCompleted: 4,
    weightKg: 1100,
    volumeCbm: 6.0,
    shipments: ['SHP-100241', 'SHP-100242'],
    epodSigned: true,
    sealNumber: 'SEAL-11029-C',
    tempC: 'Ambient',
  },
  {
    id: 'TRIP-872',
    vehicle: 'VEH-5091 (DL-01-GH-5091)',
    driver: 'David Kim',
    origin: 'Hyderabad MedTech Gateway',
    destination: 'Nagpur Central Hub',
    currentStage: 'In Transit',
    stageIndex: 6,
    eta: 'Today 12:00',
    delayMinutes: 0,
    stopsTotal: 3,
    stopsCompleted: 1,
    weightKg: 4200,
    volumeCbm: 18.0,
    shipments: ['SHP-100255'],
    epodSigned: false,
    sealNumber: 'SEAL-77412-D',
    tempC: '+3.8°C (Cold Chain Pass)',
  },
];
