/**
 * LOGISTICSHUB — MOCK DATA: Exceptions & Risk Management
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 14 (Exceptions & Risk Management)
 */

export const exceptionDashboardStats = {
  totalExceptions: 127,
  criticalCount: 4,
  highCount: 14,
  mediumCount: 31,
  lowCount: 78,
  financialExposure: '$425,000',
  resolvedToday: 38,
  avgResolutionTime: '34 mins',
  slaProtectionRate: '96.2%',
};

export const exceptionsQueue = [
  {
    id: 'EXC-2024-001234',
    title: 'Delivery Delay SLA Warning — SHP-100247',
    type: 'Delivery Delay',
    severity: 'critical',
    status: 'Investigating',
    createdTime: 'Today 11:30',
    elapsedTime: '2h 15m',
    dueTime: '1h 15m remaining',
    isOverdue: false,
    shipmentId: 'SHP-100247',
    orderId: 'ORD-90815',
    customer: 'Reliance Retail Supply',
    carrier: 'Safexpress Logistics',
    vehicleId: 'VEH-8190',
    driverName: 'Elena Rostova',
    driverPhone: '+1 (555) 345-6789',
    origin: 'Mumbai Nhava Sheva Port',
    destination: 'Ahmedabad S.G. Highway',
    location: 'Surat Bypass Highway Toll Plaza (NH-48)',
    estimatedImpact: '+1h 45m delay ($2,400 SLA penalty risk)',
    rootCause: 'Heavy monsoon waterlogging and multi-vehicle toll gate bottleneck on NH-48 corridor.',
    assignee: { name: 'Rajesh Kumar', avatar: 'RK' },
    cargoSummary: {
      itemsCount: 12,
      weightKg: 4500,
      cargoValue: '$84,000',
      serviceLevel: 'Standard Heavy Ground',
    },
    historyLog: [
      { time: '11:30', user: 'AI Telematics Monitor', action: 'Incident detected: Speed dropped below 20 km/h for >40m' },
      { time: '11:45', user: 'Rajesh Kumar', action: 'Claimed incident & contacted driver Elena Rostova' },
      { time: '12:05', user: 'Rajesh Kumar', action: 'Requested GIS alternative detour via State Ring Road' },
    ],
  },
  {
    id: 'EXC-2024-001235',
    title: 'Cold Chain Temperature Spike (+12.5°C) — SHP-100250',
    type: 'Temperature Breach',
    severity: 'critical',
    status: 'Action Required',
    createdTime: 'Today 12:15',
    elapsedTime: '45 mins',
    dueTime: '30 mins remaining',
    isOverdue: false,
    shipmentId: 'SHP-100250',
    orderId: 'ORD-90820',
    customer: 'Apollo Hospitals Pharma Hub',
    carrier: 'Express Freight Corp',
    vehicleId: 'VEH-5091',
    driverName: 'David Kim',
    driverPhone: '+1 (555) 567-8901',
    origin: 'Hyderabad MedTech Park',
    destination: 'Nagpur Central Hub',
    location: 'Adilabad Express Highway Mile 18',
    estimatedImpact: 'Risk of vaccine cargo degradation ($120,000 product value)',
    rootCause: 'Auxiliary compressor belt slippage causing temperature climb from +3.8°C to +12.5°C.',
    assignee: { name: 'Priya Sharma (QA)', avatar: 'PS' },
    cargoSummary: {
      itemsCount: 4,
      weightKg: 620,
      cargoValue: '$120,000',
      serviceLevel: 'Critical Cold Chain (+2°C to +8°C)',
    },
    historyLog: [
      { time: '12:15', user: 'IoT Temp Telemetry', action: 'Reefer threshold alert: +12.5°C detected' },
      { time: '12:20', user: 'Priya Sharma', action: 'Alerted driver & dispatched mobile backup reefer' },
    ],
  },
  {
    id: 'EXC-2024-001236',
    title: 'Vehicle Transmission Failure Breakdown — VEH-0102',
    type: 'Vehicle Breakdown',
    severity: 'high',
    status: 'Investigating',
    createdTime: 'Today 10:00',
    elapsedTime: '3h 30m',
    dueTime: 'Overdue (+30m)',
    isOverdue: true,
    shipmentId: 'SHP-100247',
    orderId: 'ORD-90815',
    customer: 'Reliance Retail Supply',
    carrier: 'Spot Carrier Services',
    vehicleId: 'VEH-0102',
    driverName: 'Anil Patel',
    driverPhone: '+91 98111 22334',
    origin: 'Delhi North Gate',
    destination: 'Jaipur Logistics Park',
    location: 'NH-48 Km 114, Rajasthan border',
    estimatedImpact: 'Vehicle stationary on shoulder; tow truck ETA 25 mins',
    rootCause: 'Hydraulic fluid pressure loss in heavy tractor transmission casing.',
    assignee: { name: 'Amit Verma (Fleet)', avatar: 'AV' },
    cargoSummary: {
      itemsCount: 18,
      weightKg: 8200,
      cargoValue: '$45,000',
      serviceLevel: 'Heavy Freight Trailer',
    },
    historyLog: [
      { time: '10:00', user: 'CAN-Bus ECU', action: 'DTC Code P0700 Transmission Lock Error' },
      { time: '10:15', user: 'Amit Verma', action: 'Tow truck & replacement tractor unit dispatched' },
    ],
  },
  {
    id: 'EXC-2024-001237',
    title: 'Unplanned Corridor Exit (>15km) — VEH-0210',
    type: 'Route Deviation',
    severity: 'high',
    status: 'Unassigned',
    createdTime: 'Today 12:40',
    elapsedTime: '20 mins',
    dueTime: '2h 10m remaining',
    isOverdue: false,
    shipmentId: 'SHP-100251',
    orderId: 'ORD-90822',
    customer: 'Samsung Electronics',
    carrier: 'Southern Freight Corp',
    vehicleId: 'VEH-0210',
    driverName: 'Deepak Tiwari',
    driverPhone: '+91 98400 44556',
    origin: 'Chennai Port Terminal',
    destination: 'Coimbatore Hub',
    location: 'Vellore Bypass Rural Road',
    estimatedImpact: '15 km off designated secure corridor (+40m detour)',
    rootCause: 'Driver took unofficial shortcut to bypass highway toll plaza.',
    assignee: null,
    cargoSummary: {
      itemsCount: 8,
      weightKg: 1400,
      cargoValue: '$65,000',
      serviceLevel: 'High-Value Electronics SLA',
    },
    historyLog: [
      { time: '12:40', user: 'Geofence Guard', action: 'Corridor boundary violation alert triggered' },
    ],
  },
  {
    id: 'EXC-2024-001238',
    title: 'GST E-Way Bill Expiring in 90 Minutes — EWAY-991023',
    type: 'Document Expiry',
    severity: 'medium',
    status: 'Investigating',
    createdTime: 'Today 12:00',
    elapsedTime: '1h 00m',
    dueTime: '1h 30m remaining',
    isOverdue: false,
    shipmentId: 'SHP-100249',
    orderId: 'ORD-90818',
    customer: 'Aditya Birla Fashion Hub',
    carrier: 'QuickTrans India',
    vehicleId: 'VEH-0198',
    driverName: 'Manoj Verma',
    driverPhone: '+91 98250 11223',
    origin: 'Surat Textile Hub',
    destination: 'Mumbai Nhava Sheva',
    location: 'Surat SEZ Outbound Checkpost',
    estimatedImpact: 'Commercial tax checkpoint impoundment risk',
    rootCause: 'Delayed departure at origin dock exhausted remaining validity window.',
    assignee: { name: 'Kavita Roy (Compliance)', avatar: 'KR' },
    cargoSummary: {
      itemsCount: 22,
      weightKg: 3100,
      cargoValue: '$32,000',
      serviceLevel: 'Commercial Ground Transport',
    },
    historyLog: [
      { time: '12:00', user: 'Compliance Engine', action: 'Auto-detected validity window < 2 hours' },
    ],
  },
];

export const riskQueueList = [
  {
    id: 'RSK-801',
    title: 'SHP-100245 at risk of late delivery due to NH-48 bottleneck',
    shipmentId: 'SHP-100245',
    orderId: 'ORD-90812',
    customer: 'ABC Logistics Pvt Ltd',
    customerContact: 'ops@abclogistics.com',
    carrier: 'BlueDart Express Line',
    vehicleId: 'VEH-3042',
    driverName: 'John Smith',
    driverPhone: '+1 (555) 234-5678',
    origin: 'Delhi Gate North Hub',
    destination: 'Jaipur Industrial Corridor',
    probabilityPct: 82,
    impactHours: 2.5,
    riskScore: 88, // Score 80+ Critical
    riskLevel: 'critical', // critical | high | medium | low
    timeUntilBreach: '1 hour 45 minutes',
    scheduledETA: 'Today 14:00',
    predictedETA: 'Today 16:30',
    currentLocation: 'NH-48 Corridor Mile 84 (45 km remaining)',
    currentSpeed: '42 km/h (Segment avg 65 km/h)',
    probabilityFactors: [
      { name: 'Highway Traffic Congestion Forecast', chance: 78, impact: 'High (+1h 15m delay)' },
      { name: 'Toll Fastag Clearance Queue', chance: 65, impact: 'Medium (+45m delay)' },
      { name: 'Driver Rest & Dwell Window', chance: 15, impact: 'Low (+15m delay)' },
      { name: 'Weather Radar Monsoon Rain', chance: 5, impact: 'Low (0m delay)' },
    ],
    mitigationOptions: [
      {
        id: 'mit-1',
        title: '🗺️ Reroute via State Toll Ring Road',
        newETA: 'Today 14:45 (Saves 1h 45m)',
        cost: '$120 (Toll Variance)',
        successProb: '92%',
        desc: 'Directs driver to exit at Mile 88 to avoid toll plaza bottleneck.',
      },
      {
        id: 'mit-2',
        title: '🚛 Cross-Dock Transfer to Fast Sprinter VEH-1024',
        newETA: 'Today 14:15 (Saves 2h 15m)',
        cost: '$180 (Cross-Dock Transfer)',
        successProb: '88%',
        desc: 'Cross-dock parcels at Gurgaon Hub to dedicated high-speed courier van.',
      },
      {
        id: 'mit-3',
        title: '📲 Contact Consignee for 2-Hour SLA Window Extension',
        newETA: 'Today 16:30 (Penalty Waived)',
        cost: '$0 (Customer Courtesy)',
        successProb: '75%',
        desc: 'Dispatches automated SLA waiver agreement to ABC Logistics receiving dock.',
      },
    ],
    status: 'Monitoring',
    owner: 'Unassigned',
  },
  {
    id: 'RSK-802',
    title: 'SHP-100247 Heavy Container Risk of Port Gate Curfew Breach',
    shipmentId: 'SHP-100247',
    orderId: 'ORD-90815',
    customer: 'Reliance Retail Supply',
    customerContact: 'supplychain@relianceretail.com',
    carrier: 'Safexpress Logistics',
    vehicleId: 'VEH-8190',
    driverName: 'Elena Rostova',
    driverPhone: '+1 (555) 345-6789',
    origin: 'Mumbai Nhava Sheva Port',
    destination: 'Ahmedabad S.G. Highway',
    probabilityPct: 74,
    impactHours: 3.2,
    riskScore: 78, // High (60-79)
    riskLevel: 'high',
    timeUntilBreach: '2 hours 10 minutes',
    scheduledETA: 'Today 17:00',
    predictedETA: 'Today 18:45',
    currentLocation: 'Surat Bypass Highway Toll Plaza',
    currentSpeed: '38 km/h (Monsoon crawl)',
    probabilityFactors: [
      { name: 'Monsoon Flooding Slowdown', chance: 85, impact: 'High (+1h 30m delay)' },
      { name: 'Weight Bridge Inspection Queue', chance: 40, impact: 'Medium (+30m delay)' },
      { name: 'Port Night Entry Curfew (20:00)', chance: 55, impact: 'Critical (+12h Overnight Impound)' },
    ],
    mitigationOptions: [
      {
        id: 'mit-21',
        title: '⚡ Priority Green-Corridor Toll Gate Pass',
        newETA: 'Today 17:40 (Saves 1h 05m)',
        cost: '$85 (Expedited Pass)',
        successProb: '95%',
        desc: 'Activates RFID priority express lane at Surat & Bharuch toll gates.',
      },
      {
        id: 'mit-22',
        title: '🏢 Request Port Terminal Inbound Gate Extension',
        newETA: 'Today 18:45 (No Curfew Lock)',
        cost: '$50 (Late Gate Fee)',
        successProb: '80%',
        desc: 'Notifies Nhava Sheva port terminal supervisor to hold gate open.',
      },
    ],
    status: 'Monitoring',
    owner: 'Rajesh Kumar',
  },
  {
    id: 'RSK-803',
    title: 'SHP-100250 Hospital Vaccine Delivery Temperature Buffer Risk',
    shipmentId: 'SHP-100250',
    orderId: 'ORD-90820',
    customer: 'Apollo Hospitals Pharma Hub',
    customerContact: 'coldchain@apollohospitals.org',
    carrier: 'Express Freight Corp',
    vehicleId: 'VEH-5091',
    driverName: 'David Kim',
    driverPhone: '+1 (555) 567-8901',
    origin: 'Hyderabad MedTech Park',
    destination: 'Nagpur Central Hub',
    probabilityPct: 62,
    impactHours: 1.5,
    riskScore: 65, // High
    riskLevel: 'high',
    timeUntilBreach: '3 hours 00 minutes',
    scheduledETA: 'Today 15:30',
    predictedETA: 'Today 15:45',
    currentLocation: 'Adilabad Express Highway Mile 18',
    currentSpeed: '65 km/h (Normal)',
    probabilityFactors: [
      { name: 'Ambient Heatwave Peak (+38°C)', chance: 90, impact: 'High Reefer Load' },
      { name: 'Reefer Auxiliary Battery Depletion', chance: 35, impact: 'Medium (+30m delay)' },
    ],
    mitigationOptions: [
      {
        id: 'mit-31',
        title: '❄️ Deploy Mobile Generator Auxiliary Plug-in',
        newETA: 'Today 15:30 (Saves Cold Chain)',
        cost: '$140 (Service Fee)',
        successProb: '98%',
        desc: 'Connects secondary backup power at Adilabad service station.',
      },
    ],
    status: 'Monitoring',
    owner: 'Priya Sharma (QA)',
  },
  {
    id: 'RSK-804',
    title: 'SHP-100249 Apparel Consignment Document Clearance Risk',
    shipmentId: 'SHP-100249',
    orderId: 'ORD-90818',
    customer: 'Aditya Birla Fashion Hub',
    customerContact: 'logistics@abfrl.com',
    carrier: 'QuickTrans India',
    vehicleId: 'VEH-0198',
    driverName: 'Manoj Verma',
    driverPhone: '+91 98250 11223',
    origin: 'Surat Textile Hub',
    destination: 'Mumbai Nhava Sheva',
    probabilityPct: 45,
    impactHours: 1.0,
    riskScore: 48, // Medium (40-59)
    riskLevel: 'medium',
    timeUntilBreach: '4 hours 15 minutes',
    scheduledETA: 'Today 16:30',
    predictedETA: 'Today 16:45',
    currentLocation: 'Surat Textile Gate SEZ',
    currentSpeed: '55 km/h',
    probabilityFactors: [
      { name: 'E-Way Bill 2-Hour Expiration Window', chance: 60, impact: 'Medium (+45m)' },
    ],
    mitigationOptions: [
      {
        id: 'mit-41',
        title: '📑 Auto-Renew GST E-Way Bill Online',
        newETA: 'Today 16:30 (0 Delay)',
        cost: '$0 (Auto-Renewed)',
        successProb: '100%',
        desc: 'Triggers instant GST portal API renewal with updated vehicle registration.',
      },
    ],
    status: 'Monitoring',
    owner: 'Kavita Roy',
  },
];
