// ── Facilities, Dock & Yard Management Mock Dataset ──
// Source: Section 15 of COMPLETE_UI_DESIGN_PROMPT.md

export const facilitiesList = [
  {
    id: 'FAC-BHW-01',
    name: 'Mumbai Bhiwandi Central Logistics Hub',
    code: 'BHW-01',
    city: 'Bhiwandi, Mumbai, MH',
    address: 'Survey 44/2, Rahnal Village, Bhiwandi-Wada Road, Thane, MH - 421302',
    totalAreaSqFt: '250,000 sq.ft',
    totalDocks: 6,
    totalYardSlots: 32,
    activeAppointmentsToday: 24,
    operatingHours: '24/7 Continuous Operations',
    manager: 'Arun Deshmukh (+91 98201 99401)',
  },
  {
    id: 'FAC-GGN-02',
    name: 'Delhi NCR Logistics Gateway',
    code: 'GGN-02',
    city: 'Gurugram, HR',
    address: 'Plot 18, Sector 8, IMT Manesar, Gurugram, HR - 122050',
    totalAreaSqFt: '180,000 sq.ft',
    totalDocks: 5,
    totalYardSlots: 24,
    activeAppointmentsToday: 18,
    operatingHours: '06:00 - 23:00 IST',
    manager: 'Rajeev Bhatia (+91 98110 44102)',
  },
  {
    id: 'FAC-BLR-03',
    name: 'Bengaluru Whitefield Fulfillment Center',
    code: 'BLR-03',
    city: 'Bengaluru, KA',
    address: 'Export Promotion Industrial Park, Whitefield, Bengaluru, KA - 560066',
    totalAreaSqFt: '140,000 sq.ft',
    totalDocks: 4,
    totalYardSlots: 18,
    activeAppointmentsToday: 15,
    operatingHours: '07:00 - 22:00 IST',
    manager: 'Kavitha Murthy (+91 98450 77209)',
  },
  {
    id: 'FAC-MAA-04',
    name: 'Chennai Port Container Drayage Hub',
    code: 'MAA-04',
    city: 'Chennai, TN',
    address: 'Ennore Port Express Road, Manali Industrial Corridor, Chennai, TN - 600068',
    totalAreaSqFt: '300,000 sq.ft',
    totalDocks: 8,
    totalYardSlots: 45,
    activeAppointmentsToday: 28,
    operatingHours: '24/7 Port bonded gate',
    manager: 'Senthil Nathan (+91 94440 33812)',
  },
];

export const facilityAppointmentsStats = {
  totalMonthAppointments: 456,
  confirmedScheduled: 284,
  checkedInAtDock: 82,
  completedToday: 76,
  noShowOrCancelled: 14,
  avgTurnaroundDwellMinutes: 44,
  onTimeDockArrivalPct: 96.2,
};

export const appointmentsWeeklySchedule = [
  // Mon
  { id: 'APT-101', day: 'Mon', time: '08:00', duration: '45m', shipmentId: 'SHP-88092', customer: 'Cipla Pharma Ltd', type: 'Pickup', status: 'Completed', dock: 'Dock 1', color: '#2563eb' },
  { id: 'APT-102', day: 'Mon', time: '10:30', duration: '60m', shipmentId: 'SHP-88104', customer: 'Samsung Electronics', type: 'Delivery', status: 'Completed', dock: 'Dock 2', color: '#059669' },
  { id: 'APT-103', day: 'Mon', time: '14:00', duration: '30m', shipmentId: 'SHP-88120', customer: 'Schneider Electric', type: 'Cross-dock', status: 'Completed', dock: 'Dock 3', color: '#d97706' },
  // Tue
  { id: 'APT-104', day: 'Tue', time: '09:00', duration: '45m', shipmentId: 'SHP-88135', customer: 'Tata Motors Spares', type: 'Delivery', status: 'Completed', dock: 'Dock 1', color: '#059669' },
  { id: 'APT-105', day: 'Tue', time: '13:00', duration: '45m', shipmentId: 'SHP-88148', customer: 'Unilever FMCG', type: 'Pickup', status: 'Completed', dock: 'Dock 4', color: '#2563eb' },
  // Wed
  { id: 'APT-106', day: 'Wed', time: '08:00', duration: '60m', shipmentId: 'SHP-88160', customer: 'Reliance Retail', type: 'Delivery', status: 'Completed', dock: 'Dock 2', color: '#059669' },
  { id: 'APT-107', day: 'Wed', time: '11:15', duration: '30m', shipmentId: 'SHP-88172', customer: 'Dr. Reddy Labs', type: 'Pickup', status: 'Completed', dock: 'Reefer Bay', color: '#2563eb' },
  { id: 'APT-108', day: 'Wed', time: '15:30', duration: '45m', shipmentId: 'SHP-88188', customer: 'ABB India Ltd', type: 'Cross-dock', status: 'Completed', dock: 'Dock 3', color: '#d97706' },
  // Thu
  { id: 'APT-109', day: 'Thu', time: '08:30', duration: '45m', shipmentId: 'SHP-88201', customer: 'Bosch Automotive', type: 'Delivery', status: 'Completed', dock: 'Dock 1', color: '#059669' },
  { id: 'APT-110', day: 'Thu', time: '14:00', duration: '60m', shipmentId: 'SHP-88219', customer: 'Nestle India', type: 'Pickup', status: 'Completed', dock: 'Dock 2', color: '#2563eb' },
  // Fri (Today)
  { id: 'APT-111', day: 'Fri', time: '08:00', duration: '45m', shipmentId: 'SHP-94021', customer: 'Sun Pharma Ltd', type: 'Pickup', status: 'Completed', dock: 'Dock 1', vehicle: 'MH-04-AB-1234', driver: 'Rajesh Sharma', color: '#2563eb' },
  { id: 'APT-112', day: 'Fri', time: '09:15', duration: '60m', shipmentId: 'SHP-94033', customer: 'Hero MotoCorp', type: 'Delivery', status: 'In Progress', dock: 'Dock 2', vehicle: 'PB-10-CJ-5511', driver: 'Gurpreet Singh', color: '#059669' },
  { id: 'APT-113', day: 'Fri', time: '11:00', duration: '45m', shipmentId: 'SHP-94050', customer: 'Havells India', type: 'Cross-dock', status: 'Arrived (Gate)', dock: 'Dock 3', vehicle: 'HR-26-EQ-9921', driver: 'Vikram Verma', color: '#d97706' },
  { id: 'APT-114', day: 'Fri', time: '13:30', duration: '45m', shipmentId: 'SHP-94072', customer: 'Hyundai Mobis SEZ', type: 'Delivery', status: 'Confirmed', dock: 'Dock 4', vehicle: 'TN-01-PT-3301', driver: 'Karthik R.', color: '#059669' },
  { id: 'APT-115', day: 'Fri', time: '15:45', duration: '60m', shipmentId: 'SHP-94088', customer: 'Cisco Tech India', type: 'Pickup', status: 'Confirmed', dock: 'Dock 1', vehicle: 'KA-01-EV-4412', driver: 'Ananya Deshmukh', color: '#2563eb' },
  { id: 'APT-116', day: 'Fri', time: '18:00', duration: '30m', shipmentId: 'SHP-94099', customer: 'Lupin Pharma', type: 'Pickup', status: 'Pending', dock: 'Reefer Bay', vehicle: 'MH-12-RN-8801', driver: 'Suresh Patil', color: '#2563eb' },
  // Sat
  { id: 'APT-117', day: 'Sat', time: '09:00', duration: '60m', shipmentId: 'SHP-94110', customer: 'Tata Steel Tubes', type: 'Delivery', status: 'Confirmed', dock: 'Dock 2', color: '#059669' },
  { id: 'APT-118', day: 'Sat', time: '14:30', duration: '45m', shipmentId: 'SHP-94125', customer: 'Flipkart Logistics', type: 'Cross-dock', status: 'Confirmed', dock: 'Dock 3', color: '#d97706' },
  // Sun
  { id: 'APT-119', day: 'Sun', time: '10:00', duration: '45m', shipmentId: 'SHP-94140', customer: 'Amazon IN Fulfilment', type: 'Delivery', status: 'Confirmed', dock: 'Dock 1', color: '#059669' },
];

export const todayAppointmentsList = [
  {
    id: 'APT-2024-00111',
    timeSlot: '08:00 - 08:45',
    date: '28-Sep-2024',
    shipmentId: 'SHP-94021',
    customer: 'Sun Pharma Ltd',
    contactPhone: '+91 98201 11204',
    type: 'Pickup',
    dockAssigned: 'Dock 1 (Inbound Pallet Bay)',
    vehicleReg: 'MH-04-AB-1234',
    driverName: 'Rajesh Sharma',
    cargoItems: '4 Reefer Pallets (Vaccines 2-8°C)',
    weightKg: 4500,
    volumeCbm: 16.5,
    status: 'Completed',
    arrivedAt: '07:50 IST',
    completedAt: '08:40 IST',
    dwellMinutes: 50,
  },
  {
    id: 'APT-2024-00112',
    timeSlot: '09:15 - 10:15',
    date: '28-Sep-2024',
    shipmentId: 'SHP-94033',
    customer: 'Hero MotoCorp Industrial',
    contactPhone: '+91 98112 33409',
    type: 'Delivery',
    dockAssigned: 'Dock 2 (Heavy Freight Bay)',
    vehicleReg: 'PB-10-CJ-5511',
    driverName: 'Gurpreet Singh',
    cargoItems: '24 Metal Crates Auto Sub-Assemblies',
    weightKg: 12400,
    volumeCbm: 34.0,
    status: 'In Progress',
    arrivedAt: '09:10 IST',
    completedAt: null,
    dwellMinutes: 35,
  },
  {
    id: 'APT-2024-00113',
    timeSlot: '11:00 - 11:45',
    date: '28-Sep-2024',
    shipmentId: 'SHP-94050',
    customer: 'Havells India Lighting',
    contactPhone: '+91 98450 88219',
    type: 'Cross-dock',
    dockAssigned: 'Dock 3 (Rapid Sort Cross-Dock)',
    vehicleReg: 'HR-26-EQ-9921',
    driverName: 'Vikram Verma',
    cargoItems: '140 Cartons Commercial LED Fixtures',
    weightKg: 6200,
    volumeCbm: 28.0,
    status: 'Arrived (Gate)',
    arrivedAt: '10:52 IST',
    completedAt: null,
    dwellMinutes: 12,
  },
  {
    id: 'APT-2024-00114',
    timeSlot: '13:30 - 14:15',
    date: '28-Sep-2024',
    shipmentId: 'SHP-94072',
    customer: 'Hyundai Mobis SEZ',
    contactPhone: '+91 94440 99014',
    type: 'Delivery',
    dockAssigned: 'Dock 4 (Container Chassis Bay)',
    vehicleReg: 'TN-01-PT-3301',
    driverName: 'Karthik Ramanathan',
    cargoItems: '40ft Import Container Auto Parts',
    weightKg: 28500,
    volumeCbm: 68.0,
    status: 'Confirmed',
    arrivedAt: null,
    completedAt: null,
    dwellMinutes: 0,
  },
  {
    id: 'APT-2024-00115',
    timeSlot: '15:45 - 16:45',
    date: '28-Sep-2024',
    shipmentId: 'SHP-94088',
    customer: 'Cisco Tech India',
    contactPhone: '+91 98230 44102',
    type: 'Pickup',
    dockAssigned: 'Dock 1 (Inbound Pallet Bay)',
    vehicleReg: 'KA-01-EV-4412',
    driverName: 'Ananya Deshmukh',
    cargoItems: '2 Pallets Optical Server Hardware',
    weightKg: 1200,
    volumeCbm: 6.8,
    status: 'Confirmed',
    arrivedAt: null,
    completedAt: null,
    dwellMinutes: 0,
  },
];

// ── Dock Schedule Gantt Timeline Mock Data ──
export const dockScheduleData = {
  facilityName: 'Mumbai Bhiwandi Central Logistics Hub',
  currentTimeStr: '09:45 IST',
  currentTimeXPercent: 27, // Position line on Gantt (06:00 to 22:00 timeline)
  docks: [
    {
      id: 'DOCK-01',
      name: 'Dock 1 (Pallet & Reefer Bay)',
      capacityKg: 10000,
      equipment: '2.5T Electric Forklift, Pallet Jacks, Calibrated Scale',
      status: 'Available',
      utilizationPct: 80,
      slotsBooked: '4/5 Slots',
      avgDwellMinutes: 42,
      appointments: [
        { id: 'APT-111', shipmentId: 'SHP-94021', customer: 'Sun Pharma', type: 'Pickup', startTime: '08:00', endTime: '08:45', startHour: 8, durationHours: 0.75, status: 'Completed', color: '#2563eb' },
        { id: 'APT-115', shipmentId: 'SHP-94088', customer: 'Cisco Tech', type: 'Pickup', startTime: '15:45', endTime: '16:45', startHour: 15.75, durationHours: 1.0, status: 'Scheduled', color: '#2563eb' },
      ],
    },
    {
      id: 'DOCK-02',
      name: 'Dock 2 (Heavy Freight Inbound)',
      capacityKg: 35000,
      equipment: '5.0T Counterbalance Forklift, Hydraulic Leveller',
      status: 'Occupied',
      utilizationPct: 75,
      slotsBooked: '3/4 Slots',
      avgDwellMinutes: 58,
      appointments: [
        { id: 'APT-112', shipmentId: 'SHP-94033', customer: 'Hero MotoCorp', type: 'Delivery', startTime: '09:15', endTime: '10:15', startHour: 9.25, durationHours: 1.0, status: 'Active (In Progress)', color: '#059669' },
        { id: 'APT-122', shipmentId: 'SHP-94101', customer: 'Mahindra Heavy', type: 'Delivery', startTime: '12:00', endTime: '13:30', startHour: 12.0, durationHours: 1.5, status: 'Scheduled', color: '#059669' },
      ],
    },
    {
      id: 'DOCK-03',
      name: 'Dock 3 (Rapid Sort Cross-Dock)',
      capacityKg: 15000,
      equipment: 'Automated Roller Conveyor, Barcode Sorters',
      status: 'Standby / Pre-Docking',
      utilizationPct: 65,
      slotsBooked: '3/5 Slots',
      avgDwellMinutes: 32,
      appointments: [
        { id: 'APT-113', shipmentId: 'SHP-94050', customer: 'Havells India', type: 'Cross-dock', startTime: '11:00', endTime: '11:45', startHour: 11.0, durationHours: 0.75, status: 'Arrived at Yard', color: '#d97706' },
        { id: 'APT-124', shipmentId: 'SHP-94118', customer: 'Schneider Electric', type: 'Cross-dock', startTime: '14:30', endTime: '15:30', startHour: 14.5, durationHours: 1.0, status: 'Scheduled', color: '#d97706' },
      ],
    },
    {
      id: 'DOCK-04',
      name: 'Dock 4 (Container Drayage)',
      capacityKg: 40000,
      equipment: 'Container Lock Adapters, Heavy Ramp',
      status: 'Available',
      utilizationPct: 40,
      slotsBooked: '2/5 Slots',
      avgDwellMinutes: 48,
      appointments: [
        { id: 'APT-114', shipmentId: 'SHP-94072', customer: 'Hyundai Mobis', type: 'Delivery', startTime: '13:30', endTime: '14:15', startHour: 13.5, durationHours: 0.75, status: 'Scheduled', color: '#059669' },
      ],
    },
    {
      id: 'GATE-01',
      name: 'Main Security Gate & Weighbridge',
      capacityKg: 60000,
      equipment: 'Weighbridge 60T, RFID FastTag Sensor, CCTV Boom Barrier',
      status: 'Active Clearance',
      utilizationPct: 90,
      slotsBooked: 'Continuous Flow',
      avgDwellMinutes: 6,
      appointments: [
        { id: 'SEC-01', shipmentId: 'GATE-INBOUND', customer: 'All Inbound Gate Checks', type: 'Check-In', startTime: '06:00', endTime: '22:00', startHour: 6, durationHours: 16, status: 'Active Continuous', color: '#6366f1' },
      ],
    },
  ],
  bottlenecks: [
    { dock: 'Dock 2', issue: 'High freight dwell time (58m avg). Next truck arriving in 20m.', recommendation: 'Spread pallet unloading to Dock 1 using auxiliary forklift.' },
  ],
};

// ── Visual 2D Yard Management Operations Mock Data ──
export const yardOperationsData = {
  facilityName: 'Mumbai Bhiwandi Central Logistics Hub (Yard Zone)',
  yardStats: {
    totalTrailersInYard: 18,
    inboundDocking: 4,
    outboundLoading: 3,
    stagingMarshalling: 6,
    parkedChassisStorage: 5,
    avgYardDwellHours: 3.4,
    yardUtilizationPct: 56.2,
  },
  zones: [
    {
      id: 'ZONE-INBOUND',
      name: 'Zone A: Inbound Unloading Docks (Bays 1-3)',
      type: 'Dock',
      capacityTrailers: 5,
      currentCount: 3,
      occupancyPct: 60,
      equipment: '3 Forklifts (2 Active, 1 Charging)',
      operatorAssigned: 'Mahesh Patil (Yard Supervisor)',
      status: 'Active Unloading',
      trailers: ['TR-102 (Hero MotoCorp)', 'TR-108 (Havells)', 'TR-114 (Cipla)'],
      color: '#2563eb',
    },
    {
      id: 'ZONE-OUTBOUND',
      name: 'Zone B: Outbound Dispatch Docks (Bays 4-6)',
      type: 'Dock',
      capacityTrailers: 4,
      currentCount: 2,
      occupancyPct: 50,
      equipment: '2 Pallet Jacks, 1 Forklift',
      operatorAssigned: 'Sanjay Rawat',
      status: 'Loading in Progress',
      trailers: ['TR-204 (Sun Pharma)', 'TR-209 (Cisco Tech)'],
      color: '#059669',
    },
    {
      id: 'ZONE-STAGING',
      name: 'Zone C: Marshalling & Pre-Dock Staging Yard',
      type: 'Staging',
      capacityTrailers: 12,
      currentCount: 8,
      occupancyPct: 67,
      equipment: '2 Terminal Yard Shunting Tractors (TUG-01, TUG-02)',
      operatorAssigned: 'Dinesh Kumar (Shunter)',
      status: 'Standby / Inspection',
      trailers: ['TR-301', 'TR-305', 'TR-308', 'TR-312', 'TR-319', 'TR-322', 'TR-325', 'TR-330'],
      color: '#d97706',
    },
    {
      id: 'ZONE-STORAGE',
      name: 'Zone D: Long-Term Chassis & Empty Container Storage',
      type: 'Storage',
      capacityTrailers: 20,
      currentCount: 5,
      occupancyPct: 25,
      equipment: 'Reach Stacker Crane 45T',
      operatorAssigned: 'Naveen Rao',
      status: 'Parked Empty',
      trailers: ['CH-01', 'CH-04', 'CH-09', 'CH-14', 'CH-18'],
      color: '#64748b',
    },
  ],
  vehiclesInYard: [
    {
      id: 'TR-102',
      registration: 'PB-10-CJ-5511',
      trailerNumber: 'TRL-BHW-8891',
      carrier: 'North Express Freight',
      driver: 'Gurpreet Singh',
      zone: 'Zone A: Inbound Dock 2',
      status: 'Unloading (65% done)',
      statusBadge: 'loading',
      cargo: '24 Crates Auto Parts (12,400 kg)',
      timeInYard: '48 mins',
      x: 18, // 2D layout percentage coordinates
      y: 28,
    },
    {
      id: 'TR-108',
      registration: 'HR-26-EQ-9921',
      trailerNumber: 'TRL-BHW-4412',
      carrier: 'Capital Haul Logistics',
      driver: 'Vikram Verma',
      zone: 'Zone A: Inbound Dock 3',
      status: 'Docked (Pre-Check)',
      statusBadge: 'ready',
      cargo: '140 Cartons Lighting (6,200 kg)',
      timeInYard: '22 mins',
      x: 32,
      y: 28,
    },
    {
      id: 'TR-204',
      registration: 'MH-04-AB-1234',
      trailerNumber: 'TRL-MUM-9901',
      carrier: 'LogisticsHub Dedicated Fleet',
      driver: 'Rajesh Sharma',
      zone: 'Zone B: Outbound Dock 1',
      status: 'Loading Complete (Awaiting POD)',
      statusBadge: 'ready',
      cargo: '4 Cold Boxes Pharma (+4.2°C)',
      timeInYard: '1h 12m',
      x: 68,
      y: 28,
    },
    {
      id: 'TR-301',
      registration: 'MH-12-RN-8801',
      trailerNumber: 'TRL-REF-7714',
      carrier: 'Western Cold-Chain Express',
      driver: 'Suresh Patil',
      zone: 'Zone C: Marshalling Staging Slot 4',
      status: 'Pre-Cooling Thermostat (+4°C)',
      statusBadge: 'waiting',
      cargo: 'Reefer Standby',
      timeInYard: '35 mins',
      x: 45,
      y: 65,
    },
    {
      id: 'TR-305',
      registration: 'TN-01-PT-3301',
      trailerNumber: 'TRL-CNT-3301',
      carrier: 'Chennai Port Drayage',
      driver: 'Karthik R.',
      zone: 'Zone C: Marshalling Staging Slot 8',
      status: 'Customs Paperwork Verified',
      statusBadge: 'waiting',
      cargo: '40ft Import Container (28,500 kg)',
      timeInYard: '1h 45m',
      x: 58,
      y: 65,
    },
    {
      id: 'CH-01',
      registration: 'DL-01-GH-5091',
      trailerNumber: 'CHASSIS-20FT-01',
      carrier: 'Fleet Pool',
      driver: 'Unassigned',
      zone: 'Zone D: Storage Rack Slot 2',
      status: 'Empty Parked',
      statusBadge: 'parked',
      cargo: 'None (Empty 20ft Flatbed)',
      timeInYard: '2 days',
      x: 25,
      y: 85,
    },
  ],
  recentYardMoves: [
    { id: 'MOV-401', trailer: 'TR-108 (HR-26-EQ-9921)', fromZone: 'Zone C: Staging Area', toZone: 'Zone A: Inbound Dock 3', time: '09:35 IST', operator: 'Dinesh Kumar (TUG-01)', reason: 'Dock Bay Ready' },
    { id: 'MOV-400', trailer: 'TR-204 (MH-04-AB-1234)', fromZone: 'Zone C: Staging Area', toZone: 'Zone B: Outbound Dock 1', time: '08:45 IST', operator: 'Dinesh Kumar (TUG-01)', reason: 'Outbound Loading Priority' },
    { id: 'MOV-399', trailer: 'CH-01 (DL-01-GH-5091)', fromZone: 'Zone A: Inbound Dock 1', toZone: 'Zone D: Storage Racks', time: '07:20 IST', operator: 'Naveen Rao (TUG-02)', reason: 'Unloaded - Shifted to Empty Pool' },
  ],
};
