// ── Fleet Vehicles & Fleet Analytics Mock Dataset ──
// Source: Section 12 of COMPLETE_UI_DESIGN_PROMPT.md

export const fleetSummaryStats = {
  totalVehicles: 234,
  activeOnRoad: 168,
  underMaintenance: 18,
  availableIdle: 38,
  breakdownCritical: 10,
  fleetUtilizationRate: 82.5,
  fleetUtilizationTarget: 85.0,
  avgFuelEfficiency: 6.8, // km/l
  fuelEfficiencyTrendMoM: '+2.3%',
  avgFleetAge: 3.2, // years
  breakdownRate: 2.1, // %
  telematicsConnectedRate: 97.4, // %
  pendingMaintenanceAlerts: 7,
};

export const fleetVehiclesList = [
  {
    id: 'VEH-001',
    registration: 'MH-04-AB-1234',
    type: '20ft Box Truck',
    category: 'Truck',
    make: 'Tata Motors',
    model: 'LPT 1613 Turbo',
    year: 2021,
    color: 'Industrial Arctic White',
    vin: 'MAT612089N1A29014',
    status: 'Active', // 'Active' | 'Under Maintenance' | 'Available' | 'Breakdown' | 'Retired'
    ownership: 'Company Owned',
    leaseDetails: null,
    assignedDriver: {
      id: 'DR-88201',
      name: 'Rajesh Sharma',
      phone: '+91 98201 44512',
      assignedSince: '2023-01-15',
    },
    specs: {
      payloadCapacityKg: 7500,
      volumeCapacityCbm: 24.5,
      dimensions: '6.2m (L) × 2.4m (W) × 2.5m (H)',
      axles: 2,
      grossVehicleWeightKg: 11990,
      wheelbaseMm: 4200,
      fuelType: 'Diesel (Euro VI / BS-VI)',
      fuelTankCapacityLiters: 160,
    },
    telematics: {
      gpsConnected: true,
      deviceId: 'GPS-TRK-99012',
      lastSignal: '1 min ago',
      currentLocation: 'Pune Expressway Toll Plaza (NH-48)',
      coordinates: { lat: 18.7521, lng: 73.4019 },
      currentSpeedKmH: 64,
      heading: 'South-East (135°)',
      engineStatus: 'Running',
      fuelLevelPct: 78,
      odometerKm: 184520,
      batteryHealthPct: 96,
      currentTrip: {
        id: 'TRIP-94021',
        origin: 'Mumbai Central Depot',
        destination: 'Pune Hadapsar Hub',
        distanceCoveredKm: 98,
        distanceRemainingKm: 42.6,
        eta: '16:45 IST Today',
      },
    },
    certifications: [
      { name: 'Hazmat Transport Endorsement (Class 3 & 8)', validUntil: '2025-11-30', status: 'Valid' },
      { name: 'Cold-Chain Reefer Thermostat Certified', validUntil: '2026-04-15', status: 'Valid' },
      { name: 'National Goods Carriage Permit', validUntil: '2027-01-10', status: 'Valid' },
    ],
    service: {
      lastServiceDate: '2024-08-15',
      lastServiceOdometerKm: 175000,
      nextServiceDate: '2024-11-15',
      nextServiceDueKm: 190000,
      daysRemaining: 48,
      status: 'Upcoming (Healthy)',
      maintenanceAlerts: [
        { type: 'Engine Oil & Filter', dueIn: '5,480 km or 48 days', severity: 'Normal' },
        { type: 'Front Brake Pad Inspection', dueIn: '10,000 km', severity: 'Normal' },
      ],
    },
    maintenanceHistory: [
      { id: 'SRV-891', date: '2024-08-15', type: 'Preventive Major Service (175k km)', vendor: 'Tata Authorized Commercial Service, Thane', cost: '₹14,500', odometer: '175,000 km', notes: 'Replaced fuel filters, synthetic engine oil & differential flush.' },
      { id: 'SRV-762', date: '2024-05-10', type: 'Tire Replacement (Rear Duals)', vendor: 'Apollo Commercial Tyres, Bhiwandi', cost: '₹38,000', odometer: '162,400 km', notes: 'Replaced 4 rear drive axle tires.' },
      { id: 'SRV-640', date: '2024-02-18', type: 'Brake Disc & Pad Overhaul', vendor: 'Fleet In-House Workshop', cost: '₹8,200', odometer: '150,200 km', notes: 'Front lining adjusted, air brake pneumatic valves cleaned.' },
    ],
    documents: [
      { id: 'DOC-V01', name: 'Vehicle Registration Certificate (RC)', validUntil: '2036-04-12', status: 'Valid', uploadDate: '2021-04-12', size: '2.4 MB' },
      { id: 'DOC-V02', name: 'Commercial Fleet Comprehensive Insurance', validUntil: '2025-04-11', status: 'Valid', uploadDate: '2024-04-05', size: '3.1 MB' },
      { id: 'DOC-V03', name: 'Pollution Under Control (PUC)', validUntil: '2025-02-28', status: 'Valid', uploadDate: '2024-08-20', size: '1.1 MB' },
      { id: 'DOC-V04', name: 'Statutory Fitness Certificate', validUntil: '2025-06-30', status: 'Valid', uploadDate: '2023-06-25', size: '1.8 MB' },
      { id: 'DOC-V05', name: 'Road Tax & Green Cess Receipt', validUntil: '2025-03-31', status: 'Valid', uploadDate: '2024-03-15', size: '1.4 MB' },
    ],
    fuelLogs: {
      last30DaysLiters: 580,
      avgFuelEfficiencyKmL: 6.9,
      costLast30Days: '₹55,100',
      costPerKm: '₹14.2 / km',
      recentFillups: [
        { date: '2024-09-26', quantityLiters: 110, cost: '₹10,450', odometerKm: 184100, fuelStation: 'Indian Oil COCO Highway Hub, Panvel' },
        { date: '2024-09-22', quantityLiters: 125, cost: '₹11,875', odometerKm: 183250, fuelStation: 'HP Auto Care, Pune Bypass' },
        { date: '2024-09-18', quantityLiters: 115, cost: '₹10,925', odometerKm: 182410, fuelStation: 'BPCL Highway Oasis, Nashik' },
      ],
    },
    incidents: [
      { id: 'INC-V01', date: '2024-08-14', type: 'Harsh Braking (>0.45g)', location: 'NH-48 Mile 62', speed: '68 km/h', severity: 'Low', status: 'Reviewed & Resolved' },
    ],
    costs: {
      monthlyFuel: 55100,
      monthlyMaintenance: 4800,
      monthlyInsurance: 3200,
      monthlyDriverAlloc: 42000,
      monthlyDepreciation: 8500,
      totalMonthlyTCO: 113600,
      costPerKm: '₹28.4 / km',
    },
    auditTrail: [
      { date: '2024-09-15', action: 'Route Assigned', user: 'Dispatch System (Auto)', details: 'Assigned to TRIP-94021' },
      { date: '2024-08-15', action: 'Preventive Service Logged', user: 'Maintenance Officer (Vikram N.)', details: 'Completed 175,000 km Service' },
      { date: '2023-01-15', action: 'Driver Assigned', user: 'Fleet Manager (Sunil K.)', details: 'Assigned Rajesh Sharma (DR-88201)' },
    ],
  },
  {
    id: 'VEH-002',
    registration: 'HR-26-EQ-9921',
    type: '32ft Multi-Axle Trailer',
    category: 'Trailer',
    make: 'Ashok Leyland',
    model: 'Captain 4019 Multi-Axle Heavy Hauler',
    year: 2022,
    color: 'Industrial Crimson',
    vin: 'MAL771029P3B11942',
    status: 'Active',
    ownership: 'Company Owned',
    leaseDetails: null,
    assignedDriver: {
      id: 'DR-88202',
      name: 'Vikram Singh Verma',
      phone: '+91 97112 88941',
      assignedSince: '2022-08-01',
    },
    specs: {
      payloadCapacityKg: 28000,
      volumeCapacityCbm: 68.0,
      dimensions: '12.2m (L) × 2.5m (W) × 2.8m (H)',
      axles: 4,
      grossVehicleWeightKg: 40200,
      wheelbaseMm: 6200,
      fuelType: 'Diesel (Euro VI)',
      fuelTankCapacityLiters: 350,
    },
    telematics: {
      gpsConnected: true,
      deviceId: 'GPS-TRK-99015',
      lastSignal: 'Just now',
      currentLocation: 'Manesar Logistics Corridor Gate 3',
      coordinates: { lat: 28.3588, lng: 76.9405 },
      currentSpeedKmH: 0,
      heading: 'North (0°)',
      engineStatus: 'Idle (Standby)',
      fuelLevelPct: 84,
      odometerKm: 215400,
      batteryHealthPct: 98,
      currentTrip: null,
    },
    certifications: [
      { name: 'Oversize / Heavy Machinery Transport (ODC)', validUntil: '2025-10-15', status: 'Valid' },
      { name: 'National Heavy Freight Permit', validUntil: '2026-08-30', status: 'Valid' },
    ],
    service: {
      lastServiceDate: '2024-07-20',
      lastServiceOdometerKm: 200000,
      nextServiceDate: '2024-10-20',
      nextServiceDueKm: 225000,
      daysRemaining: 22,
      status: 'Service Due Soon (22 Days)',
      maintenanceAlerts: [
        { type: 'Pneumatic Air Brake Line Pressure Check', dueIn: '9,600 km or 22 days', severity: 'Warning' },
      ],
    },
    maintenanceHistory: [
      { id: 'SRV-820', date: '2024-07-20', type: 'Major Multi-Axle Transmission & Hub Greasing', vendor: 'Ashok Leyland Authorized Hub, Gurugram', cost: '₹22,000', odometer: '200,000 km', notes: 'All 4 axles re-greased, kingpin play adjusted.' },
    ],
    documents: [
      { id: 'DOC-V11', name: 'Registration Certificate (RC)', validUntil: '2037-08-10', status: 'Valid', uploadDate: '2022-08-10', size: '2.5 MB' },
      { id: 'DOC-V12', name: 'Comprehensive Insurance', validUntil: '2025-08-09', status: 'Valid', uploadDate: '2024-08-01', size: '3.4 MB' },
    ],
    fuelLogs: {
      last30DaysLiters: 1100,
      avgFuelEfficiencyKmL: 4.8,
      costLast30Days: '₹104,500',
      costPerKm: '₹20.8 / km',
      recentFillups: [],
    },
    incidents: [],
    costs: {
      monthlyFuel: 104500,
      monthlyMaintenance: 7500,
      monthlyInsurance: 4800,
      monthlyDriverAlloc: 45000,
      monthlyDepreciation: 12000,
      totalMonthlyTCO: 173800,
      costPerKm: '₹34.5 / km',
    },
    auditTrail: [],
  },
  {
    id: 'VEH-003',
    registration: 'MH-12-RN-8801',
    type: 'Refrigerated Reefer Semi-Trailer',
    category: 'Reefer',
    make: 'BharatBenz',
    model: '2823R Reefer 2-8°C Thermo King',
    year: 2023,
    color: 'Pure White (Thermal Insulated)',
    vin: 'MEE441029R8K99014',
    status: 'Active',
    ownership: 'Leased',
    leaseDetails: {
      leasedFrom: 'LeasePlan Fleet Logistics India Pvt Ltd',
      leaseStart: '2023-03-01',
      leaseEnd: '2026-02-28',
      monthlyPayment: '₹62,000',
    },
    assignedDriver: {
      id: 'DR-88206',
      name: 'Suresh Patil',
      phone: '+91 98223 99120',
      assignedSince: '2023-03-01',
    },
    specs: {
      payloadCapacityKg: 16000,
      volumeCapacityCbm: 42.0,
      dimensions: '8.8m (L) × 2.4m (W) × 2.6m (H)',
      axles: 3,
      grossVehicleWeightKg: 28000,
      wheelbaseMm: 5175,
      fuelType: 'Diesel + Dual ThermoKing Auxiliary Genset',
      fuelTankCapacityLiters: 260,
    },
    telematics: {
      gpsConnected: true,
      deviceId: 'GPS-REEF-4401',
      lastSignal: 'Just now',
      currentLocation: 'Pune Bhosari Cold Storage SEZ',
      coordinates: { lat: 18.6298, lng: 73.8441 },
      currentSpeedKmH: 0,
      heading: 'East (90°)',
      engineStatus: 'Standby / Reefer Active (+4.2°C)',
      fuelLevelPct: 91,
      odometerKm: 98400,
      batteryHealthPct: 99,
      currentTrip: null,
    },
    certifications: [
      { name: 'Pharma GDP Cold-Chain Certified (2°C - 8°C & -20°C Deep Freeze)', validUntil: '2026-01-31', status: 'Valid' },
      { name: 'Hazmat (Class 6 - Toxic & Biological)', validUntil: '2025-11-15', status: 'Valid' },
    ],
    service: {
      lastServiceDate: '2024-09-01',
      lastServiceOdometerKm: 95000,
      nextServiceDate: '2024-12-01',
      nextServiceDueKm: 110000,
      daysRemaining: 64,
      status: 'Healthy',
      maintenanceAlerts: [],
    },
    maintenanceHistory: [
      { id: 'SRV-904', date: '2024-09-01', type: 'Thermo King Compressor & Sensor Calibration', vendor: 'Thermo King Authorized Service Center, Pune', cost: '₹18,500', odometer: '95,000 km', notes: 'Calibrated dual PT100 temperature probes, flushed freon lines.' },
    ],
    documents: [
      { id: 'DOC-V21', name: 'Lease Agreement & RC', validUntil: '2026-02-28', status: 'Valid', uploadDate: '2023-03-01', size: '4.2 MB' },
    ],
    fuelLogs: {
      last30DaysLiters: 720,
      avgFuelEfficiencyKmL: 5.6,
      costLast30Days: '₹68,400',
      costPerKm: '₹17.8 / km',
      recentFillups: [],
    },
    incidents: [],
    costs: {
      monthlyFuel: 68400,
      monthlyMaintenance: 6200,
      monthlyInsurance: 3900,
      monthlyDriverAlloc: 46000,
      monthlyDepreciation: 0,
      monthlyLease: 62000,
      totalMonthlyTCO: 186500,
      costPerKm: '₹36.0 / km',
    },
    auditTrail: [],
  },
  {
    id: 'VEH-004',
    registration: 'KA-01-EV-4412',
    type: 'Urban Electric Delivery Van',
    category: 'Electric Van',
    make: 'Tata Motors EV',
    model: 'Ace EV 1000 Pro',
    year: 2023,
    color: 'Eco Leaf Green & White',
    vin: 'MATEV99210N4K0012',
    status: 'Active',
    ownership: 'Company Owned',
    leaseDetails: null,
    assignedDriver: {
      id: 'DR-88203',
      name: 'Ananya Deshmukh',
      phone: '+91 98450 11209',
      assignedSince: '2023-04-10',
    },
    specs: {
      payloadCapacityKg: 1200,
      volumeCapacityCbm: 7.2,
      dimensions: '3.8m (L) × 1.5m (W) × 1.9m (H)',
      axles: 2,
      grossVehicleWeightKg: 2840,
      wheelbaseMm: 2100,
      fuelType: '100% Battery Electric (21.3 kWh LFP)',
      fuelTankCapacityLiters: 0, // Battery
    },
    telematics: {
      gpsConnected: true,
      deviceId: 'GPS-EV-102',
      lastSignal: 'Just now',
      currentLocation: 'Electronic City Phase 1 Express Corridor',
      coordinates: { lat: 12.8452, lng: 77.6602 },
      currentSpeedKmH: 42,
      heading: 'South (180°)',
      engineStatus: 'Running (EV Motor)',
      fuelLevelPct: 82, // Battery SOC
      odometerKm: 34100,
      batteryHealthPct: 98,
      currentTrip: {
        id: 'TRIP-94088',
        origin: 'Bengaluru Central FC',
        destination: 'Whitefield Tech Zone',
        distanceCoveredKm: 28,
        distanceRemainingKm: 8.4,
        eta: '15:10 IST',
      },
    },
    certifications: [
      { name: 'Zero-Emission Green Urban Fleet Pass', validUntil: '2028-04-09', status: 'Valid' },
      { name: 'High-Voltage Battery Safety Inspected', validUntil: '2025-04-09', status: 'Valid' },
    ],
    service: {
      lastServiceDate: '2024-06-10',
      lastServiceOdometerKm: 28000,
      nextServiceDate: '2024-12-10',
      nextServiceDueKm: 40000,
      daysRemaining: 73,
      status: 'Healthy',
      maintenanceAlerts: [],
    },
    maintenanceHistory: [
      { id: 'SRV-880', date: '2024-06-10', type: 'EV High-Voltage BMS Firmware & Cooling Service', vendor: 'Tata EV Fast Hub, Peenya', cost: '₹4,500', odometer: '28,000 km', notes: 'BMS battery cells balanced, regenerative brake pads inspected.' },
    ],
    documents: [
      { id: 'DOC-V31', name: 'Registration Certificate (EV Green Plate)', validUntil: '2038-04-09', status: 'Valid', uploadDate: '2023-04-09', size: '2.1 MB' },
    ],
    fuelLogs: {
      last30DaysLiters: 0,
      avgFuelEfficiencyKmL: 12.5, // km/kWh equivalent
      costLast30Days: '₹4,200', // EV Charging Cost
      costPerKm: '₹1.8 / km',
      recentFillups: [],
    },
    incidents: [],
    costs: {
      monthlyFuel: 4200,
      monthlyMaintenance: 1500,
      monthlyInsurance: 2400,
      monthlyDriverAlloc: 38000,
      monthlyDepreciation: 5000,
      totalMonthlyTCO: 51100,
      costPerKm: '₹12.8 / km',
    },
    auditTrail: [],
  },
  {
    id: 'VEH-005',
    registration: 'DL-01-GH-5091',
    type: '24ft Container Truck',
    category: 'Truck',
    make: 'Eicher Motors',
    model: 'Pro 3019 Heavy Commercial',
    year: 2020,
    color: 'Silver Grey',
    vin: 'MEIC301989K20194',
    status: 'Under Maintenance',
    ownership: 'Company Owned',
    leaseDetails: null,
    assignedDriver: {
      id: 'DR-88204',
      name: 'Gurpreet Singh Gill',
      phone: '+91 98150 77321',
      assignedSince: '2021-11-20',
    },
    specs: {
      payloadCapacityKg: 11000,
      volumeCapacityCbm: 38.0,
      dimensions: '7.4m (L) × 2.4m (W) × 2.5m (H)',
      axles: 2,
      grossVehicleWeightKg: 18500,
      wheelbaseMm: 4900,
      fuelType: 'Diesel (Euro VI)',
      fuelTankCapacityLiters: 190,
    },
    telematics: {
      gpsConnected: true,
      deviceId: 'GPS-TRK-7712',
      lastSignal: '12 mins ago',
      currentLocation: 'Delhi Transport Nagar Workshop Bay 4',
      coordinates: { lat: 28.7204, lng: 77.1402 },
      currentSpeedKmH: 0,
      heading: 'West (270°)',
      engineStatus: 'Off (In Workshop)',
      fuelLevelPct: 45,
      odometerKm: 248900,
      batteryHealthPct: 91,
      currentTrip: null,
    },
    certifications: [
      { name: 'National Carriage Permit', validUntil: '2025-09-30', status: 'Valid' },
    ],
    service: {
      lastServiceDate: '2024-05-15',
      lastServiceOdometerKm: 230000,
      nextServiceDate: '2024-09-28',
      nextServiceDueKm: 248000,
      daysRemaining: 0,
      status: 'In Maintenance (Clutch Overhaul)',
      maintenanceAlerts: [
        { type: 'Clutch Assembly Replacement in Progress', dueIn: 'Overdue (Under Repair)', severity: 'Urgent' },
        { type: 'Radiator Coolant Flush', dueIn: 'Current Job', severity: 'Urgent' },
      ],
    },
    maintenanceHistory: [
      { id: 'SRV-912', date: '2024-09-27', type: 'Clutch Plate & Pressure Plate Overhaul', vendor: 'Eicher Central Workshop, Okhla', cost: '₹26,000', odometer: '248,900 km', notes: 'Clutch slipped on highway. Replaced full kit and slave cylinder.' },
    ],
    documents: [],
    fuelLogs: {
      last30DaysLiters: 640,
      avgFuelEfficiencyKmL: 5.9,
      costLast30Days: '₹60,800',
      costPerKm: '₹16.5 / km',
      recentFillups: [],
    },
    incidents: [],
    costs: {
      monthlyFuel: 60800,
      monthlyMaintenance: 26000,
      monthlyInsurance: 3400,
      monthlyDriverAlloc: 48000,
      monthlyDepreciation: 9000,
      totalMonthlyTCO: 147200,
      costPerKm: '₹38.2 / km',
    },
    auditTrail: [],
  },
  {
    id: 'VEH-006',
    registration: 'TN-01-PT-3301',
    type: '40ft Port Container Drayage Tractor',
    category: 'Trailer',
    make: 'Tata Motors Heavy',
    model: 'Prima 5530.S 4x2 Tractor',
    year: 2022,
    color: 'Oceanic Blue',
    vin: 'MATPRIMA5530K1942',
    status: 'Active',
    ownership: 'Company Owned',
    leaseDetails: null,
    assignedDriver: {
      id: 'DR-88207',
      name: 'Karthik Ramanathan',
      phone: '+91 94440 22891',
      assignedSince: '2023-02-15',
    },
    specs: {
      payloadCapacityKg: 38000,
      volumeCapacityCbm: 78.0,
      dimensions: '13.6m (L) × 2.6m (W) × 3.2m (H)',
      axles: 3,
      grossVehicleWeightKg: 55000,
      wheelbaseMm: 3800,
      fuelType: 'Diesel (Cummins 6.7L 300hp)',
      fuelTankCapacityLiters: 400,
    },
    telematics: {
      gpsConnected: true,
      deviceId: 'GPS-PORT-881',
      lastSignal: 'Just now',
      currentLocation: 'Chennai Port Express Gate 4 Corridor',
      coordinates: { lat: 13.0827, lng: 80.2707 },
      currentSpeedKmH: 54,
      heading: 'West (260°)',
      engineStatus: 'Running',
      fuelLevelPct: 68,
      odometerKm: 142800,
      batteryHealthPct: 97,
      currentTrip: {
        id: 'TRIP-94072',
        origin: 'Chennai Port Container Terminal',
        destination: 'Sriperumbudur Auto SEZ',
        distanceCoveredKm: 14,
        distanceRemainingKm: 38,
        eta: '17:15 IST Today',
      },
    },
    certifications: [
      { name: 'Port Access pass & Bonded Drayage Security Card', validUntil: '2025-12-31', status: 'Valid' },
    ],
    service: {
      lastServiceDate: '2024-07-15',
      lastServiceOdometerKm: 130000,
      nextServiceDate: '2024-10-15',
      nextServiceDueKm: 150000,
      daysRemaining: 17,
      status: 'Upcoming (17 Days)',
      maintenanceAlerts: [],
    },
    maintenanceHistory: [],
    documents: [],
    fuelLogs: {
      last30DaysLiters: 980,
      avgFuelEfficiencyKmL: 4.2,
      costLast30Days: '₹93,100',
      costPerKm: '₹22.5 / km',
      recentFillups: [],
    },
    incidents: [],
    costs: {
      monthlyFuel: 93100,
      monthlyMaintenance: 7800,
      monthlyInsurance: 5200,
      monthlyDriverAlloc: 41000,
      monthlyDepreciation: 14000,
      totalMonthlyTCO: 161100,
      costPerKm: '₹37.5 / km',
    },
    auditTrail: [],
  },
  {
    id: 'VEH-007',
    registration: 'GJ-01-EF-1024',
    type: 'High-Roof Sprinter Express Van',
    category: 'Van',
    make: 'Force Motors',
    model: 'Urbania 3615 High Roof',
    year: 2023,
    color: 'Pure White',
    vin: 'MFORBANIA3615992',
    status: 'Available',
    ownership: 'Company Owned',
    leaseDetails: null,
    assignedDriver: null,
    specs: {
      payloadCapacityKg: 2200,
      volumeCapacityCbm: 14.5,
      dimensions: '5.4m (L) × 2.0m (W) × 2.4m (H)',
      axles: 2,
      grossVehicleWeightKg: 4200,
      wheelbaseMm: 3615,
      fuelType: 'Diesel (Mercedes OM616 Derived)',
      fuelTankCapacityLiters: 70,
    },
    telematics: {
      gpsConnected: true,
      deviceId: 'GPS-VAN-3301',
      lastSignal: '4 mins ago',
      currentLocation: 'Ahmedabad Sanand Hub Yard Gate 1',
      coordinates: { lat: 22.9868, lng: 72.3787 },
      currentSpeedKmH: 0,
      heading: 'North (0°)',
      engineStatus: 'Off (Ready for Dispatch)',
      fuelLevelPct: 94,
      odometerKm: 48200,
      batteryHealthPct: 99,
      currentTrip: null,
    },
    certifications: [
      { name: 'Rapid Air Freight Feeder Certified', validUntil: '2026-06-30', status: 'Valid' },
    ],
    service: {
      lastServiceDate: '2024-08-01',
      lastServiceOdometerKm: 45000,
      nextServiceDate: '2024-11-01',
      nextServiceDueKm: 55000,
      daysRemaining: 34,
      status: 'Healthy',
      maintenanceAlerts: [],
    },
    maintenanceHistory: [],
    documents: [],
    fuelLogs: {
      last30DaysLiters: 280,
      avgFuelEfficiencyKmL: 11.2,
      costLast30Days: '₹26,600',
      costPerKm: '₹8.5 / km',
      recentFillups: [],
    },
    incidents: [],
    costs: {
      monthlyFuel: 26600,
      monthlyMaintenance: 2800,
      monthlyInsurance: 2100,
      monthlyDriverAlloc: 0,
      monthlyDepreciation: 6000,
      totalMonthlyTCO: 37500,
      costPerKm: '₹12.0 / km',
    },
    auditTrail: [],
  },
  {
    id: 'VEH-008',
    registration: 'RJ-14-BR-4488',
    type: '16ft Closed Container Truck',
    category: 'Truck',
    make: 'Tata Motors',
    model: 'LPT 1109 Ex2',
    year: 2019,
    color: 'Desert Sand',
    vin: 'MAT1109RJ19042',
    status: 'Breakdown',
    ownership: 'Company Owned',
    leaseDetails: null,
    assignedDriver: {
      id: 'DR-88208',
      name: 'Deepak Choudhary',
      phone: '+91 94140 88219',
      assignedSince: '2021-04-20',
    },
    specs: {
      payloadCapacityKg: 6500,
      volumeCapacityCbm: 20.0,
      dimensions: '5.2m (L) × 2.2m (W) × 2.3m (H)',
      axles: 2,
      grossVehicleWeightKg: 10500,
      wheelbaseMm: 3800,
      fuelType: 'Diesel',
      fuelTankCapacityLiters: 120,
    },
    telematics: {
      gpsConnected: false, // Disconnected / SOS
      deviceId: 'GPS-TRK-1092',
      lastSignal: '48 mins ago (Low Voltage)',
      currentLocation: 'Jaipur Bypass Highway km 88 (Shoulder)',
      coordinates: { lat: 26.8821, lng: 75.7201 },
      currentSpeedKmH: 0,
      heading: 'East (90°)',
      engineStatus: 'Breakdown (Alternator Failure)',
      fuelLevelPct: 32,
      odometerKm: 312400,
      batteryHealthPct: 62,
      currentTrip: null,
    },
    certifications: [],
    service: {
      lastServiceDate: '2024-04-10',
      lastServiceOdometerKm: 295000,
      nextServiceDate: '2024-08-10',
      nextServiceDueKm: 310000,
      daysRemaining: -49,
      status: 'Overdue by 49 Days',
      maintenanceAlerts: [
        { type: 'Alternator & Electrical Failure (Towed to Yard)', dueIn: 'CRITICAL', severity: 'Breakdown' },
      ],
    },
    maintenanceHistory: [],
    documents: [],
    fuelLogs: {
      last30DaysLiters: 420,
      avgFuelEfficiencyKmL: 5.2,
      costLast30Days: '₹39,900',
      costPerKm: '₹18.0 / km',
      recentFillups: [],
    },
    incidents: [
      { id: 'INC-V88', date: '2024-09-28', type: 'Alternator Smoke & Total Electrical Loss', location: 'Jaipur Bypass km 88', speed: '0 km/h', severity: 'Critical', status: 'Rescue Reefer/Tow Dispatched' },
    ],
    costs: {
      monthlyFuel: 39900,
      monthlyMaintenance: 18000,
      monthlyInsurance: 2800,
      monthlyDriverAlloc: 35000,
      monthlyDepreciation: 5000,
      totalMonthlyTCO: 100700,
      costPerKm: '₹42.0 / km',
    },
    auditTrail: [],
  },
];

// ── Fleet Analytics Aggregations ──
export const fleetAnalyticsData = {
  utilizationByType: [
    { type: 'Reefer Semi-Trailers', utilization: 92.4, fleetCount: 42, color: '#0d9488' },
    { type: '32ft Multi-Axle Trailers', utilization: 88.6, fleetCount: 68, color: '#2563eb' },
    { type: '20ft/24ft Box Trucks', utilization: 84.1, fleetCount: 76, color: '#3b82f6' },
    { type: 'Urban Electric Vans', utilization: 79.5, fleetCount: 28, color: '#10b981' },
    { type: 'Courier High-Roof Vans', utilization: 74.0, fleetCount: 20, color: '#f59e0b' },
  ],
  costBreakdown: [
    { category: 'Fuel & Energy (Diesel / EV)', amount: 485000, percentage: 42.5, color: '#2563eb' },
    { category: 'Driver Compensation & Benefits', amount: 365000, percentage: 32.0, color: '#3b82f6' },
    { category: 'Preventive & Scheduled Maintenance', amount: 160000, percentage: 14.0, color: '#f59e0b' },
    { category: 'Commercial Fleet Insurance', amount: 80000, percentage: 7.0, color: '#10b981' },
    { category: 'Fleet Capital Depreciation & Leases', amount: 51000, percentage: 4.5, color: '#8b5cf6' },
  ],
  fuelEfficiencyTrend: [
    { month: 'Apr', avgKmL: 6.4, targetKmL: 6.8, totalFuelLiters: 112000, co2Tons: 298 },
    { month: 'May', avgKmL: 6.5, targetKmL: 6.8, totalFuelLiters: 114500, co2Tons: 304 },
    { month: 'Jun', avgKmL: 6.6, targetKmL: 6.8, totalFuelLiters: 111000, co2Tons: 295 },
    { month: 'Jul', avgKmL: 6.6, targetKmL: 6.8, totalFuelLiters: 109800, co2Tons: 292 },
    { month: 'Aug', avgKmL: 6.7, targetKmL: 6.8, totalFuelLiters: 108400, co2Tons: 288 },
    { month: 'Sep', avgKmL: 6.8, targetKmL: 6.8, totalFuelLiters: 106200, co2Tons: 282 },
  ],
  fleetAgeDistribution: [
    { range: '0 - 2 Years (New Fleet)', count: 68, percentage: 29.0, status: 'Optimal' },
    { range: '2 - 5 Years (Mid-Life High Yield)', count: 124, percentage: 53.0, status: 'Peak Efficiency' },
    { range: '5+ Years (Replacement Watchlist)', count: 42, percentage: 18.0, status: 'Maintenance Intensive' },
  ],
  incidentTrends: [
    { month: 'Jul', critical: 1, high: 4, medium: 8, low: 16 },
    { month: 'Aug', critical: 0, high: 3, medium: 6, low: 12 },
    { month: 'Sep', critical: 1, high: 2, medium: 5, low: 9 },
  ],
  topPerformers: [
    { id: 'VEH-004', registration: 'KA-01-EV-4412', model: 'Tata Ace EV 1000 Pro', driver: 'Ananya Deshmukh', monthlyDistanceKm: 4200, fuelKmL: '12.5 km/kWh eq', costPerKm: '₹12.8 / km', uptimePct: 99.4 },
    { id: 'VEH-003', registration: 'MH-12-RN-8801', model: 'BharatBenz 2823R Reefer', driver: 'Suresh Patil', monthlyDistanceKm: 7800, fuelKmL: '5.6 km/l', costPerKm: '₹36.0 / km', uptimePct: 98.8 },
    { id: 'VEH-001', registration: 'MH-04-AB-1234', model: 'Tata LPT 1613 Turbo', driver: 'Rajesh Sharma', monthlyDistanceKm: 6400, fuelKmL: '6.9 km/l', costPerKm: '₹28.4 / km', uptimePct: 97.6 },
    { id: 'VEH-007', registration: 'GJ-01-EF-1024', model: 'Force Urbania 3615', driver: 'Available Pool', monthlyDistanceKm: 3900, fuelKmL: '11.2 km/l', costPerKm: '₹12.0 / km', uptimePct: 97.2 },
  ],
  triageVehicles: [
    { id: 'VEH-008', registration: 'RJ-14-BR-4488', model: 'Tata LPT 1109 Ex2', issue: 'Alternator smoke breakdown on highway (Overdue 49d service)', priority: 'CRITICAL', actionNeeded: 'Tow to Jaipur Depot Workshop & schedule total engine overhaul' },
    { id: 'VEH-005', registration: 'DL-01-GH-5091', model: 'Eicher Pro 3019', issue: 'Clutch slipped under heavy payload (In Workshop Bay 4)', priority: 'HIGH', actionNeeded: 'Complete slave cylinder overhaul by 18:00 IST' },
    { id: 'VEH-002', registration: 'HR-26-EQ-9921', model: 'Ashok Leyland Captain 4019', issue: 'Pneumatic air line service due in 22 days', priority: 'MEDIUM', actionNeeded: 'Pre-book Gurugram commercial bay slot' },
  ],
};
