/**
 * LOGISTICSHUB — MOCK DATA: Orders Management
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 4 (Orders Management)
 */

export const ordersStats = {
  totalOrders: 2847,
  pendingValidation: 89,
  validatedCount: 350,
  plannedCount: 1420,
  assignedCount: 650,
  dispatchedCount: 238,
  deliveredCount: 100,
};

export const ordersList = [
  {
    id: 'ORD-2024-0891',
    customer: 'ABC Logistics Pvt Ltd',
    customerCode: 'CUST-001',
    origin: {
      locationName: 'Mumbai Central WH',
      city: 'Mumbai',
      address: 'Plot 42, MIDC Industrial Area, Andheri East, Mumbai, MH',
      pickupTime: '28-Sep-2026 09:00',
      contactPerson: 'Rohan Deshmukh',
      phone: '+91 98200 11223',
    },
    destination: {
      locationName: 'Delhi North Gate Hub',
      city: 'Delhi',
      address: 'Sector 18, Transport Nagar, GT Road, Delhi',
      deliveryTime: '29-Sep-2026 18:00',
      contactPerson: 'Vikas Malhotra',
      phone: '+91 98100 44556',
    },
    items: [
      { sku: 'SKU-PHARM-01', description: 'Cold Chain Vaccines', qty: 10, unit: 'Boxes', weightKg: 500, volumeCbm: 2.4, hazmat: false, tempRequired: true, minTemp: '+2°C', maxTemp: '+8°C' },
      { sku: 'SKU-PHARM-02', description: 'Medical Syringes Kit', qty: 2, unit: 'Pallets', weightKg: 340, volumeCbm: 1.8, hazmat: false, tempRequired: false },
    ],
    totalWeight: '840 kg',
    totalVolume: '4.2 Cbm',
    priority: 'urgent',
    serviceLevel: 'Express',
    status: 'Planned', // Draft, Pending Validation, Validated, Planned, Assigned, Dispatched, Delivered, Cancelled
    createdDate: '27-Sep-2026 09:00',
    expectedDelivery: '29-Sep-2026 18:00',
    relatedShipmentId: 'SHP-100245',
    orderValue: '₹4,50,000',
  },
  {
    id: 'ORD-2024-0892',
    customer: 'Tata Steel Infrastructure',
    customerCode: 'CUST-004',
    origin: {
      locationName: 'Pune Chakan Plant',
      city: 'Pune',
      address: 'Gate 2, Chakan MIDC Phase 2, Pune, MH',
      pickupTime: '28-Sep-2026 11:30',
      contactPerson: 'Suresh Patil',
      phone: '+91 98900 33445',
    },
    destination: {
      locationName: 'Bangalore Hub',
      city: 'Bangalore',
      address: 'Peenya Industrial Area, Stage 3, Bangalore, KA',
      deliveryTime: '30-Sep-2026 14:00',
      contactPerson: 'Kiran Rao',
      phone: '+91 98450 66778',
    },
    items: [
      { sku: 'SKU-STEEL-09', description: 'Steel Girders & Rods', qty: 5, unit: 'Bundles', weightKg: 3200, volumeCbm: 6.5, hazmat: false, tempRequired: false },
    ],
    totalWeight: '3.2 T',
    totalVolume: '6.5 Cbm',
    priority: 'high',
    serviceLevel: 'Standard',
    status: 'Pending Validation',
    createdDate: '27-Sep-2026 10:30',
    expectedDelivery: '30-Sep-2026 14:00',
    relatedShipmentId: null,
    orderValue: '₹12,80,000',
  },
  {
    id: 'ORD-2024-0893',
    customer: 'Reliance Retail Ventures',
    customerCode: 'CUST-009',
    origin: {
      locationName: 'Delhi Central Depot',
      city: 'Delhi',
      address: 'Okhla Industrial Estate Phase 3, New Delhi',
      pickupTime: '28-Sep-2026 14:00',
      contactPerson: 'Sunil Gupta',
      phone: '+91 98111 88990',
    },
    destination: {
      locationName: 'Chennai Port Facility',
      city: 'Chennai',
      address: 'Harbor Expressway Gate 4, Chennai, TN',
      deliveryTime: '01-Oct-2026 10:00',
      contactPerson: 'Mani Rajan',
      phone: '+91 98400 22334',
    },
    items: [
      { sku: 'SKU-APPRL-88', description: 'Cotton Garments Cartons', qty: 22, unit: 'Cartons', weightKg: 1200, volumeCbm: 8.0, hazmat: false, tempRequired: false },
    ],
    totalWeight: '1.2 T',
    totalVolume: '8.0 Cbm',
    priority: 'urgent',
    serviceLevel: 'Express',
    status: 'Validated',
    createdDate: '27-Sep-2026 11:00',
    expectedDelivery: '01-Oct-2026 10:00',
    relatedShipmentId: null,
    orderValue: '₹8,90,000',
  },
  {
    id: 'ORD-2024-0894',
    customer: 'Kolkata Heavy Engineering',
    customerCode: 'CUST-012',
    origin: {
      locationName: 'Kolkata Port Yard',
      city: 'Kolkata',
      address: 'Dock 5, Khidirpur, Kolkata, WB',
      pickupTime: '29-Sep-2026 08:00',
      contactPerson: 'Debabrata Sen',
      phone: '+91 98300 55667',
    },
    destination: {
      locationName: 'Hyderabad Tech Park',
      city: 'Hyderabad',
      address: 'HITEC City Phase 2, Hyderabad, TS',
      deliveryTime: '01-Oct-2026 20:00',
      contactPerson: 'Praveen Reddy',
      phone: '+91 98490 11223',
    },
    items: [
      { sku: 'SKU-MACH-04', description: 'Transformer Components', qty: 8, unit: 'Crates', weightKg: 560, volumeCbm: 3.2, hazmat: true, tempRequired: false },
    ],
    totalWeight: '560 kg',
    totalVolume: '3.2 Cbm',
    priority: 'normal',
    serviceLevel: 'Standard',
    status: 'Assigned',
    createdDate: '27-Sep-2026 12:15',
    expectedDelivery: '01-Oct-2026 20:00',
    relatedShipmentId: 'SHP-100248',
    orderValue: '₹3,40,000',
  },
  {
    id: 'ORD-2024-0895',
    customer: 'Surat Textile Mills',
    customerCode: 'CUST-015',
    origin: {
      locationName: 'Surat Textile Hub',
      city: 'Surat',
      address: 'Ring Road Textile Market, Surat, GJ',
      pickupTime: '28-Sep-2026 16:00',
      contactPerson: 'Jayesh Patel',
      phone: '+91 98250 99001',
    },
    destination: {
      locationName: 'Mumbai Port Yard',
      city: 'Mumbai',
      address: 'JNPT Port Road, Nhava Sheva, Navi Mumbai',
      deliveryTime: '29-Sep-2026 06:00',
      contactPerson: 'Anand Shinde',
      phone: '+91 98210 33445',
    },
    items: [
      { sku: 'SKU-FABRIC-02', description: 'Synthetic Yarn Spools', qty: 3, unit: 'Rolls', weightKg: 180, volumeCbm: 1.2, hazmat: false, tempRequired: false },
    ],
    totalWeight: '180 kg',
    totalVolume: '1.2 Cbm',
    priority: 'urgent',
    serviceLevel: 'Same-Day',
    status: 'Dispatched',
    createdDate: '27-Sep-2026 12:45',
    expectedDelivery: '29-Sep-2026 06:00',
    relatedShipmentId: 'SHP-100249',
    orderValue: '₹1,75,000',
  },
];

export const validationQueue = [
  {
    orderId: 'ORD-2024-0892',
    customer: 'Tata Steel Infrastructure',
    severity: 'critical', // critical, warning, passed
    errorsCount: 2,
    errorList: [
      { field: 'Delivery Address', message: 'PIN Code 560058 does not match Peenya Industrial Area district', fixType: 'address' },
      { field: 'Cargo Weight Limit', message: 'Total weight (3.2 T) exceeds assigned van axle load', fixType: 'capacity' },
    ],
    timestamp: '15 mins ago',
  },
  {
    orderId: 'ORD-2024-0898',
    customer: 'Cipla Pharma Ltd',
    severity: 'warning',
    errorsCount: 1,
    errorList: [
      { field: 'Contact Phone Number', message: 'Driver phone number missing leading country code', fixType: 'contact' },
    ],
    timestamp: '32 mins ago',
  },
];
