/**
 * LOGISTICSHUB — MOCK DATA: Transportation Planning
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 6 (Transportation Planning)
 */

export const planningStats = {
  totalDemandKg: '2,450 kg',
  totalDemandCbm: '12.5 Cbm',
  totalAssignedKg: '1,800 kg',
  weightUtilPct: 73.5,
  volumeUtilPct: 73.6,
  estimatedCost: '$2,445',
  backhaulOppsCount: 3,
  readyToPlanCount: 8,
};

export const unallocatedDemand = [
  {
    id: 'DEM-001',
    orderId: 'ORD-2024-0891',
    customer: 'ABC Logistics Pvt Ltd',
    origin: 'Mumbai',
    destination: 'Delhi',
    weightKg: 840,
    volumeCbm: 4.2,
    serviceLevel: 'Express',
    pickupDate: '28-Sep 09:00',
    deliveryDeadline: '29-Sep 18:00',
    tempRequired: '+4°C Cold Chain',
    hazmat: false,
  },
  {
    id: 'DEM-002',
    orderId: 'ORD-2024-0892',
    customer: 'Tata Steel Infrastructure',
    origin: 'Pune',
    destination: 'Bangalore',
    weightKg: 3200,
    volumeCbm: 6.5,
    serviceLevel: 'Standard',
    pickupDate: '28-Sep 11:30',
    deliveryDeadline: '30-Sep 14:00',
    tempRequired: null,
    hazmat: false,
  },
  {
    id: 'DEM-003',
    orderId: 'ORD-2024-0893',
    customer: 'Reliance Retail',
    origin: 'Delhi',
    destination: 'Chennai',
    weightKg: 1200,
    volumeCbm: 8.0,
    serviceLevel: 'Express',
    pickupDate: '28-Sep 14:00',
    deliveryDeadline: '01-Oct 10:00',
    tempRequired: null,
    hazmat: false,
  },
  {
    id: 'DEM-004',
    orderId: 'ORD-2024-0894',
    customer: 'Kolkata Heavy Eng',
    origin: 'Kolkata',
    destination: 'Hyderabad',
    weightKg: 560,
    volumeCbm: 3.2,
    serviceLevel: 'Standard',
    pickupDate: '29-Sep 08:00',
    deliveryDeadline: '01-Oct 20:00',
    tempRequired: null,
    hazmat: true,
  },
  {
    id: 'DEM-005',
    orderId: 'ORD-2024-0895',
    customer: 'Surat Textile Mills',
    origin: 'Surat',
    destination: 'Mumbai',
    weightKg: 180,
    volumeCbm: 1.2,
    serviceLevel: 'Same-Day',
    pickupDate: '28-Sep 16:00',
    deliveryDeadline: '29-Sep 06:00',
    tempRequired: null,
    hazmat: false,
  }
];

export const carrierCapacityList = [
  {
    carrierId: 'CRR-01',
    carrierName: 'Express Logistics (Heavy Fleet)',
    vehicleType: 'Heavy Truck (18T)',
    maxWeightKg: 5000,
    maxVolumeCbm: 20,
    assignedWeightKg: 3675,
    assignedVolumeCbm: 14.7,
    fillPct: 73.5,
    onTimeRating: '95.2%',
    ratePer100Kg: '$245',
    transitDays: '2.3 Days',
    status: 'optimal',
  },
  {
    carrierId: 'CRR-02',
    carrierName: 'BlueDart Freight (Trailer Fleet)',
    vehicleType: 'Multi-Axle Trailer',
    maxWeightKg: 8000,
    maxVolumeCbm: 30,
    assignedWeightKg: 7040,
    assignedVolumeCbm: 26.4,
    fillPct: 88.0,
    onTimeRating: '93.1%',
    ratePer100Kg: '$238',
    transitDays: '2.5 Days',
    status: 'optimal',
  },
  {
    carrierId: 'CRR-03',
    carrierName: 'Spot Carrier Services',
    vehicleType: 'Medium Van (5T)',
    maxWeightKg: 2500,
    maxVolumeCbm: 10,
    assignedWeightKg: 1125,
    assignedVolumeCbm: 4.5,
    fillPct: 45.0,
    onTimeRating: '88.5%',
    ratePer100Kg: '$220',
    transitDays: '3.1 Days',
    status: 'under-utilized',
  },
];

export const replanTriggers = [
  {
    id: 'TRIG-01',
    name: 'Vehicle Breakdown > Auto Reassign',
    type: 'Breakdown Event',
    status: 'Active',
    lastTriggered: '14 mins ago',
    affectedCount: 2,
    description: 'Auto-reroutes shipments when OBD-II reports severe engine fault or transmission lock.',
  },
  {
    id: 'TRIG-02',
    name: 'ETA Delay > Recalculate Route Corridor',
    type: 'ETA Delay > 60m',
    status: 'Active',
    lastTriggered: '45 mins ago',
    affectedCount: 4,
    description: 'Recalculates transit ETA and dispatches SLA delay warnings to customer contacts.',
  },
  {
    id: 'TRIG-03',
    name: 'Carrier Tender Rejection > Backup Tender',
    type: 'Tender Rejection',
    status: 'Active',
    lastTriggered: '1 hour ago',
    affectedCount: 1,
    description: 'Tenders load to secondary fallback carrier if primary carrier rejects within 2h.',
  },
];
