/**
 * LOGISTICSHUB — MOCK DATA: Procurement & Freight Tendering
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 9 (Procurement & Tender)
 */

export const initialKanbanTenders = {
  draft: [
    {
      id: 'TEN-801',
      shipmentId: 'SHP-100251',
      origin: 'Mumbai Central Hub',
      destination: 'Delhi NCR Logistics Park',
      weightKg: 1850,
      volumeCbm: 8.2,
      items: 14,
      serviceLevel: 'Express',
      createdDate: '2026-09-27',
      estimatedBudget: 380,
      status: 'draft',
      specialRequirements: ['Liftgate Required', 'Fragile Handling'],
    },
    {
      id: 'TEN-802',
      shipmentId: 'SHP-100253',
      origin: 'Pune MIDC Sector 2',
      destination: 'Bangalore Electronic City',
      weightKg: 3200,
      volumeCbm: 14.5,
      items: 26,
      serviceLevel: 'Standard',
      createdDate: '2026-09-27',
      estimatedBudget: 620,
      status: 'draft',
      specialRequirements: ['Full Truckload (FTL)'],
    },
    {
      id: 'TEN-803',
      shipmentId: 'SHP-100258',
      origin: 'Surat Textile Zone',
      destination: 'Kolkata Port Terminal',
      weightKg: 950,
      volumeCbm: 4.6,
      items: 8,
      serviceLevel: 'Express',
      createdDate: '2026-09-26',
      estimatedBudget: 290,
      status: 'draft',
      specialRequirements: ['High-Value Cargo Insurance'],
    },
  ],

  sent: [
    {
      id: 'TEN-791',
      shipmentId: 'SHP-100245',
      origin: 'Delhi Gate North',
      destination: 'Jaipur Industrial Corridor',
      weightKg: 2400,
      volumeCbm: 10.4,
      items: 18,
      serviceLevel: 'Express',
      sentDate: '2026-09-27 08:30',
      deadlineHoursLeft: 4.5,
      deadlineTime: 'Today, 18:00',
      isUrgent: false,
      invitedCarriers: [
        { name: 'BlueDart Logistics', code: 'BD', avatarColor: '#2563eb' },
        { name: 'Express Freight Corp', code: 'EF', avatarColor: '#10b981' },
        { name: 'Apex Cargo Lines', code: 'AC', avatarColor: '#f59e0b' },
      ],
      responsesCount: '1 / 3 Bids Received',
      status: 'sent',
      specialRequirements: ['Time-Critical SLA'],
    },
    {
      id: 'TEN-792',
      shipmentId: 'SHP-100247',
      origin: 'Mumbai Nhava Sheva',
      destination: 'Ahmedabad S.G. Highway',
      weightKg: 4500,
      volumeCbm: 18.0,
      items: 32,
      serviceLevel: 'Standard',
      sentDate: '2026-09-27 09:15',
      deadlineHoursLeft: 1.8,
      deadlineTime: 'Today, 15:00',
      isUrgent: true,
      invitedCarriers: [
        { name: 'Mahindra Logistics', code: 'ML', avatarColor: '#ef4444' },
        { name: 'VRL Logistics', code: 'VR', avatarColor: '#8b5cf6' },
        { name: 'Safexpress Logistics', code: 'SE', avatarColor: '#06b6d4' },
        { name: 'Delhivery Freight', code: 'DL', avatarColor: '#d97706' },
      ],
      responsesCount: '2 / 4 Bids Received',
      status: 'sent',
      specialRequirements: ['Heavy Multi-Axle'],
    },
    {
      id: 'TEN-794',
      shipmentId: 'SHP-100262',
      origin: 'Chennai Auto Cluster',
      destination: 'Hyderabad HITEC Hub',
      weightKg: 1200,
      volumeCbm: 5.5,
      items: 12,
      serviceLevel: 'Express',
      sentDate: '2026-09-27 10:00',
      deadlineHoursLeft: 5.2,
      deadlineTime: 'Today, 19:30',
      isUrgent: false,
      invitedCarriers: [
        { name: 'BlueDart Logistics', code: 'BD', avatarColor: '#2563eb' },
        { name: 'TCI Express', code: 'TC', avatarColor: '#16a34a' },
      ],
      responsesCount: '0 / 2 Bids Received',
      status: 'sent',
      specialRequirements: ['Pallet Jack Required'],
    },
  ],

  responses_received: [
    {
      id: 'TEN-785',
      shipmentId: 'SHP-100238',
      origin: 'Bangalore Electronic City',
      destination: 'Chennai Port Terminal',
      weightKg: 2800,
      volumeCbm: 12.0,
      items: 20,
      serviceLevel: 'Standard',
      responsesCount: 3,
      bestPrice: 310,
      bestCarrier: 'Safexpress Logistics',
      status: 'responses_received',
      specialRequirements: ['GPS Telematics Mandatory'],
      bids: [
        { carrierName: 'Safexpress Logistics', bidPrice: 310, otp: 96.2, acceptanceRate: 98, mcdaScore: 91.5, recommended: true },
        { carrierName: 'BlueDart Logistics', bidPrice: 335, otp: 97.5, acceptanceRate: 95, mcdaScore: 88.0, recommended: false },
        { carrierName: 'VRL Logistics', bidPrice: 350, otp: 92.0, acceptanceRate: 91, mcdaScore: 79.4, recommended: false },
      ],
    },
    {
      id: 'TEN-786',
      shipmentId: 'SHP-100240',
      origin: 'Delhi Cold Chain Hub',
      destination: 'Lucknow Transport Nagar',
      weightKg: 1600,
      volumeCbm: 7.4,
      items: 15,
      serviceLevel: 'Express',
      responsesCount: 4,
      bestPrice: 245,
      bestCarrier: 'Express Freight Corp',
      status: 'responses_received',
      specialRequirements: ['+4°C Refrigerated Container'],
      bids: [
        { carrierName: 'Express Freight Corp', bidPrice: 245, otp: 95.8, acceptanceRate: 96, mcdaScore: 93.2, recommended: true },
        { carrierName: 'Snowman Cold Chain', bidPrice: 260, otp: 98.4, acceptanceRate: 99, mcdaScore: 92.0, recommended: false },
        { carrierName: 'TCI Cold Chain', bidPrice: 275, otp: 93.0, acceptanceRate: 92, mcdaScore: 82.5, recommended: false },
        { carrierName: 'Mahindra Reefer', bidPrice: 290, otp: 91.5, acceptanceRate: 88, mcdaScore: 76.0, recommended: false },
      ],
    },
  ],

  evaluated: [
    {
      id: 'TEN-778',
      shipmentId: 'SHP-100230',
      origin: 'Mumbai Central Port',
      destination: 'Pune Chakan Industrial',
      weightKg: 5200,
      volumeCbm: 22.5,
      items: 45,
      serviceLevel: 'Standard',
      recommendedCarrier: 'Mahindra Logistics',
      recommendedPrice: 420,
      overallScore: 92.4,
      alternativeCarrier: 'VRL Logistics ($445 - 84.0 Score)',
      status: 'evaluated',
      specialRequirements: ['Over-Dimensional Cargo (ODC)'],
      bids: [
        { carrierName: 'Mahindra Logistics', bidPrice: 420, otp: 96.8, acceptanceRate: 97, mcdaScore: 92.4, recommended: true },
        { carrierName: 'VRL Logistics', bidPrice: 445, otp: 93.2, acceptanceRate: 94, mcdaScore: 84.0, recommended: false },
        { carrierName: 'BlueDart Logistics', bidPrice: 490, otp: 97.0, acceptanceRate: 95, mcdaScore: 80.5, recommended: false },
      ],
    },
    {
      id: 'TEN-779',
      shipmentId: 'SHP-100233',
      origin: 'Hyderabad MedTech Park',
      destination: 'Nagpur Central Hub',
      weightKg: 1100,
      volumeCbm: 4.8,
      items: 10,
      serviceLevel: 'Express',
      recommendedCarrier: 'BlueDart Logistics',
      recommendedPrice: 215,
      overallScore: 94.8,
      alternativeCarrier: 'TCI Express ($230 - 86.5 Score)',
      status: 'evaluated',
      specialRequirements: ['Pharma GDP Compliant'],
      bids: [
        { carrierName: 'BlueDart Logistics', bidPrice: 215, otp: 98.6, acceptanceRate: 99, mcdaScore: 94.8, recommended: true },
        { carrierName: 'TCI Express', bidPrice: 230, otp: 94.0, acceptanceRate: 93, mcdaScore: 86.5, recommended: false },
      ],
    },
  ],

  awarded: [
    {
      id: 'TEN-760',
      shipmentId: 'SHP-100215',
      origin: 'Delhi Hub',
      destination: 'Mumbai Nhava Sheva',
      weightKg: 6400,
      volumeCbm: 28.0,
      items: 50,
      serviceLevel: 'Standard',
      awardedTo: 'Safexpress Logistics',
      awardedPrice: 780,
      awardedDate: '2026-09-26 16:45',
      dispatchStatus: 'Confirmed & Driver Assigned',
      status: 'awarded',
    },
    {
      id: 'TEN-761',
      shipmentId: 'SHP-100218',
      origin: 'Bangalore Hub',
      destination: 'Hyderabad Hub',
      weightKg: 2100,
      volumeCbm: 9.2,
      items: 16,
      serviceLevel: 'Express',
      awardedTo: 'BlueDart Logistics',
      awardedPrice: 340,
      awardedDate: '2026-09-26 17:10',
      dispatchStatus: 'Pending Vehicle Docking',
      status: 'awarded',
    },
    {
      id: 'TEN-762',
      shipmentId: 'SHP-100222',
      origin: 'Kolkata Sector V',
      destination: 'Patna Industrial Zone',
      weightKg: 1450,
      volumeCbm: 6.0,
      items: 12,
      serviceLevel: 'Standard',
      awardedTo: 'Express Freight Corp',
      awardedPrice: 260,
      awardedDate: '2026-09-26 14:20',
      dispatchStatus: 'In Transit',
      status: 'awarded',
    },
  ],

  rejected: [
    {
      id: 'TEN-750',
      shipmentId: 'SHP-100201',
      origin: 'Guwahati Hub',
      destination: 'Kolkata Terminal',
      weightKg: 3100,
      volumeCbm: 13.5,
      items: 22,
      serviceLevel: 'Express',
      declinedBy: 'NorthEast Express Cargo',
      reason: 'No available multi-axle trailer capacity on mountain corridor',
      backupOption: 'Re-tender on Spot Freight Exchange',
      status: 'rejected',
    },
    {
      id: 'TEN-751',
      shipmentId: 'SHP-100204',
      origin: 'Indore Food Park',
      destination: 'Bhopal Bypass Hub',
      weightKg: 850,
      volumeCbm: 3.8,
      items: 8,
      serviceLevel: 'Standard',
      declinedBy: 'Central Logistics Line',
      reason: 'Quote exceeded maximum cost ceiling tolerance',
      backupOption: 'Bundled into Regional Multi-Drop Run',
      status: 'rejected',
    },
  ],
};

export const carrierDirectory = [
  { id: 'CAR-01', name: 'BlueDart Logistics', rating: 4.9, otp: 98.2, fleetSize: 450, coverage: 'Pan-India Express', preferred: true },
  { id: 'CAR-02', name: 'Safexpress Logistics', rating: 4.85, otp: 96.5, fleetSize: 620, coverage: 'Heavy Surface & 3PL', preferred: true },
  { id: 'CAR-03', name: 'Mahindra Logistics', rating: 4.75, otp: 95.8, fleetSize: 380, coverage: 'Automotive & FTL', preferred: true },
  { id: 'CAR-04', name: 'VRL Logistics', rating: 4.7, otp: 93.4, fleetSize: 510, coverage: 'Western & Southern Corridors', preferred: false },
  { id: 'CAR-05', name: 'Express Freight Corp', rating: 4.8, otp: 96.0, fleetSize: 290, coverage: 'North-South Fast Trunk', preferred: true },
  { id: 'CAR-06', name: 'Delhivery Freight', rating: 4.78, otp: 95.1, fleetSize: 410, coverage: 'E-commerce & Mid-Mile', preferred: false },
];
