/**
 * LOGISTICSHUB — MOCK DATA: Routing & Optimization
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 8 (Routing & Optimization)
 */

export const initialRouteData = {
  routeId: 'RT-2026-0891',
  status: 'Draft',
  routeType: 'Multi-Stop Delivery',
  startDepot: 'Central Hub - West Logistics Park (Depot #1)',
  endDepot: 'Central Hub - West Logistics Park (Depot #1)',
  startTime: '06:00 AM',
  assignedVehicle: 'VEH-3042 (20ft Container - 5,000 kg cap)',
  assignedDriver: 'John Smith (CDL-A Certified - 9.5h Available)',
  totalStops: 6,
  totalDistanceKm: 234,
  estimatedDuration: '8h 45m',
  weightUtilizationPct: 56.2,
  volumeUtilizationPct: 58.4,
  estimatedCost: 189,
  efficiencyScore: 82,
  stops: [
    {
      id: 'ST-01',
      order: 1,
      type: 'depot_start',
      name: 'Central Hub - West Logistics Park',
      address: '742 Evergreen Blvd, Westside Industrial Park',
      items: 0,
      weightKg: 0,
      volumeCbm: 0,
      timeWindow: '06:00 - 06:30',
      contact: 'Dispatcher Office',
      phone: '+1 (555) 019-2834',
      status: 'Ready',
      x: 80,
      y: 180,
    },
    {
      id: 'ST-02',
      order: 2,
      type: 'delivery',
      name: 'Apex Supermarkets Corp',
      address: '104 Commerce St, Metro Gateway Plaza',
      items: 3,
      weightKg: 450,
      volumeCbm: 1.8,
      timeWindow: '08:00 - 09:30',
      contact: 'Michael Davis (Receiving Mgr)',
      phone: '+1 (555) 432-8765',
      status: 'Confirmed',
      x: 220,
      y: 100,
    },
    {
      id: 'ST-03',
      order: 3,
      type: 'delivery',
      name: 'Zenith Electronics Distribution',
      address: '58 Tech Zone Way, North District',
      items: 2,
      weightKg: 280,
      volumeCbm: 1.2,
      timeWindow: '10:00 - 11:30',
      contact: 'Sarah Lin (Warehouse Lead)',
      phone: '+1 (555) 789-0123',
      status: 'Confirmed',
      x: 380,
      y: 70,
    },
    {
      id: 'ST-04',
      order: 4,
      type: 'pickup',
      name: 'Summit Packaging Industries',
      address: '910 Riverbank Rd, East Port Sector',
      items: 4,
      weightKg: 620,
      volumeCbm: 2.6,
      timeWindow: '12:00 - 13:30',
      contact: 'Robert Chen (Shipping Clerk)',
      phone: '+1 (555) 234-5678',
      status: 'Pending Verification',
      x: 520,
      y: 160,
    },
    {
      id: 'ST-05',
      order: 5,
      type: 'delivery',
      name: 'Global MedTech Supply',
      address: '320 Highland Avenue, Healthcare Zone',
      items: 2,
      weightKg: 190,
      volumeCbm: 0.9,
      timeWindow: '14:00 - 15:15',
      contact: 'Dr. Emily Vance (Inventory Head)',
      phone: '+1 (555) 678-9012',
      status: 'Confirmed',
      x: 440,
      y: 280,
    },
    {
      id: 'ST-06',
      order: 6,
      type: 'delivery',
      name: 'Pinnacle Auto Parts Depot',
      address: '14 Industrial Bypass, South Terminal',
      items: 5,
      weightKg: 780,
      volumeCbm: 3.1,
      timeWindow: '16:00 - 17:15',
      contact: 'Carlos Mendez (Dock Supervisor)',
      phone: '+1 (555) 345-6789',
      status: 'Confirmed',
      x: 260,
      y: 310,
    },
    {
      id: 'ST-07',
      order: 7,
      type: 'depot_end',
      name: 'Central Hub - West Logistics Park',
      address: '742 Evergreen Blvd, Westside Industrial Park',
      items: 0,
      weightKg: 0,
      volumeCbm: 0,
      timeWindow: '18:00 - 18:30',
      contact: 'Gate Inbound Inspector',
      phone: '+1 (555) 019-2834',
      status: 'Scheduled',
      x: 80,
      y: 180,
    },
  ],
};

export const availableVehicles = [
  { id: 'VEH-3042', name: 'VEH-3042 (20ft Container - 5,000 kg cap)', type: '20ft Box Truck', capacityKg: 5000, volumeCbm: 24, features: 'Liftgate, GPS Telematics, Temperature Controlled' },
  { id: 'VEH-8190', name: 'VEH-8190 (32ft Multi-Axle - 12,000 kg cap)', type: '32ft Trailer', capacityKg: 12000, volumeCbm: 48, features: 'Heavy Payload, Hazmat Certified, Dual Axle' },
  { id: 'VEH-1024', name: 'VEH-1024 (Sprinter Van - 2,200 kg cap)', type: 'Urban Van', capacityKg: 2200, volumeCbm: 12, features: 'Rapid Courier, City Permitted, EV Powertrain' },
];

export const availableDrivers = [
  { id: 'DRV-101', name: 'John Smith (CDL-A Certified - 9.5h Available)', hoursLeft: '9.5h', rating: 4.9, certs: 'Hazmat, Multi-Drop, Defensive Driving' },
  { id: 'DRV-102', name: 'Elena Rostova (CDL-A Certified - 8.0h Available)', hoursLeft: '8.0h', rating: 4.95, certs: 'Reefer Master, Oversized Load' },
  { id: 'DRV-103', name: 'Marcus Brody (CDL-B Certified - 11.0h Available)', hoursLeft: '11.0h', rating: 4.85, certs: 'Urban Fast Delivery, Liftgate Tech' },
];

export const availableDepots = [
  'Central Hub - West Logistics Park (Depot #1)',
  'North Gate Distribution Facility (Depot #2)',
  'East Harbor Maritime Terminal (Depot #3)',
  'South Metro Cross-Dock Facility (Depot #4)',
];

export const routeComplianceRules = [
  { id: 'c1', label: 'Axle & Weight Distribution', status: 'pass', detail: 'Total payload 2,320 kg (46.4% of 5,000 kg limit)' },
  { id: 'c2', label: 'Volume Space Distribution', status: 'pass', detail: 'Total volume 9.6 cbm within 24 cbm envelope' },
  { id: 'c3', label: 'Hazmat & Chemical Segregation', status: 'pass', detail: 'Zero conflicting dangerous goods loaded' },
  { id: 'c4', label: 'Customer Time Windows Guaranteed', status: 'pass', detail: 'All 6 stops planned within appointment slots' },
  { id: 'c5', label: 'Driver HOS (Hours of Service) Compliance', status: 'pass', detail: '8h 45m planned route vs 11.0h DOT threshold' },
  { id: 'c6', label: 'Urban Zone Delivery Clearance', status: 'pass', detail: 'Vehicle certified for Downtown low-emission sectors' },
];

export const optimizationSolutions = {
  solution1: {
    id: 'SOL-01',
    title: 'Best Cost (Maximum Consolidation)',
    badge: 'Recommended',
    tagColor: '#2563eb',
    cost: 2145,
    distanceKm: 1240,
    duration: '18h 20m',
    vehiclesUsed: '8 / 12 Vehicles',
    weightUtilization: 88.5,
    volumeUtilization: 91.2,
    costSavingsPct: 12.5,
    timeSavingsPct: 4.2,
    co2ReductionKg: 380,
    unassignedShipments: 0,
    feasibility: '100% Feasible',
    routes: [
      { id: 'OPT-R1', vehicle: 'VEH-3042 (20ft Container)', driver: 'John Smith', stops: 8, distanceKm: 156, time: '2h 15m', cost: 245, fillRate: '92%' },
      { id: 'OPT-R2', vehicle: 'VEH-8190 (32ft Trailer)', driver: 'Elena Rostova', stops: 12, distanceKm: 280, time: '4h 30m', cost: 420, fillRate: '95%' },
      { id: 'OPT-R3', vehicle: 'VEH-1024 (Sprinter Van)', driver: 'Marcus Brody', stops: 6, distanceKm: 98, time: '1h 45m', cost: 160, fillRate: '88%' },
      { id: 'OPT-R4', vehicle: 'VEH-5091 (24ft Box Truck)', driver: 'David Kim', stops: 10, distanceKm: 210, time: '3h 10m', cost: 310, fillRate: '90%' },
      { id: 'OPT-R5', vehicle: 'VEH-7723 (32ft Trailer)', driver: 'Rachel Green', stops: 14, distanceKm: 310, time: '4h 50m', cost: 480, fillRate: '94%' },
      { id: 'OPT-R6', vehicle: 'VEH-2291 (Urban Van)', driver: 'Sam Taylor', stops: 5, distanceKm: 86, time: '1h 50m', cost: 190, fillRate: '85%' },
      { id: 'OPT-R7', vehicle: 'VEH-6601 (20ft Container)', driver: 'Tom Hardy', stops: 7, distanceKm: 100, time: '2h 00m', cost: 220, fillRate: '89%' },
      { id: 'OPT-R8', vehicle: 'VEH-9012 (Express Van)', driver: 'Lisa Kudrow', stops: 4, distanceKm: 0, time: '0h 40m', cost: 120, fillRate: '82%' },
    ],
  },
  solution2: {
    id: 'SOL-02',
    title: 'Fastest Delivery (Express Turnaround)',
    badge: 'Fastest ETA',
    tagColor: '#059669',
    cost: 2380,
    distanceKm: 1120,
    duration: '16h 45m',
    vehiclesUsed: '9 / 12 Vehicles',
    weightUtilization: 82.4,
    volumeUtilization: 85.0,
    costSavingsPct: 7.8,
    timeSavingsPct: 14.8,
    co2ReductionKg: 290,
    unassignedShipments: 0,
    feasibility: '100% Feasible',
    routes: [
      { id: 'OPT-F1', vehicle: 'VEH-1024 (Sprinter Van)', driver: 'Marcus Brody', stops: 5, distanceKm: 90, time: '1h 20m', cost: 180, fillRate: '80%' },
      { id: 'OPT-F2', vehicle: 'VEH-3042 (20ft Container)', driver: 'John Smith', stops: 7, distanceKm: 130, time: '1h 55m', cost: 230, fillRate: '85%' },
      { id: 'OPT-F3', vehicle: 'VEH-8190 (32ft Trailer)', driver: 'Elena Rostova', stops: 10, distanceKm: 240, time: '3h 40m', cost: 390, fillRate: '88%' },
      { id: 'OPT-F4', vehicle: 'VEH-5091 (24ft Box Truck)', driver: 'David Kim', stops: 8, distanceKm: 180, time: '2h 40m', cost: 290, fillRate: '82%' },
      { id: 'OPT-F5', vehicle: 'VEH-7723 (32ft Trailer)', driver: 'Rachel Green', stops: 11, distanceKm: 260, time: '3h 50m', cost: 430, fillRate: '86%' },
    ],
  },
  solution3: {
    id: 'SOL-03',
    title: 'Balanced Trade-off (Cost & SLA)',
    badge: 'Balanced',
    tagColor: '#d97706',
    cost: 2210,
    distanceKm: 1190,
    duration: '17h 10m',
    vehiclesUsed: '8 / 12 Vehicles',
    weightUtilization: 86.2,
    volumeUtilization: 88.4,
    costSavingsPct: 10.2,
    timeSavingsPct: 10.5,
    co2ReductionKg: 340,
    unassignedShipments: 0,
    feasibility: '100% Feasible',
    routes: [
      { id: 'OPT-B1', vehicle: 'VEH-3042 (20ft Container)', driver: 'John Smith', stops: 8, distanceKm: 145, time: '2h 05m', cost: 240, fillRate: '90%' },
      { id: 'OPT-B2', vehicle: 'VEH-8190 (32ft Trailer)', driver: 'Elena Rostova', stops: 11, distanceKm: 265, time: '4h 10m', cost: 410, fillRate: '92%' },
      { id: 'OPT-B3', vehicle: 'VEH-5091 (24ft Box Truck)', driver: 'David Kim', stops: 9, distanceKm: 195, time: '3h 00m', cost: 300, fillRate: '87%' },
    ],
  },
  solution4: {
    id: 'SOL-04',
    title: 'Eco-Green (Low Emissions & Fuel)',
    badge: 'Eco Friendly',
    tagColor: '#16a34a',
    cost: 2190,
    distanceKm: 1140,
    duration: '17h 35m',
    vehiclesUsed: '8 / 12 Vehicles',
    weightUtilization: 87.0,
    volumeUtilization: 89.1,
    costSavingsPct: 11.0,
    timeSavingsPct: 7.5,
    co2ReductionKg: 520,
    unassignedShipments: 0,
    feasibility: '100% Feasible',
    routes: [
      { id: 'OPT-E1', vehicle: 'VEH-1024 (EV Urban Van)', driver: 'Marcus Brody', stops: 7, distanceKm: 85, time: '1h 35m', cost: 140, fillRate: '91%' },
      { id: 'OPT-E2', vehicle: 'VEH-3042 (Euro 6 Diesel)', driver: 'John Smith', stops: 9, distanceKm: 140, time: '2h 10m', cost: 235, fillRate: '93%' },
    ],
  },
};
