/**
 * LOGISTICSHUB — MOCK DATA: Saved Views
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 3 (Saved Views)
 */

export const savedViewsStats = {
  totalViews: 12,
  systemPresets: 5,
  customViews: 4,
  sharedViews: 3,
};

export const availableWidgets = [
  { id: 'w-kpi', name: 'Executive KPI Strip', category: 'Executive', description: 'Top-level shipments, spend, and exceptions metrics' },
  { id: 'w-freight', name: '12-Month Freight Spend Chart', category: 'Financial', description: 'Area trend chart tracking monthly spend vs budget' },
  { id: 'w-capacity', name: 'Fleet Capacity Stacked Bar', category: 'Operations', description: 'Load fill percentage breakdown by vehicle type' },
  { id: 'w-dock', name: 'Dock Facility Occupancy', category: 'Facility', description: 'Real-time loading bay dock utilization bars' },
  { id: 'w-timeline', name: 'Next 24H Dispatch Timeline', category: 'Operations', description: 'Chronological timeline of upcoming pickups & deliveries' },
  { id: 'w-map', name: 'GIS Control Tower Canvas', category: 'Telemetry', description: 'Interactive dark vector map displaying active GPS vehicle pins' },
  { id: 'w-alerts', name: 'Triage Alerts Stack', category: 'Exceptions', description: 'Live exception queue ordered by severity' },
];

export const savedViewsList = [
  {
    id: 'view-01',
    title: 'Morning Ops Briefing',
    description: 'Daily operational snapshot configured for AM standup meetings. Focuses on capacity, trip status, and dock occupancy.',
    category: 'preset',
    owner: 'System Preset',
    lastModified: 'Today at 08:00',
    refreshRate: 'Every 30s',
    widgetsCount: 4,
    sharedUsersCount: 18,
    isFavorite: true,
    color: '#0066CC',
    icon: 'Sun',
    targetPath: '/ops-dashboard',
  },
  {
    id: 'view-02',
    title: 'Executive Summary',
    description: 'High-level executive financial and SLA health board. Includes 12-month freight spend and carrier performance leaderboards.',
    category: 'preset',
    owner: 'System Preset',
    lastModified: 'Yesterday',
    refreshRate: 'Manual',
    widgetsCount: 5,
    sharedUsersCount: 24,
    isFavorite: true,
    color: '#27AE60',
    icon: 'Briefcase',
    targetPath: '/',
  },
  {
    id: 'view-03',
    title: 'Night Shift Telemetry Monitor',
    description: 'Dark-mode GIS Control Tower layout tailored for overnight dispatchers monitoring unattended vehicles and cold chain breaches.',
    category: 'preset',
    owner: 'System Preset',
    lastModified: '26-Sep 23:00',
    refreshRate: 'Real-time (5s)',
    widgetsCount: 3,
    sharedUsersCount: 8,
    isFavorite: false,
    color: '#E74C3C',
    icon: 'Moon',
    targetPath: '/control-tower',
  },
  {
    id: 'view-04',
    title: 'Carrier SLA & Penalty Tracking',
    description: 'Monitors top carrier on-time delivery rates, penalty thresholds, and unassigned tender orders.',
    category: 'custom',
    owner: 'Ramesh Patel (You)',
    lastModified: '25-Sep 14:30',
    refreshRate: 'Every 5m',
    widgetsCount: 4,
    sharedUsersCount: 3,
    isFavorite: false,
    color: '#FF9800',
    icon: 'Award',
    targetPath: '/ops-dashboard',
  },
  {
    id: 'view-05',
    title: 'Cold Chain Exception War Room',
    description: 'Dedicated exception queue filtered exclusively for temperature breach alerts and reefer unit breakdowns.',
    category: 'shared',
    owner: 'QA Audit Team',
    lastModified: '24-Sep 11:15',
    refreshRate: 'Real-time (5s)',
    widgetsCount: 2,
    sharedUsersCount: 12,
    isFavorite: true,
    color: '#17A2B8',
    icon: 'Thermometer',
    targetPath: '/alerts-center',
  },
  {
    id: 'view-06',
    title: 'Dock & Hub Bottleneck Analysis',
    description: 'Facility dock occupancy and gate delay analysis across Mumbai, Delhi, and Bangalore hubs.',
    category: 'custom',
    owner: 'Ramesh Patel (You)',
    lastModified: '22-Sep 09:45',
    refreshRate: 'Every 30s',
    widgetsCount: 3,
    sharedUsersCount: 5,
    isFavorite: false,
    color: '#6C3483',
    icon: 'Anchor',
    targetPath: '/ops-dashboard',
  },
];
