/**
 * LOGISTICSHUB — MOCK DATA: Shipments Management
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 5 (Shipments Management)
 */

export const shipmentsStats = {
  totalShipments: 5234,
  inTransitCount: 2840,
  atRiskCount: 142,
  deliveredCount: 1980,
  consolidationCandidatesCount: 18,
};

export const shipmentsList = [
  {
    id: 'SHP-100245',
    orderId: 'ORD-2024-0891',
    customer: 'ABC Logistics Pvt Ltd',
    origin: { city: 'Mumbai', address: 'Mumbai Central WH', pickupTime: '28-Sep 09:00' },
    destination: { city: 'Pune', address: 'Pune Distribution Hub', deliveryTime: '28-Sep 14:00' },
    carrier: 'Express Logistics',
    driverName: 'Ramesh Kumar',
    vehicleNumber: 'MH-12-AB-1234',
    gpsLocation: 'NH-48 Km 42 (Near Panvel Plaza)',
    weight: '840 kg',
    volume: '4.2 Cbm',
    status: 'In Transit', // Planned, Confirmed, Assigned, In Transit, At Risk, Delivered, Cancelled
    eta: '28-Sep 14:00',
    progressPct: 72,
    serviceLevel: 'Express',
  },
  {
    id: 'SHP-100246',
    orderId: 'ORD-2024-0892',
    customer: 'Tata Steel Infrastructure',
    origin: { city: 'Pune', address: 'Pune Chakan Plant', pickupTime: '28-Sep 11:30' },
    destination: { city: 'Bangalore', address: 'Peenya Hub, Bangalore', deliveryTime: '28-Sep 19:15' },
    carrier: 'BlueDart Logistics',
    driverName: 'Suresh Sharma',
    vehicleNumber: 'MH-14-CD-5678',
    gpsLocation: 'Lonavala Exit Plaza (Traffic Delay)',
    weight: '3.2 T',
    volume: '6.5 Cbm',
    status: 'At Risk',
    eta: '28-Sep 19:15',
    progressPct: 45,
    serviceLevel: 'Standard',
  },
  {
    id: 'SHP-100247',
    orderId: 'ORD-2024-0893',
    customer: 'Reliance Retail Ventures',
    origin: { city: 'Delhi', address: 'Delhi North Gate Facility', pickupTime: '27-Sep 21:00' },
    destination: { city: 'Jaipur', address: 'Jaipur Industrial Area', deliveryTime: '29-Sep 11:30' },
    carrier: 'Spot Carrier Services',
    driverName: 'Anil Patel',
    vehicleNumber: 'DL-08-EF-9012',
    gpsLocation: 'NH-48 Border Plaza (Stationary Breakdown)',
    weight: '1.2 T',
    volume: '8.0 Cbm',
    status: 'At Risk',
    eta: '29-Sep 11:30',
    progressPct: 30,
    serviceLevel: 'Express',
  },
  {
    id: 'SHP-100248',
    orderId: 'ORD-2024-0894',
    customer: 'Kolkata Heavy Engineering',
    origin: { city: 'Kolkata', address: 'Kolkata Port Yard', pickupTime: '28-Sep 08:00' },
    destination: { city: 'Hyderabad', address: 'Hyderabad Tech Park', deliveryTime: '28-Sep 21:00' },
    carrier: 'Express Logistics',
    driverName: 'Vijay Singh',
    vehicleNumber: 'KA-05-GH-3456',
    gpsLocation: 'Vijayawada Expressway Km 110',
    weight: '560 kg',
    volume: '3.2 Cbm',
    status: 'In Transit',
    eta: '28-Sep 21:00',
    progressPct: 85,
    serviceLevel: 'Standard',
  },
  {
    id: 'SHP-100249',
    orderId: 'ORD-2024-0895',
    customer: 'Surat Textile Mills',
    origin: { city: 'Surat', address: 'Surat Textile Hub', pickupTime: '28-Sep 12:45' },
    destination: { city: 'Mumbai', address: 'Nhava Sheva Port Yard', deliveryTime: '28-Sep 16:30' },
    carrier: 'QuickTrans India',
    driverName: 'Manoj Verma',
    vehicleNumber: 'GJ-01-IJ-7890',
    gpsLocation: 'Vapi Industrial Toll',
    weight: '180 kg',
    volume: '1.2 Cbm',
    status: 'In Transit',
    eta: '28-Sep 16:30',
    progressPct: 90,
    serviceLevel: 'Same-Day',
  },
  {
    id: 'SHP-100250',
    orderId: 'ORD-2024-0896',
    customer: 'Chennai Auto Ancillaries',
    origin: { city: 'Chennai', address: 'Chennai Port Terminal', pickupTime: '27-Sep 18:00' },
    destination: { city: 'Coimbatore', address: 'Coimbatore Industrial Hub', deliveryTime: '29-Sep 08:30' },
    carrier: 'Southern Freight Corp',
    driverName: 'Deepak Tiwari',
    vehicleNumber: 'TN-10-KL-2345',
    gpsLocation: 'Vellore Bypass Expressway',
    weight: '2.4 T',
    volume: '5.4 Cbm',
    status: 'In Transit',
    eta: '29-Sep 08:30',
    progressPct: 40,
    serviceLevel: 'Standard',
  }
];

export const consolidationCandidates = [
  { id: 'SHP-LTL-01', origin: 'Mumbai WH', destination: 'Delhi Hub', weightKg: 420, volumeCbm: 2.1, customer: 'Cipla Pharma', readyDate: 'Today 14:00' },
  { id: 'SHP-LTL-02', origin: 'Mumbai WH', destination: 'Delhi Hub', weightKg: 580, volumeCbm: 3.4, customer: 'Sun Retail', readyDate: 'Today 15:30' },
  { id: 'SHP-LTL-03', origin: 'Mumbai WH', destination: 'Delhi Hub', weightKg: 350, volumeCbm: 1.8, customer: 'Apollo Tech', readyDate: 'Today 16:00' },
  { id: 'SHP-LTL-04', origin: 'Mumbai WH', destination: 'Delhi Hub', weightKg: 890, volumeCbm: 4.6, customer: 'Godrej Goods', readyDate: 'Today 17:00' },
  { id: 'SHP-LTL-05', origin: 'Pune MIDC', destination: 'Bangalore Hub', weightKg: 640, volumeCbm: 3.0, customer: 'Bajaj Auto', readyDate: 'Today 18:00' },
];
