/**
 * LOGISTICSHUB — MOCK DATA: Live Tracking & Visibility
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 13 (Live Tracking & Visibility)
 */

export const liveTrackedVehicles = [
  {
    id: 'VEH-3042',
    registration: 'MH-12-AB-3042',
    driver: 'John Smith',
    driverPhone: '+1 (555) 234-5678',
    vehicleType: '20ft Box Truck',
    status: 'on_time', // on_time | at_risk | delayed | idle | offline
    speedKmH: 68,
    heading: 'North-East (NE 42°)',
    fuelPct: 82,
    tempC: '+4.2°C (Reefer Pass)',
    currentTripId: 'TRIP-870',
    origin: 'Mumbai Central Hub',
    destination: 'Pune MIDC Sector 4',
    nextStop: 'Apex Supermarkets Receiving Dock',
    distanceRemainingKm: 64,
    eta: 'Today 12:00',
    delayMinutes: 0,
    lastUpdated: 'Just now (Live Ping)',
    x: 180,
    y: 190,
    breadcrumbs: [
      { x: 80, y: 180 },
      { x: 130, y: 185 },
      { x: 180, y: 190 },
    ],
    geofenceInside: 'Westside Logistics Park',
  },
  {
    id: 'VEH-8190',
    registration: 'MH-14-CD-8190',
    driver: 'Elena Rostova',
    driverPhone: '+1 (555) 345-6789',
    vehicleType: '32ft Multi-Axle Trailer',
    status: 'at_risk',
    speedKmH: 42,
    heading: 'South (S 180°)',
    fuelPct: 74,
    tempC: 'Ambient (+22°C)',
    currentTripId: 'TRIP-865',
    origin: 'Delhi Gate North',
    destination: 'Jaipur Industrial Corridor',
    nextStop: 'Highway Toll Gate Plaza 3',
    distanceRemainingKm: 142,
    eta: 'Today 16:30',
    delayMinutes: 14,
    lastUpdated: '1 min ago',
    x: 360,
    y: 110,
    breadcrumbs: [
      { x: 300, y: 60 },
      { x: 330, y: 85 },
      { x: 360, y: 110 },
    ],
    geofenceInside: 'Northern Freight Highway Corridor',
  },
  {
    id: 'VEH-1024',
    registration: 'GJ-01-EF-1024',
    driver: 'Marcus Brody',
    driverPhone: '+1 (555) 456-7890',
    vehicleType: 'Sprinter Courier Van',
    status: 'on_time',
    speedKmH: 54,
    heading: 'East (E 90°)',
    fuelPct: 91,
    tempC: 'Ambient (+20°C)',
    currentTripId: 'TRIP-881',
    origin: 'Ahmedabad SEZ Gate',
    destination: 'Vadodara City Terminal',
    nextStop: 'Zenith Electronics Hub',
    distanceRemainingKm: 28,
    eta: 'Today 09:30',
    delayMinutes: 0,
    lastUpdated: 'Live Ping',
    x: 480,
    y: 220,
    breadcrumbs: [
      { x: 420, y: 200 },
      { x: 450, y: 210 },
      { x: 480, y: 220 },
    ],
    geofenceInside: 'Eastern Industrial Zone',
  },
  {
    id: 'VEH-5091',
    registration: 'DL-01-GH-5091',
    driver: 'David Kim',
    driverPhone: '+1 (555) 567-8901',
    vehicleType: '24ft Container Truck',
    status: 'delayed',
    speedKmH: 15,
    heading: 'North (N 0°)',
    fuelPct: 65,
    tempC: '+3.8°C (Cold Chain Pass)',
    currentTripId: 'TRIP-872',
    origin: 'Hyderabad MedTech Park',
    destination: 'Nagpur Central Hub',
    nextStop: 'Highland Avenue Medical Center',
    distanceRemainingKm: 88,
    eta: 'Today 13:45',
    delayMinutes: 38,
    lastUpdated: '2 mins ago',
    x: 290,
    y: 310,
    breadcrumbs: [
      { x: 250, y: 330 },
      { x: 270, y: 320 },
      { x: 290, y: 310 },
    ],
    geofenceInside: 'Southern Metro Terminal',
  },
  {
    id: 'VEH-7723',
    registration: 'KA-04-IJ-7723',
    driver: 'Rachel Green',
    driverPhone: '+1 (555) 678-9012',
    vehicleType: '32ft Multi-Axle Trailer',
    status: 'on_time',
    speedKmH: 72,
    heading: 'West (W 270°)',
    fuelPct: 86,
    tempC: 'Ambient (+24°C)',
    currentTripId: 'TRIP-890',
    origin: 'Bangalore Electronic City',
    destination: 'Chennai Marine Terminal',
    nextStop: 'Coastal Freight Interchange',
    distanceRemainingKm: 110,
    eta: 'Today 17:00',
    delayMinutes: 0,
    lastUpdated: 'Live Ping',
    x: 540,
    y: 120,
    breadcrumbs: [
      { x: 480, y: 100 },
      { x: 510, y: 110 },
      { x: 540, y: 120 },
    ],
    geofenceInside: 'Coastal Port Logistics SEZ',
  },
  {
    id: 'VEH-2291',
    registration: 'TN-09-KL-2291',
    driver: 'Sam Taylor',
    driverPhone: '+1 (555) 789-0123',
    vehicleType: 'Medium Freight Van',
    status: 'offline',
    speedKmH: 0,
    heading: 'Stationary (0°)',
    fuelPct: 50,
    tempC: 'Ambient',
    currentTripId: null,
    origin: 'Depot Maintenance Bay',
    destination: 'Standby / Idle',
    nextStop: 'Scheduled Maintenance Bay 3',
    distanceRemainingKm: 0,
    eta: 'Standby',
    delayMinutes: 0,
    lastUpdated: '15 mins ago',
    x: 90,
    y: 280,
    breadcrumbs: [],
    geofenceInside: 'Central Hub Maintenance Yard',
  },
];

export const geofenceZones = [
  { id: 'geo-1', name: 'Westside Logistics Park', points: '40,140 160,120 180,240 60,250', color: 'rgba(37, 99, 235, 0.12)', border: '#3b82f6', activeVehicles: 4 },
  { id: 'geo-2', name: 'Northern Industrial Corridor', points: '280,30 420,20 440,140 300,150', color: 'rgba(16, 185, 129, 0.12)', border: '#10b981', activeVehicles: 6 },
  { id: 'geo-3', name: 'Eastern Port Terminal Zone', points: '460,80 590,70 610,210 470,220', color: 'rgba(245, 158, 11, 0.12)', border: '#f59e0b', activeVehicles: 5 },
  { id: 'geo-4', name: 'Southern Metro Distribution Hub', points: '220,260 380,250 400,360 230,370', color: 'rgba(124, 58, 237, 0.12)', border: '#7c3aed', activeVehicles: 3 },
];

export const trackingGlobalStats = {
  totalVehicles: 234,
  onlineTracked: 212,
  onTime: 145,
  atRisk: 34,
  delayed: 22,
  offline: 22,
  fleetUtilizationPct: 89.2,
};

export const detailedShipmentsTracking = [
  {
    id: 'SHP-100245',
    orderId: 'ORD-90812',
    customer: 'ABC Logistics Pvt Ltd',
    origin: 'Delhi Gate North Hub',
    originAddress: 'Plot 42, North Gateway Logistics Park, Delhi',
    destination: 'Jaipur Industrial Corridor',
    destinationAddress: 'Unit 12, Sanganer Industrial SEZ, Jaipur, RJ',
    status: 'In Transit (On-Time)',
    expectedDelivery: 'Today, 14:00',
    serviceLevel: 'Express Guaranteed',
    progressPct: 81,
    totalDistanceKm: 234,
    completedDistanceKm: 189,
    remainingDistanceKm: 45,
    speedKmH: 62,
    currentLocationName: 'Highway NH-48 Expressway Sector 6',
    carrier: 'BlueDart Express Line',
    vehicleRegistration: 'MH-12-AB-3042',
    driverName: 'John Smith',
    driverPhone: '+1 (555) 234-5678',
    itemsCount: 3,
    weightKg: 250,
    volumeCbm: 1.2,
    hazmat: false,
    tempControl: false,
    originCoords: { x: 60, y: 180 },
    currentCoords: { x: 380, y: 150 },
    destinationCoords: { x: 560, y: 140 },
    eventsTimeline: [
      { id: 'ev-1', title: 'Order Created & Confirmed', time: 'Today 09:00', location: 'Delhi Operations Center', actor: 'ERP System', completed: true, details: 'Order received and credit limit validated.' },
      { id: 'ev-2', title: 'Shipment Generated & Waybill Printed', time: 'Today 09:15', location: 'Delhi Gate Hub', actor: 'Automated Dispatcher', completed: true, details: 'e-Waybill generated with QR verification code.' },
      { id: 'ev-3', title: 'Carrier Assigned', time: 'Today 10:00', location: 'Dispatch Board', actor: 'Dispatcher Mike', completed: true, details: 'Assigned to BlueDart unit MH-12-AB-3042 (John Smith).' },
      { id: 'ev-4', title: 'Pickup Completed & Sealed', time: 'Today 10:45', location: 'Origin Dock Gate 4', actor: 'Dock Lead Raj', completed: true, details: 'Digital Security Seal #SEAL-98741-A verified.' },
      { id: 'ev-5', title: 'Departed Origin Terminal', time: 'Today 11:00', location: 'Delhi Gateway Plaza', actor: 'Vehicle Telematics', completed: true, details: 'Departed origin on scheduled highway route.' },
      { id: 'ev-6', title: 'In Transit — Highway Corridor', time: 'Today 12:30 (Current)', location: 'Highway NH-48 Sector 6', actor: 'GPS Ping (62 km/h)', completed: true, details: 'Telematics ping verified, running on-time within green corridor.' },
      { id: 'ev-7', title: 'Arrival at Destination Hub', time: 'Estimated 13:45', location: 'Jaipur Cross-Dock Gate 2', actor: 'Scheduled', completed: false, details: 'Scheduled cross-dock de-vanning and sorting.' },
      { id: 'ev-8', title: 'Final Customer Handover & ePOD', time: 'Estimated 14:00', location: 'Customer Receiving Bay', actor: 'Recipient', completed: false, details: 'Digital signature and physical parcel delivery.' },
    ],
    liveStream: [
      { id: 'ls-1', time: '12:35', event: 'GPS Location Ping', location: 'NH-48 Corridor Mile 84', speed: '62 km/h', status: 'Normal' },
      { id: 'ls-2', time: '12:20', event: 'Toll Plaza Passed', location: 'Shahjahanpur Toll Plaza', speed: '58 km/h', status: 'Fastag Cleared' },
      { id: 'ls-3', time: '12:05', event: 'Speed Monitoring Ping', location: 'NH-48 Sector 4', speed: '65 km/h', status: 'Normal' },
      { id: 'ls-4', time: '11:45', event: 'Geofence Exit', location: 'NCR Delhi Logistics Park Boundary', speed: '48 km/h', status: 'On Route' },
    ],
    documents: [
      { id: 'doc-1', title: 'Electronic Bill of Lading (e-BOL)', size: '240 KB', type: 'PDF', date: '27-Sep-2026' },
      { id: 'doc-2', title: 'Commercial Packing Manifest', size: '180 KB', type: 'PDF', date: '27-Sep-2026' },
      { id: 'doc-3', title: 'GST e-Waybill Certificate', size: '120 KB', type: 'PDF', date: '27-Sep-2026' },
    ],
    exceptions: [],
  },
  {
    id: 'SHP-100247',
    orderId: 'ORD-90815',
    customer: 'Reliance Retail Supply',
    origin: 'Mumbai Nhava Sheva Port',
    originAddress: 'Terminal 3 Gate 8, Nhava Sheva Port, MH',
    destination: 'Ahmedabad S.G. Highway',
    destinationAddress: 'Sector 9, S.G. Highway Industrial Zone, Ahmedabad, GJ',
    status: 'At Risk (+15m Delay)',
    expectedDelivery: 'Today, 18:45',
    serviceLevel: 'Standard Ground',
    progressPct: 52,
    totalDistanceKm: 520,
    completedDistanceKm: 270,
    remainingDistanceKm: 250,
    speedKmH: 42,
    currentLocationName: 'Surat Bypass Highway Toll Plaza',
    carrier: 'Safexpress Logistics',
    vehicleRegistration: 'MH-14-CD-8190',
    driverName: 'Elena Rostova',
    driverPhone: '+1 (555) 345-6789',
    itemsCount: 12,
    weightKg: 4500,
    volumeCbm: 18.0,
    hazmat: false,
    tempControl: false,
    originCoords: { x: 80, y: 320 },
    currentCoords: { x: 300, y: 220 },
    destinationCoords: { x: 500, y: 100 },
    eventsTimeline: [
      { id: 'ev-21', title: 'Order Created & Booked', time: 'Today 07:00', location: 'Mumbai HQ', actor: 'System', completed: true, details: 'Standard booking.' },
      { id: 'ev-22', title: 'Port Gate Dispatched', time: 'Today 09:00', location: 'Nhava Sheva Port', actor: 'Port Inspector', completed: true, details: 'Heavy container loaded.' },
      { id: 'ev-23', title: 'In Transit — Surat Bypass Slowdown', time: 'Today 13:00 (Current)', location: 'Surat Bypass', actor: 'GPS Ping (42 km/h)', completed: true, details: 'Monsoon congestion identified on highway.' },
      { id: 'ev-24', title: 'Final Destination Arrival', time: 'Estimated 18:45', location: 'Ahmedabad SEZ', actor: 'Scheduled', completed: false, details: 'Delayed by +15m.' },
    ],
    liveStream: [
      { id: 'ls-21', time: '13:00', event: 'Congestion Slowdown Alert', location: 'Surat Bypass Mile 22', speed: '42 km/h', status: 'Moderate Traffic' },
      { id: 'ls-22', time: '12:30', event: 'GPS Location Ping', location: 'Navsari Highway Sector', speed: '55 km/h', status: 'Normal' },
    ],
    documents: [
      { id: 'doc-21', title: 'Heavy Freight Bill of Lading', size: '310 KB', type: 'PDF', date: '27-Sep-2026' },
      { id: 'doc-22', title: 'Port Gate Outbound Pass', size: '150 KB', type: 'PDF', date: '27-Sep-2026' },
    ],
    exceptions: [
      { id: 'exc-1', title: 'Highway Monsoon Waterlogging', severity: 'Medium', impact: '+15m Delay', resolution: 'Rerouting via State Toll Ring Road' },
    ],
  },
  {
    id: 'SHP-100250',
    orderId: 'ORD-90820',
    customer: 'Apollo Hospitals Pharma Hub',
    origin: 'Hyderabad MedTech Park',
    originAddress: 'Pharma City Corridor, Hyderabad, TS',
    destination: 'Nagpur Central Hub',
    destinationAddress: 'Healthcare Zone, Wardha Road, Nagpur, MH',
    status: 'In Transit (Temp Verified)',
    expectedDelivery: 'Today, 15:30',
    serviceLevel: 'Critical Cold Chain',
    progressPct: 68,
    totalDistanceKm: 340,
    completedDistanceKm: 230,
    remainingDistanceKm: 110,
    speedKmH: 65,
    currentLocationName: 'Adilabad Express Highway Mile 18',
    carrier: 'Express Freight Corp',
    vehicleRegistration: 'DL-01-GH-5091',
    driverName: 'David Kim',
    driverPhone: '+1 (555) 567-8901',
    itemsCount: 4,
    weightKg: 620,
    volumeCbm: 3.2,
    hazmat: false,
    tempControl: true,
    originCoords: { x: 120, y: 300 },
    currentCoords: { x: 340, y: 190 },
    destinationCoords: { x: 520, y: 80 },
    eventsTimeline: [
      { id: 'ev-31', title: 'Cold Chain Pharma Pickup', time: 'Today 08:00', location: 'Hyderabad MedTech', actor: 'Pharma Lead', completed: true, details: '+3.8°C Temperature Verified.' },
      { id: 'ev-32', title: 'Departed MedTech Hub', time: 'Today 08:30', location: 'Hyderabad Gate 2', actor: 'Driver David', completed: true, details: 'Active Reefer Unit Running.' },
      { id: 'ev-33', title: 'In Transit — Temperature Stable', time: 'Today 12:45 (Current)', location: 'Adilabad Sector', actor: 'IoT Sensor Ping', completed: true, details: 'Chamber temperature constant at +3.8°C.' },
      { id: 'ev-34', title: 'Hospital Receiving Dock Arrival', time: 'Estimated 15:30', location: 'Nagpur Pharma Center', actor: 'Scheduled', completed: false, details: 'Direct cold room handover.' },
    ],
    liveStream: [
      { id: 'ls-31', time: '12:45', event: 'IoT Temp Sensor Ping', location: 'Adilabad Corridor', speed: '65 km/h', status: '+3.8°C Safe' },
    ],
    documents: [
      { id: 'doc-31', title: 'GDP Cold Chain Temperature Log', size: '420 KB', type: 'PDF', date: '27-Sep-2026' },
      { id: 'doc-32', title: 'Pharma Delivery Waybill', size: '200 KB', type: 'PDF', date: '27-Sep-2026' },
    ],
    exceptions: [],
  },
];

export const etaPredictionsList = [
  {
    id: 'ETA-101',
    vehicleId: 'VEH-3042',
    registration: 'MH-12-AB-3042',
    vehicleType: '20ft Box Truck',
    driver: 'John Smith',
    driverPhone: '+1 (555) 234-5678',
    currentLocation: 'Highway NH-48 Mile 42 (Sector 6)',
    origin: 'Delhi Gate North',
    destination: 'Jaipur Industrial Corridor',
    scheduledArrival: 'Today, 14:00',
    predictedArrival: 'Today, 14:00',
    varianceMinutes: 0,
    onTimeProbability: 96,
    status: 'on_time', // on_time | at_risk | delayed
    customer: 'ABC Logistics Pvt Ltd',
    customerContact: 'tracking@abclogistics.com',
    serviceLevel: 'Express SLA Guaranteed',
    factors: {
      traffic: 'Free Flow (0m delay)',
      distanceRemainingKm: 45,
      currentSpeedKmH: 62,
      segmentAvgSpeedKmH: 58,
      stopDurationMin: 0,
      weather: 'Clear Sky (No impact)',
      historicalPattern: 'Matches top 5% fastest corridor runs',
    },
    breakdown: {
      drivingTimeMin: 42,
      stopTimeMin: 0,
      bufferMin: 3,
      totalRemainingMin: 45,
    },
    confidence: {
      percentage: 95,
      level: 'High Precision',
      gpsSignal: '100% (5 satellites locked)',
      trafficStream: 'Active Telematics Stream',
      hardwareHealth: 'OBD-II CAN-Bus 100% OK',
    },
    whatIfScenarios: {
      worsenTraffic: { title: 'If Traffic Congestion +30%', newETA: '14:25', impact: '+25m' },
      fuelStop: { title: 'If 15-min Fuel & Inspection Stop', newETA: '14:15', impact: '+15m' },
      speedBoost: { title: 'If Highway Speed Increases +10%', newETA: '13:52', impact: '-8m (Early)' },
    },
  },
  {
    id: 'ETA-102',
    vehicleId: 'VEH-8190',
    registration: 'MH-14-CD-8190',
    vehicleType: '32ft Multi-Axle Trailer',
    driver: 'Elena Rostova',
    driverPhone: '+1 (555) 345-6789',
    currentLocation: 'Surat Bypass Toll Plaza Gate 4',
    origin: 'Mumbai Nhava Sheva Port',
    destination: 'Ahmedabad S.G. Highway',
    scheduledArrival: 'Today, 17:00',
    predictedArrival: 'Today, 18:45',
    varianceMinutes: 105,
    onTimeProbability: 38,
    status: 'delayed',
    customer: 'Reliance Retail Supply',
    customerContact: 'supplychain@relianceretail.com',
    serviceLevel: 'Standard Heavy Freight',
    factors: {
      traffic: 'Heavy Monsoon Waterlogging (+85m delay)',
      distanceRemainingKm: 142,
      currentSpeedKmH: 42,
      segmentAvgSpeedKmH: 60,
      stopDurationMin: 20,
      weather: 'Heavy Monsoon Rain (+20m impact)',
      historicalPattern: 'Severe monsoon bottleneck observed at Surat ring',
    },
    breakdown: {
      drivingTimeMin: 145,
      stopTimeMin: 20,
      bufferMin: 10,
      totalRemainingMin: 175,
    },
    confidence: {
      percentage: 92,
      level: 'High Precision',
      gpsSignal: '98% (High signal)',
      trafficStream: 'Live Sensor Grid Connected',
      hardwareHealth: 'CAN-Bus Verified',
    },
    whatIfScenarios: {
      rerouteRing: { title: 'If Reroute via State Toll Ring Road', newETA: '17:35', impact: '-70m Recovery' },
      worsenRain: { title: 'If Rain Continues > 2 hours', newETA: '19:15', impact: '+30m Further Delay' },
      priorityClearance: { title: 'If Green-Corridor Toll Pass Triggered', newETA: '17:50', impact: '-55m Recovery' },
    },
  },
  {
    id: 'ETA-103',
    vehicleId: 'VEH-1024',
    registration: 'GJ-01-EF-1024',
    vehicleType: 'Sprinter Courier Van',
    driver: 'Marcus Brody',
    driverPhone: '+1 (555) 456-7890',
    currentLocation: 'Ahmedabad Outer Ring Road km 12',
    origin: 'Ahmedabad SEZ Gate',
    destination: 'Vadodara City Terminal',
    scheduledArrival: 'Today, 09:30',
    predictedArrival: 'Today, 09:30',
    varianceMinutes: 0,
    onTimeProbability: 98,
    status: 'on_time',
    customer: 'Zenith Electronics Corp',
    customerContact: 'dispatch@zenithelec.com',
    serviceLevel: 'Same-Day Fast Track',
    factors: {
      traffic: 'Optimal Corridor (0m impact)',
      distanceRemainingKm: 28,
      currentSpeedKmH: 54,
      segmentAvgSpeedKmH: 50,
      stopDurationMin: 0,
      weather: 'Clear (No impact)',
      historicalPattern: 'Consistently completes in 32 mins',
    },
    breakdown: {
      drivingTimeMin: 28,
      stopTimeMin: 0,
      bufferMin: 2,
      totalRemainingMin: 30,
    },
    confidence: {
      percentage: 97,
      level: 'Very High',
      gpsSignal: '100%',
      trafficStream: 'Live Traffic Flow Verified',
      hardwareHealth: 'Normal',
    },
    whatIfScenarios: {
      cityTraffic: { title: 'If City Inbound Congestion Occurs', newETA: '09:42', impact: '+12m' },
      directDock: { title: 'If Direct Unloading at Dock 2', newETA: '09:25', impact: '-5m' },
    },
  },
  {
    id: 'ETA-104',
    vehicleId: 'VEH-5091',
    registration: 'DL-01-GH-5091',
    vehicleType: '24ft Cold Container Truck',
    driver: 'David Kim',
    driverPhone: '+1 (555) 567-8901',
    currentLocation: 'Adilabad Express Highway Mile 18',
    origin: 'Hyderabad MedTech Park',
    destination: 'Nagpur Central Hub',
    scheduledArrival: 'Today, 15:30',
    predictedArrival: 'Today, 15:45',
    varianceMinutes: 15,
    onTimeProbability: 68,
    status: 'at_risk',
    customer: 'Apollo Hospitals Pharma Hub',
    customerContact: 'coldchain@apollohospitals.org',
    serviceLevel: 'Critical Cold Chain (+3.8°C)',
    factors: {
      traffic: 'Moderate Toll Gate Queue (+15m impact)',
      distanceRemainingKm: 110,
      currentSpeedKmH: 65,
      segmentAvgSpeedKmH: 68,
      stopDurationMin: 10,
      weather: 'Warm Ambient (+32°C outside, Reefer Active)',
      historicalPattern: 'Moderate delay at state border toll',
    },
    breakdown: {
      drivingTimeMin: 95,
      stopTimeMin: 10,
      bufferMin: 5,
      totalRemainingMin: 110,
    },
    confidence: {
      percentage: 89,
      level: 'High',
      gpsSignal: '100%',
      trafficStream: 'Live Fastag Stream',
      hardwareHealth: 'Reefer Temp Constant +3.8°C',
    },
    whatIfScenarios: {
      fastagPass: { title: 'If Fastag Expressway Auto-Gate Cleared', newETA: '15:30', impact: '-15m (Recovers On-Time)' },
      reeferCheck: { title: 'If Reefer Unit Safety Inspection at Gate', newETA: '16:05', impact: '+20m Delay' },
    },
  },
  {
    id: 'ETA-105',
    vehicleId: 'VEH-7723',
    registration: 'KA-04-IJ-7723',
    vehicleType: '32ft Multi-Axle Trailer',
    driver: 'Rachel Green',
    driverPhone: '+1 (555) 678-9012',
    currentLocation: 'Bangalore-Chennai Golden Quadrilateral km 180',
    origin: 'Bangalore Electronic City',
    destination: 'Chennai Marine Terminal',
    scheduledArrival: 'Today, 17:00',
    predictedArrival: 'Today, 17:00',
    varianceMinutes: 0,
    onTimeProbability: 94,
    status: 'on_time',
    customer: 'Samsung High-Tech Logistics',
    customerContact: 'freight@samsung.com',
    serviceLevel: 'Export Time-Critical',
    factors: {
      traffic: 'Free Flow Highway Corridor',
      distanceRemainingKm: 110,
      currentSpeedKmH: 72,
      segmentAvgSpeedKmH: 70,
      stopDurationMin: 0,
      weather: 'Clear',
      historicalPattern: 'Optimal trajectory',
    },
    breakdown: {
      drivingTimeMin: 90,
      stopTimeMin: 0,
      bufferMin: 5,
      totalRemainingMin: 95,
    },
    confidence: {
      percentage: 94,
      level: 'High',
      gpsSignal: '100%',
      trafficStream: 'Live',
      hardwareHealth: '100% OK',
    },
    whatIfScenarios: {
      portQueue: { title: 'If Port Container Terminal Backlog Occurs', newETA: '17:40', impact: '+40m' },
      expressLane: { title: 'If Special Green Freight Corridor Access', newETA: '16:45', impact: '-15m Early' },
    },
  },
];

export const etaModelMetrics = {
  averageAccuracyPct: 96.8,
  confidenceIntervalMin: 8,
  activeTrackedCount: 212,
  onTimeCount: 178,
  atRiskCount: 22,
  delayedCount: 12,
  slaBreachPreventionRate: 94.2,
  modelEngine: 'Gradient Boosted Spatial-Temporal Regressor (v4.8)',
  lastRetrained: '24 mins ago (Auto-calibrated on 48,000 trips)',
};

