/**
 * LOGISTICSHUB — MOCK DATA: Live Tracking & Visibility
 * Source: COMPLETE_UI_DESIGN_PROMPT.md — SECTION 13 (Live Tracking & Visibility)
 */

export const liveTrackedVehicles = [
  {
    id: 'VEH-3042',
    registration: 'MH-12-AB-3042',
    driver: 'John Smith',
    driverPhone: '+1 (555) 234-5678',
    vehicleType: '20ft Box Truck',
    status: 'on_time', // on_time | at_risk | delayed | idle | offline
    speedKmH: 68,
    heading: 'North-East (NE 42°)',
    fuelPct: 82,
    tempC: '+4.2°C (Reefer Pass)',
    currentTripId: 'TRIP-870',
    origin: 'Mumbai Central Hub',
    destination: 'Pune MIDC Sector 4',
    nextStop: 'Apex Supermarkets Receiving Dock',
    distanceRemainingKm: 64,
    eta: 'Today 12:00',
    delayMinutes: 0,
    lastUpdated: 'Just now (Live Ping)',
    x: 180,
    y: 190,
    breadcrumbs: [
      { x: 80, y: 180 },
      { x: 130, y: 185 },
      { x: 180, y: 190 },
    ],
    geofenceInside: 'Westside Logistics Park',
  },
  {
    id: 'VEH-8190',
    registration: 'MH-14-CD-8190',
    driver: 'Elena Rostova',
    driverPhone: '+1 (555) 345-6789',
    vehicleType: '32ft Multi-Axle Trailer',
    status: 'at_risk',
    speedKmH: 42,
    heading: 'South (S 180°)',
    fuelPct: 74,
    tempC: 'Ambient (+22°C)',
    currentTripId: 'TRIP-865',
    origin: 'Delhi Gate North',
    destination: 'Jaipur Industrial Corridor',
    nextStop: 'Highway Toll Gate Plaza 3',
    distanceRemainingKm: 142,
    eta: 'Today 16:30',
    delayMinutes: 14,
    lastUpdated: '1 min ago',
    x: 360,
    y: 110,
    breadcrumbs: [
      { x: 300, y: 60 },
      { x: 330, y: 85 },
      { x: 360, y: 110 },
    ],
    geofenceInside: 'Northern Freight Highway Corridor',
  },
  {
    id: 'VEH-1024',
    registration: 'GJ-01-EF-1024',
    driver: 'Marcus Brody',
    driverPhone: '+1 (555) 456-7890',
    vehicleType: 'Sprinter Courier Van',
    status: 'on_time',
    speedKmH: 54,
    heading: 'East (E 90°)',
    fuelPct: 91,
    tempC: 'Ambient (+20°C)',
    currentTripId: 'TRIP-881',
    origin: 'Ahmedabad SEZ Gate',
    destination: 'Vadodara City Terminal',
    nextStop: 'Zenith Electronics Hub',
    distanceRemainingKm: 28,
    eta: 'Today 09:30',
    delayMinutes: 0,
    lastUpdated: 'Live Ping',
    x: 480,
    y: 220,
    breadcrumbs: [
      { x: 420, y: 200 },
      { x: 450, y: 210 },
      { x: 480, y: 220 },
    ],
    geofenceInside: 'Eastern Industrial Zone',
  },
  {
    id: 'VEH-5091',
    registration: 'DL-01-GH-5091',
    driver: 'David Kim',
    driverPhone: '+1 (555) 567-8901',
    vehicleType: '24ft Container Truck',
    status: 'delayed',
    speedKmH: 15,
    heading: 'North (N 0°)',
    fuelPct: 65,
    tempC: '+3.8°C (Cold Chain Pass)',
    currentTripId: 'TRIP-872',
    origin: 'Hyderabad MedTech Park',
    destination: 'Nagpur Central Hub',
    nextStop: 'Highland Avenue Medical Center',
    distanceRemainingKm: 88,
    eta: 'Today 13:45',
    delayMinutes: 38,
    lastUpdated: '2 mins ago',
    x: 290,
    y: 310,
    breadcrumbs: [
      { x: 250, y: 330 },
      { x: 270, y: 320 },
      { x: 290, y: 310 },
    ],
    geofenceInside: 'Southern Metro Terminal',
  },
  {
    id: 'VEH-7723',
    registration: 'KA-04-IJ-7723',
    driver: 'Rachel Green',
    driverPhone: '+1 (555) 678-9012',
    vehicleType: '32ft Multi-Axle Trailer',
    status: 'on_time',
    speedKmH: 72,
    heading: 'West (W 270°)',
    fuelPct: 86,
    tempC: 'Ambient (+24°C)',
    currentTripId: 'TRIP-890',
    origin: 'Bangalore Electronic City',
    destination: 'Chennai Marine Terminal',
    nextStop: 'Coastal Freight Interchange',
    distanceRemainingKm: 110,
    eta: 'Today 17:00',
    delayMinutes: 0,
    lastUpdated: 'Live Ping',
    x: 540,
    y: 120,
    breadcrumbs: [
      { x: 480, y: 100 },
      { x: 510, y: 110 },
      { x: 540, y: 120 },
    ],
    geofenceInside: 'Coastal Port Logistics SEZ',
  },
  {
    id: 'VEH-2291',
    registration: 'TN-09-KL-2291',
    driver: 'Sam Taylor',
    driverPhone: '+1 (555) 789-0123',
    vehicleType: 'Medium Freight Van',
    status: 'offline',
    speedKmH: 0,
    heading: 'Stationary (0°)',
    fuelPct: 50,
    tempC: 'Ambient',
    currentTripId: null,
    origin: 'Depot Maintenance Bay',
    destination: 'Standby / Idle',
    nextStop: 'Scheduled Maintenance Bay 3',
    distanceRemainingKm: 0,
    eta: 'Standby',
    delayMinutes: 0,
    lastUpdated: '15 mins ago',
    x: 90,
    y: 280,
    breadcrumbs: [],
    geofenceInside: 'Central Hub Maintenance Yard',
  },
];

export const geofenceZones = [
  { id: 'geo-1', name: 'Westside Logistics Park', points: '40,140 160,120 180,240 60,250', color: 'rgba(37, 99, 235, 0.12)', border: '#3b82f6', activeVehicles: 4 },
  { id: 'geo-2', name: 'Northern Industrial Corridor', points: '280,30 420,20 440,140 300,150', color: 'rgba(16, 185, 129, 0.12)', border: '#10b981', activeVehicles: 6 },
  { id: 'geo-3', name: 'Eastern Port Terminal Zone', points: '460,80 590,70 610,210 470,220', color: 'rgba(245, 158, 11, 0.12)', border: '#f59e0b', activeVehicles: 5 },
  { id: 'geo-4', name: 'Southern Metro Distribution Hub', points: '220,260 380,250 400,360 230,370', color: 'rgba(124, 58, 237, 0.12)', border: '#7c3aed', activeVehicles: 3 },
];

export const trackingGlobalStats = {
  totalVehicles: 234,
  onlineTracked: 212,
  onTime: 145,
  atRisk: 34,
  delayed: 22,
  offline: 22,
  fleetUtilizationPct: 89.2,
};
